/// The fixed module prelude: header, type aliases, the pagination envelope, the
/// error type, and the abstract transport the runtime later supplies.
pub(crate) const PREAMBLE: &str = r#"// Generated by `based gen client` (target: rust). Do not edit by hand.
//
// The closed RPC surface: one input type, one output type, and one route per
// signature. Transport is abstract — implement `Transport` to post JSON to a route
// and decode the reply; the runtime supplies the concrete HTTP client.
//
// Some generated items may be unused by a given consumer; suppress dead-code warnings by
// including this module under an outer `#[allow(dead_code)] mod client { … }` (an inner
// `#![allow]` would be rejected by `include!`).

use serde::{Deserialize, Serialize};
use std::marker::PhantomData;

// Semantic aliases for the wire types (mirrors the DDL mapping).
pub type Uuid = String;
pub type Timestamp = String;
pub type Date = String;
pub type Time = String;
// A `bytes` value is base64-encoded on the wire — carried as its base64 string.
pub type Bytes = String;
pub type Json = serde_json::Value;

/// A wire boolean. A `bool` column rides the wire as a real JSON `true`/`false` on
/// Postgres, but as the `0`/`1` of its backing integer on MySQL and SQLite (which lose the
/// boolean type at the value level). This accepts either form so the same client decodes a
/// response from any dialect; it serializes back as a real JSON bool.
struct BoolWire(bool);

impl<'de> Deserialize<'de> for BoolWire {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        struct V;
        impl serde::de::Visitor<'_> for V {
            type Value = bool;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a boolean or 0/1")
            }
            fn visit_bool<E>(self, v: bool) -> Result<bool, E> {
                Ok(v)
            }
            fn visit_i64<E>(self, v: i64) -> Result<bool, E> {
                Ok(v != 0)
            }
            fn visit_u64<E>(self, v: u64) -> Result<bool, E> {
                Ok(v != 0)
            }
        }
        d.deserialize_any(V).map(BoolWire)
    }
}

fn de_bool<'de, D: serde::Deserializer<'de>>(d: D) -> Result<bool, D::Error> {
    BoolWire::deserialize(d).map(|b| b.0)
}

fn de_bool_opt<'de, D: serde::Deserializer<'de>>(d: D) -> Result<Option<bool>, D::Error> {
    Ok(Option::<BoolWire>::deserialize(d)?.map(|b| b.0))
}

fn de_bool_vec<'de, D: serde::Deserializer<'de>>(d: D) -> Result<Vec<bool>, D::Error> {
    Ok(Vec::<BoolWire>::deserialize(d)?
        .into_iter()
        .map(|b| b.0)
        .collect())
}

fn de_bool_opt_vec<'de, D: serde::Deserializer<'de>>(
    d: D,
) -> Result<Option<Vec<bool>>, D::Error> {
    Ok(Option::<Vec<BoolWire>>::deserialize(d)?.map(|v| v.into_iter().map(|b| b.0).collect()))
}

/// A typed id: the primary key of entity `E`. The wire repr is honest to the entity's
/// key strategy — a `uuid`/`ulid` id is a JSON string, a `serial` id a JSON number — so
/// this (de)serializes transparently as either (`numeric` records which). The `E` marker
/// keeps ids of different entities distinct types, so a `User` id can't be passed where an
/// `Org` id is wanted. A `create_*` result already hands one back typed; turn a raw value
/// into one only through the explicit, greppable `Id::from_raw` / `Id::from_int`.
pub struct Id<E> {
    raw: String,
    /// A `serial` (integer) id serializes as a JSON number; a uuid/ulid id as a string.
    numeric: bool,
    _entity: PhantomData<fn() -> E>,
}

impl<E> Id<E> {
    /// Wrap a raw string id (a uuid/ulid) as a typed id — the explicit escape from an
    /// untyped string, used only where the string's entity is known.
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Id {
            raw: raw.into(),
            numeric: false,
            _entity: PhantomData,
        }
    }
    /// Wrap an integer id (a `serial` key) as a typed id — it serializes as a JSON number.
    pub fn from_int(n: i64) -> Self {
        Id {
            raw: n.to_string(),
            numeric: true,
            _entity: PhantomData,
        }
    }
    /// The underlying id as a string (a `serial` id's decimal form).
    pub fn as_str(&self) -> &str {
        &self.raw
    }
    /// Consume into the raw id string.
    pub fn into_raw(self) -> String {
        self.raw
    }
}

impl<E> Serialize for Id<E> {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        // A serial id crosses the wire as a JSON number; a uuid/ulid id as a string.
        match (self.numeric, self.raw.parse::<i64>()) {
            (true, Ok(n)) => s.serialize_i64(n),
            _ => s.serialize_str(&self.raw),
        }
    }
}

impl<'de, E> Deserialize<'de> for Id<E> {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        struct V<E>(PhantomData<fn() -> E>);
        impl<E> serde::de::Visitor<'_> for V<E> {
            type Value = Id<E>;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("a string or integer id")
            }
            fn visit_str<Err>(self, v: &str) -> Result<Id<E>, Err> {
                Ok(Id::from_raw(v))
            }
            fn visit_i64<Err>(self, v: i64) -> Result<Id<E>, Err> {
                Ok(Id::from_int(v))
            }
            fn visit_u64<Err>(self, v: u64) -> Result<Id<E>, Err> {
                Ok(Id::from_int(v as i64))
            }
        }
        d.deserialize_any(V(PhantomData))
    }
}

// Hand-written so the marker `E` carries no trait bounds (a derive would demand
// `E: Clone`, `E: Ord`, … of a type that only ever tags).
impl<E> Clone for Id<E> {
    fn clone(&self) -> Self {
        Id {
            raw: self.raw.clone(),
            numeric: self.numeric,
            _entity: PhantomData,
        }
    }
}
impl<E> std::fmt::Debug for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Id({:?})", self.raw)
    }
}
impl<E> std::fmt::Display for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.raw)
    }
}
impl<E> PartialEq for Id<E> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}
impl<E> Eq for Id<E> {}
impl<E> PartialOrd for Id<E> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl<E> Ord for Id<E> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.raw.cmp(&other.raw)
    }
}
impl<E> std::hash::Hash for Id<E> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.raw.hash(state);
    }
}

/// An opaque keyset pagination cursor, carried on the wire as its underlying string
/// (`#[serde(transparent)]`, so the wire is unchanged). A page result hands one back and
/// the caller feeds it to the next call; its contents (the sort-key basis) are a runtime
/// concern the caller never assembles. Turn a raw string into one only through the
/// explicit, greppable `Cursor::from_raw`.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Cursor(String);

impl Cursor {
    /// Wrap a raw cursor string — the explicit escape used only where a cursor string
    /// arrives from outside the client (normally a page result already hands one back typed).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Cursor(raw.into())
    }
    /// The underlying cursor string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
    /// Consume into the raw cursor string.
    pub fn into_raw(self) -> String {
        self.0
    }
}

impl std::fmt::Debug for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Cursor({:?})", self.0)
    }
}
impl std::fmt::Display for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Pagination envelope: a paginated query returns rows + an opaque cursor.
/// Next page = the same call carrying `cursor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub cursor: Option<Cursor>,
    /// Total matching rows. `Some` exactly when the query declares `with count`
    /// (the wire carries `total` only then).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

/// What went wrong in a client call — lets a caller branch on the class of failure
/// without matching on the message text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientErrorKind {
    /// The request never completed a round-trip — a socket/connection/engine failure.
    /// Retryable in the same way the underlying transport is.
    Transport,
    /// The round-trip completed but a value could not be (de)serialized into its typed
    /// input or output. A bug in the caller's types or the payload, not a server error.
    Decode,
    /// The server ran the call and returned a structured error (its HTTP `status` and a
    /// stable machine `code`, e.g. `bad_arg`, `missing_ctx`, `database_error`).
    Api { status: u16, code: String },
}

/// An error from a client call: a transport failure, a (de)serialization failure, or a
/// structured error the server returned. Carries a stable machine [`code`](ClientError::code)
/// and a clear human message; a server error also carries its HTTP [`status`](ClientError::status).
/// Implements `std::error::Error`, so it chains with `?` and its underlying cause is reachable
/// via `source()`.
#[derive(Debug, Clone)]
pub struct ClientError {
    kind: ClientErrorKind,
    message: String,
    // Kept behind an `Arc` so `ClientError` stays `Clone` while still handing back a live
    // `&dyn Error` from `source()`.
    source: Option<std::sync::Arc<dyn std::error::Error + Send + Sync + 'static>>,
}

impl ClientError {
    /// A transport failure (the round-trip never completed), wrapping its cause.
    pub fn transport(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Transport,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A (de)serialization failure decoding an input or the reply, wrapping its cause.
    pub fn decode(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Decode,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A structured error the server returned: its HTTP `status`, stable machine `code`, and
    /// human `message` (the `{ error: { code, message } }` envelope).
    pub fn api(status: u16, code: impl Into<String>, message: impl Into<String>) -> Self {
        ClientError {
            kind: ClientErrorKind::Api {
                status,
                code: code.into(),
            },
            message: message.into(),
            source: None,
        }
    }

    /// The failure class (transport / decode / server-side api).
    pub fn kind(&self) -> &ClientErrorKind {
        &self.kind
    }

    /// The human-readable message.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// A stable machine-readable code: the server's `error.code` for an api failure, else
    /// `"transport"` / `"decode"`. Safe to branch on.
    pub fn code(&self) -> &str {
        match &self.kind {
            ClientErrorKind::Transport => "transport",
            ClientErrorKind::Decode => "decode",
            ClientErrorKind::Api { code, .. } => code,
        }
    }

    /// The HTTP status of a server-side (api) failure; `None` for a transport/decode failure.
    pub fn status(&self) -> Option<u16> {
        match &self.kind {
            ClientErrorKind::Api { status, .. } => Some(*status),
            _ => None,
        }
    }
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ClientErrorKind::Transport => write!(f, "transport error: {}", self.message),
            ClientErrorKind::Decode => write!(f, "decode error: {}", self.message),
            ClientErrorKind::Api { status, code } => {
                write!(f, "server error {status} [{code}]: {}", self.message)
            }
        }
    }
}

impl std::error::Error for ClientError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|e| &**e as &(dyn std::error::Error + 'static))
    }
}
"#;

/// The `-> ok` acknowledgement body, emitted only for a schema with an ack
/// mutation: the wire success is `{}`, this decodes it, and the method returns
/// unit — the caller never sees the type.
pub(crate) const ACK: &str = r#"
/// The empty acknowledgement a `-> ok` mutation answers with (`{}` on the wire —
/// a real DELETE leaves no row to return). Methods decode it and return `()`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ack {}
"#;
