// Generated by `based gen client` (target: rust). Do not edit by hand.
//
// The closed RPC surface: one input type, one output type, and one route per
// signature. Transport is abstract — implement `Transport` to post JSON to a route
// and decode the reply; the runtime supplies the concrete HTTP client.
//
// Some generated items may be unused by a given consumer; suppress dead-code warnings by
// including this module under an outer `#[allow(dead_code)] mod client { … }` (an inner
// `#![allow]` would be rejected by `include!`).

use serde::{Deserialize, Serialize};
use std::marker::PhantomData;

// Semantic aliases for the wire types (mirrors the DDL mapping).
pub type Uuid = String;
pub type Timestamp = String;
pub type Date = String;
pub type Json = serde_json::Value;

/// A typed id: the primary key of entity `E`, carried on the wire as its raw string
/// (`#[serde(transparent)]`, so the wire is unchanged). The `E` marker keeps ids of
/// different entities distinct types, so a `User` id can't be passed where an `Org` id
/// is wanted. A `create_*` result already hands one back typed; turn a raw string into
/// one only through the explicit, greppable `Id::from_raw`.
#[derive(Serialize, Deserialize)]
#[serde(transparent, bound = "")]
pub struct Id<E> {
    raw: String,
    #[serde(skip)]
    _entity: PhantomData<fn() -> E>,
}

impl<E> Id<E> {
    /// Wrap a raw id string as a typed id — the explicit escape from an untyped string,
    /// used only where the string's entity is known (an id from outside the client).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Id {
            raw: raw.into(),
            _entity: PhantomData,
        }
    }
    /// The underlying id string.
    pub fn as_str(&self) -> &str {
        &self.raw
    }
    /// Consume into the raw id string.
    pub fn into_raw(self) -> String {
        self.raw
    }
}

// Hand-written so the marker `E` carries no trait bounds (a derive would demand
// `E: Clone`, `E: Ord`, … of a type that only ever tags).
impl<E> Clone for Id<E> {
    fn clone(&self) -> Self {
        Id {
            raw: self.raw.clone(),
            _entity: PhantomData,
        }
    }
}
impl<E> std::fmt::Debug for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Id({:?})", self.raw)
    }
}
impl<E> std::fmt::Display for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.raw)
    }
}
impl<E> PartialEq for Id<E> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}
impl<E> Eq for Id<E> {}
impl<E> PartialOrd for Id<E> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl<E> Ord for Id<E> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.raw.cmp(&other.raw)
    }
}
impl<E> std::hash::Hash for Id<E> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.raw.hash(state);
    }
}

/// An opaque keyset pagination cursor, carried on the wire as its underlying string
/// (`#[serde(transparent)]`, so the wire is unchanged). A page result hands one back and
/// the caller feeds it to the next call; its contents (the sort-key basis) are a runtime
/// concern the caller never assembles. Turn a raw string into one only through the
/// explicit, greppable `Cursor::from_raw`.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Cursor(String);

impl Cursor {
    /// Wrap a raw cursor string — the explicit escape used only where a cursor string
    /// arrives from outside the client (normally a page result already hands one back typed).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Cursor(raw.into())
    }
    /// The underlying cursor string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
    /// Consume into the raw cursor string.
    pub fn into_raw(self) -> String {
        self.0
    }
}

impl std::fmt::Debug for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Cursor({:?})", self.0)
    }
}
impl std::fmt::Display for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Pagination envelope: a paginated query returns rows + an opaque cursor.
/// Next page = the same call carrying `cursor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub cursor: Option<Cursor>,
}

/// What went wrong in a client call — lets a caller branch on the class of failure
/// without matching on the message text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientErrorKind {
    /// The request never completed a round-trip — a socket/connection/engine failure.
    /// Retryable in the same way the underlying transport is.
    Transport,
    /// The round-trip completed but a value could not be (de)serialized into its typed
    /// input or output. A bug in the caller's types or the payload, not a server error.
    Decode,
    /// The server ran the call and returned a structured error (its HTTP `status` and a
    /// stable machine `code`, e.g. `bad_arg`, `missing_ctx`, `database_error`).
    Api { status: u16, code: String },
}

/// An error from a client call: a transport failure, a (de)serialization failure, or a
/// structured error the server returned. Carries a stable machine [`code`](ClientError::code)
/// and a clear human message; a server error also carries its HTTP [`status`](ClientError::status).
/// Implements `std::error::Error`, so it chains with `?` and its underlying cause is reachable
/// via `source()`.
#[derive(Debug, Clone)]
pub struct ClientError {
    kind: ClientErrorKind,
    message: String,
    // Kept behind an `Arc` so `ClientError` stays `Clone` while still handing back a live
    // `&dyn Error` from `source()`.
    source: Option<std::sync::Arc<dyn std::error::Error + Send + Sync + 'static>>,
}

impl ClientError {
    /// A transport failure (the round-trip never completed), wrapping its cause.
    pub fn transport(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Transport,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A (de)serialization failure decoding an input or the reply, wrapping its cause.
    pub fn decode(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Decode,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A structured error the server returned: its HTTP `status`, stable machine `code`, and
    /// human `message` (the `{ error: { code, message } }` envelope).
    pub fn api(status: u16, code: impl Into<String>, message: impl Into<String>) -> Self {
        ClientError {
            kind: ClientErrorKind::Api {
                status,
                code: code.into(),
            },
            message: message.into(),
            source: None,
        }
    }

    /// The failure class (transport / decode / server-side api).
    pub fn kind(&self) -> &ClientErrorKind {
        &self.kind
    }

    /// The human-readable message.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// A stable machine-readable code: the server's `error.code` for an api failure, else
    /// `"transport"` / `"decode"`. Safe to branch on.
    pub fn code(&self) -> &str {
        match &self.kind {
            ClientErrorKind::Transport => "transport",
            ClientErrorKind::Decode => "decode",
            ClientErrorKind::Api { code, .. } => code,
        }
    }

    /// The HTTP status of a server-side (api) failure; `None` for a transport/decode failure.
    pub fn status(&self) -> Option<u16> {
        match &self.kind {
            ClientErrorKind::Api { status, .. } => Some(*status),
            _ => None,
        }
    }
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ClientErrorKind::Transport => write!(f, "transport error: {}", self.message),
            ClientErrorKind::Decode => write!(f, "decode error: {}", self.message),
            ClientErrorKind::Api { status, code } => {
                write!(f, "server error {status} [{code}]: {}", self.message)
            }
        }
    }
}

impl std::error::Error for ClientError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|e| &**e as &(dyn std::error::Error + 'static))
    }
}

// ---------- streaming ----------

/// A live row stream from a `-> stream` query, in sort order. Each item is one typed
/// row; an in-band server failure or a truncated body arrives as an `Err` item, and
/// after an `Err` item the stream is finished. **Drop = cancel**: dropping the stream
/// abandons the pass and releases its resources (the server gets its database
/// connection back).
pub type RowStream<O> =
    std::pin::Pin<Box<dyn futures_core::Stream<Item = Result<O, ClientError>> + Send>>;

/// Decode an NDJSON response body (any stream of byte chunks) into the typed row
/// stream, enforcing the framing contract: one `{"row":…}` envelope per line, then
/// exactly one terminal line — `{"done":{"rows":N}}` on success (`rows` doubles as an
/// integrity checksum) or `{"error":{code,message}}` for an in-band failure (an `Err`
/// item carrying the server's stable code). A body that ends **without** a terminal
/// line was truncated (connection cut, server death) and yields a transport-kind
/// `Err`, never silent completion. An HTTP `Transport` feeds its response body
/// through this, so the framing rules live here once.
pub fn decode_ndjson<O, B, C, E>(body: B) -> RowStream<O>
where
    O: serde::de::DeserializeOwned + Send + 'static,
    B: futures_core::Stream<Item = Result<C, E>> + Send + 'static,
    C: AsRef<[u8]>,
    E: std::error::Error + Send + Sync + 'static,
{
    Box::pin(NdjsonRows {
        body: Box::pin(body),
        buf: Vec::new(),
        rows_seen: 0,
        body_done: false,
        finished: false,
        _row: PhantomData,
    })
}

/// The stream behind [`decode_ndjson`]: buffers body chunks, decodes each complete
/// line as one envelope, and tracks the terminal-line contract.
struct NdjsonRows<B, O> {
    body: std::pin::Pin<Box<B>>,
    buf: Vec<u8>,
    /// Rows yielded so far, checked against the terminal `done.rows` checksum.
    rows_seen: u64,
    /// The body ended (EOF). Reaching it before a terminal line is truncation.
    body_done: bool,
    /// A terminal line (or terminal `Err` item) was emitted; the stream is over.
    finished: bool,
    _row: PhantomData<fn() -> O>,
}

impl<B, C, E, O> futures_core::Stream for NdjsonRows<B, O>
where
    B: futures_core::Stream<Item = Result<C, E>>,
    C: AsRef<[u8]>,
    E: std::error::Error + Send + Sync + 'static,
    O: serde::de::DeserializeOwned,
{
    type Item = Result<O, ClientError>;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        use std::task::Poll;
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }
        loop {
            // Decode every complete buffered line before touching the transport.
            while let Some(pos) = this.buf.iter().position(|&b| b == b'\n') {
                let line: Vec<u8> = this.buf.drain(..=pos).collect();
                let line = &line[..line.len() - 1];
                if line.iter().all(|b| b.is_ascii_whitespace()) {
                    continue;
                }
                let envelope: serde_json::Value = match serde_json::from_slice(line) {
                    Ok(v) => v,
                    Err(e) => {
                        this.finished = true;
                        return Poll::Ready(Some(Err(ClientError::decode(e))));
                    }
                };
                if let Some(row) = envelope.get("row") {
                    this.rows_seen += 1;
                    return Poll::Ready(Some(match serde_json::from_value::<O>(row.clone()) {
                        Ok(row) => Ok(row),
                        Err(e) => {
                            this.finished = true;
                            Err(ClientError::decode(e))
                        }
                    }));
                }
                if let Some(done) = envelope.get("done") {
                    this.finished = true;
                    // `done.rows` is the integrity checksum: a disagreement means a
                    // row line was lost in transit — report it, never silent success.
                    let counted = done.get("rows").and_then(serde_json::Value::as_u64);
                    if counted != Some(this.rows_seen) {
                        return Poll::Ready(Some(Err(ClientError::transport(format!(
                            "stream checksum mismatch: server reports {counted:?} rows, received {}",
                            this.rows_seen
                        )))));
                    }
                    return Poll::Ready(None);
                }
                if let Some(error) = envelope.get("error") {
                    this.finished = true;
                    // The 200 status line was spent before the failure; 503 is the
                    // status the same database failure carries before the body.
                    let code = error["code"].as_str().unwrap_or("error");
                    let message = error["message"].as_str().unwrap_or("stream failed");
                    return Poll::Ready(Some(Err(ClientError::api(503, code, message))));
                }
                this.finished = true;
                return Poll::Ready(Some(Err(ClientError::transport(format!(
                    "unrecognized stream envelope: {envelope}"
                )))));
            }
            if this.body_done {
                // EOF without a terminal line (a partial line in the buffer counts):
                // the body was truncated. Never treat it as completion.
                this.finished = true;
                return Poll::Ready(Some(Err(ClientError::transport(
                    "response body ended without a terminal `done`/`error` line (truncated)"
                        .to_string(),
                ))));
            }
            match this.body.as_mut().poll_next(cx) {
                Poll::Ready(Some(Ok(chunk))) => this.buf.extend_from_slice(chunk.as_ref()),
                Poll::Ready(Some(Err(e))) => {
                    this.finished = true;
                    return Poll::Ready(Some(Err(ClientError::transport(e))));
                }
                Poll::Ready(None) => this.body_done = true,
                Poll::Pending => return Poll::Pending,
            }
        }
    }
}

/// Post a typed input to a route, carry the typed request context (`$ctx`, carried out
/// of band as request context), and decode the typed output. A callable with no `$ctx`
/// requirements passes `ctx: &()`. Async: a transport awaits its round-trip (an HTTP
/// client's socket, or the in-process engine's execution). Codegen only depends on
/// this shape.
#[allow(async_fn_in_trait)]
pub trait Transport {
    async fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned;

    /// Like [`call`](Transport::call), carrying a mutation **idempotency key** out of
    /// band — an HTTP transport sends it as the `Idempotency-Key` header; the embedded
    /// transport hands it to `Engine::call_with_key`. A retry with the same key replays
    /// the first attempt's recorded response instead of running the write again.
    async fn call_with_key<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
        key: &str,
    ) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned;

    /// Start a `-> stream` query and return its live row stream. An `Err` here means
    /// the call never started — a transport failure or a pre-body rejection carrying
    /// its real HTTP status; a failure after the stream begins arrives as the stream's
    /// final `Err` item. An HTTP transport feeds the NDJSON response body through
    /// [`decode_ndjson`]; the embedded transport yields the engine's rows in-process.
    async fn call_stream<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
    ) -> Result<RowStream<O>, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned + Send + 'static;
}

/// The generated client, generic over a `Transport`.
pub struct Client<T> {
    pub transport: T,
}

/// Phantom entity tags for `Id<entity::M>` (types only, never constructed).
pub mod entity {
    pub enum Org {}
    pub enum Order {}
}

// ---------- output types ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCard {
    pub status: String,
    pub total: i64,
}

// ---------- inputs + routes ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderByIdInput {
    pub id: Id<entity::Order>,
}
/// Wire route for `order_by_id`.
pub const ORDER_BY_ID_ROUTE: &str = "/q/order_by_id";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrdersInOrgInput {
    pub org: Id<entity::Org>,
}
/// Wire route for `orders_in_org`.
pub const ORDERS_IN_ORG_ROUTE: &str = "/q/orders_in_org";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportOrdersInput {
    pub org: Id<entity::Org>,
}
/// Wire route for `export_orders`.
pub const EXPORT_ORDERS_ROUTE: &str = "/q/export_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrgOrdersInput;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrgOrdersCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `my_org_orders`.
pub const MY_ORG_ORDERS_ROUTE: &str = "/q/my_org_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaceOrderInput {
    pub org: Id<entity::Org>,
    pub status: String,
    pub total: i64,
}
/// Wire route for `place_order`.
pub const PLACE_ORDER_ROUTE: &str = "/m/place_order";

// ---------- client ----------

impl<T: Transport> Client<T> {
    /// `POST /q/order_by_id`
    pub async fn order_by_id(&self, input: OrderByIdInput, ctx: ()) -> Result<Option<OrderCard>, ClientError> {
        self.transport.call(ORDER_BY_ID_ROUTE, &input, &ctx).await
    }
    /// `POST /q/orders_in_org`
    pub async fn orders_in_org(&self, input: OrdersInOrgInput, ctx: ()) -> Result<Vec<OrderCard>, ClientError> {
        self.transport.call(ORDERS_IN_ORG_ROUTE, &input, &ctx).await
    }
    /// `POST /q/export_orders` — a `-> stream` query: the rows arrive as a live typed
    /// stream; drop it to cancel the pass.
    pub async fn export_orders(&self, input: ExportOrdersInput, ctx: ()) -> Result<RowStream<OrderCard>, ClientError> {
        self.transport.call_stream(EXPORT_ORDERS_ROUTE, &input, &ctx).await
    }
    /// `POST /q/my_org_orders`
    pub async fn my_org_orders(&self, input: MyOrgOrdersInput, ctx: MyOrgOrdersCtx) -> Result<Vec<OrderCard>, ClientError> {
        self.transport.call(MY_ORG_ORDERS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/place_order`
    pub async fn place_order(&self, input: PlaceOrderInput, ctx: ()) -> Result<OrderCard, ClientError> {
        self.transport.call(PLACE_ORDER_ROUTE, &input, &ctx).await
    }
    /// `POST /m/place_order` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn place_order_with_key(
        &self,
        input: PlaceOrderInput,
        ctx: (),
        key: &str,
    ) -> Result<OrderCard, ClientError> {
        self.transport.call_with_key(PLACE_ORDER_ROUTE, &input, &ctx, key).await
    }
}

// ---------- embedded bridge (based_runtime::Engine) ----------

/// A `Transport` backed by an in-process `based_runtime::Engine` — every callable runs
/// through the engine's dispatch core with no socket. Build one with [`embedded`].
pub struct Embedded<'a> {
    engine: &'a based_runtime::Engine,
}

impl Transport for Embedded<'_> {
    async fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        let resp = self.engine.call(route, args, ctx).await;
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(ClientError::decode)
        } else {
            // Preserve the server's structured error: its status + stable code + message.
            let code = resp.body["error"]["code"].as_str().unwrap_or("error");
            let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
            Err(ClientError::api(resp.status, code, message))
        }
    }

    /// The keyed door in-process: the same idempotent-replay contract the HTTP
    /// `Idempotency-Key` header gets, via `Engine::call_with_key` — no header dance.
    async fn call_with_key<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
        key: &str,
    ) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        let resp = self
            .engine
            .call_with_key(route, args, ctx, Some(key.to_string()))
            .await;
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(ClientError::decode)
        } else {
            // Preserve the server's structured error: its status + stable code + message.
            let code = resp.body["error"]["code"].as_str().unwrap_or("error");
            let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
            Err(ClientError::api(resp.status, code, message))
        }
    }

    /// Start a `-> stream` query in-process: the engine's shaped row stream decoded
    /// into the typed shape — the same items the HTTP path yields, with no socket and
    /// no NDJSON round-trip. The stream owns its database connection; dropping it
    /// cancels the pass and returns the connection to the pool.
    async fn call_stream<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
    ) -> Result<RowStream<O>, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned + Send + 'static,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        match self.engine.call_stream(route, args, ctx).await {
            Ok(rows) => Ok(Box::pin(EngineRows {
                inner: rows,
                finished: false,
                _row: PhantomData,
            })),
            // A pre-body rejection: the same status + stable code the wire would send.
            Err(resp) => {
                let code = resp.body["error"]["code"].as_str().unwrap_or("error");
                let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
                Err(ClientError::api(resp.status, code, message))
            }
        }
    }
}

/// A ready-to-use client over an in-process `based_runtime::Engine` — no bridge to write.
/// `$ctx` is a typed per-call argument the app sets, not the caller; a public callable
/// passes `()`, which maps to an empty context bag.
pub fn embedded(engine: &based_runtime::Engine) -> Client<Embedded<'_>> {
    Client {
        transport: Embedded { engine },
    }
}

/// The embedded transport's row stream: `based_runtime::ShapedStream` items decoded
/// into the typed shape. After an `Err` item the stream is finished (the engine's
/// stream already ends after its error; a decode failure ends this one).
struct EngineRows<O> {
    inner: based_runtime::ShapedStream,
    finished: bool,
    _row: PhantomData<fn() -> O>,
}

impl<O: serde::de::DeserializeOwned> futures_core::Stream for EngineRows<O> {
    type Item = Result<O, ClientError>;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        use std::task::Poll;
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }
        match this.inner.as_mut().poll_next(cx) {
            Poll::Ready(Some(Ok(row))) => {
                Poll::Ready(Some(match serde_json::from_value::<O>(row) {
                    Ok(row) => Ok(row),
                    Err(e) => {
                        this.finished = true;
                        Err(ClientError::decode(e))
                    }
                }))
            }
            Poll::Ready(Some(Err(e))) => {
                this.finished = true;
                // A mid-pass database failure: the same stable code the wire's in-band
                // `error` line carries, with the 503 the failure maps to pre-body.
                Poll::Ready(Some(Err(ClientError::api(503, e.code(), e.message))))
            }
            Poll::Ready(None) => Poll::Ready(None),
            Poll::Pending => Poll::Pending,
        }
    }
}
