//! SQL DDL generation: `CheckedSchema` -> `CREATE TABLE` statements.
//!
//! One `CREATE TABLE` per model, emitted in schema order (deterministic). Each
//! table carries its columns, the `id` primary key, `(unique)` constraints, and
//! declared `@index`es. No foreign-key constraints are emitted — they are
//! opt-in, so the FK *column* exists but no `FOREIGN KEY` clause references it.
//!
//! Besides declared structure, each table carries the sema-inferred baseline
//! indexes: join-key indexes for inverse edges the access
//! layer traverses, named `inf_…` so engine-owned keys are distinguishable from
//! declared `idx_…` ones. On a `@soft_delete` model the soft-delete column is
//! prepended (predicate-leading — MariaDB has no partial indexes). Filter-path
//! indexes are *not* auto-created; they surface as the W0103 lint instead.
//!
//! ## Type mapping
//! | primitive   | MariaDB        | SQLite    | Postgres      | note |
//! |-------------|----------------|-----------|---------------|------|
//! | `text`      | `VARCHAR(255)` | `TEXT`    | `TEXT`        | MariaDB bounds it so it is index/unique-able; SQLite/Postgres have no length cap |
//! | `int`       | `BIGINT`       | `INTEGER` | `BIGINT`      | avoids silent overflow on money/counts (SQLite `INTEGER` is 64-bit) |
//! | `bool`      | `BOOLEAN`      | `INTEGER` | `BOOLEAN`     | SQLite has no bool type — stored as `0`/`1` (matches the runtime `SqliteDb` mapping) |
//! | `timestamp` | `DATETIME`     | `TEXT`    | `TIMESTAMPTZ` | MariaDB dodges `TIMESTAMP`'s implicit ON UPDATE + 2038; Postgres has a real tz-aware type |
//! | `date`      | `DATE`         | `TEXT`    | `DATE`        | |
//! | `json`      | `JSON`         | `TEXT`    | `JSONB`       | Postgres `JSONB` is the indexable/`@>`-queryable form (matches the DML `has` -> `@>`) |
//! | `uuid`/`Id` | `UUID`         | `TEXT`    | `UUID`        | native on MariaDB + Postgres; app-generated, no default. SQLite has no UUID type |
//!
//! A to-many scalar (`text[]`) has no columnar form; it maps to the dialect's JSON
//! type (a JSON array) — `JSON` on MariaDB, `TEXT` on SQLite, `JSONB` on Postgres.
//!
//! ## Index + quoting syntax (dialect-specific)
//! MariaDB emits declared + inferred indexes *inline* as `KEY` / `UNIQUE KEY` table
//! clauses. SQLite and Postgres have no inline index clause, so they emit separate
//! `CREATE INDEX` / `CREATE UNIQUE INDEX` statements after the table. Column-level
//! `(unique)` constraints stay inline in all three. Identifiers are backtick-quoted on
//! MariaDB/SQLite and double-quoted on Postgres ([`Dialect::quote`]).

use based_ast::{DefaultVal, Literal, Primitive};
use based_sema::{CheckedSchema, MemberKind, RModel};

use crate::Dialect;

pub mod dml;
pub mod mutations;

pub use dml::{lower_queries, LoweredQuery, ARRAY_MARK, KEYSET_PREFIX, NEST_SEP};
pub use mutations::{lower_mutations, LoweredMutation, LoweredWrite};

/// Render the whole schema as a DDL script (statements separated by blank lines).
pub fn ddl(schema: &CheckedSchema, dialect: Dialect) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "-- Generated by `based gen sql` (dialect: {}). Do not edit by hand.\n",
        dialect.name()
    ));
    for model in &schema.models {
        out.push('\n');
        out.push_str(&create_table(schema, model, dialect));
    }
    out
}

/// The set of index-like clauses a model carries, resolved to physical columns and
/// names. Shared by both dialects: MariaDB inlines them into the `CREATE TABLE`;
/// SQLite emits them as trailing `CREATE INDEX` statements.
struct IndexSpec {
    name: String,
    columns: Vec<String>,
    unique: bool,
}

/// Every declared + inferred index on a model, in emission order (declared first,
/// then the sema-inferred join-key baseline). Column names are already physical.
fn index_specs(model: &RModel) -> Vec<IndexSpec> {
    let mut specs = Vec::new();

    // Declared `@index`es (composite or single; unique or plain).
    for idx in &model.indexes {
        specs.push(IndexSpec {
            name: constraint_name(
                if idx.unique { "uq" } else { "idx" },
                &model.table,
                &idx.columns,
            ),
            columns: idx.columns.iter().map(|c| physical_col(model, c)).collect(),
            unique: idx.unique,
        });
    }

    // Inferred baseline indexes: join keys of traversed inverse
    // edges, deduped by sema against declared structure. Neither MariaDB nor SQLite
    // has partial indexes, so "predicate-leading" means the soft-delete column is
    // physically prepended — the engine filters it on every generated query.
    for idx in &model.inferred_indexes {
        let mut columns = idx.columns.clone();
        if let Some(sd) = &model.soft_delete {
            columns.insert(0, sd.field.clone());
        }
        specs.push(IndexSpec {
            name: constraint_name("inf", &model.table, &columns),
            columns: columns.iter().map(|c| physical_col(model, c)).collect(),
            unique: false,
        });
    }

    specs
}

/// One `CREATE TABLE` for a model: columns in declaration order, then the table
/// constraints (primary key, uniques, and — on MariaDB — the indexes inline). On
/// SQLite the indexes follow as separate `CREATE INDEX` statements (no inline form).
fn create_table(schema: &CheckedSchema, model: &RModel, dialect: Dialect) -> String {
    let mut lines: Vec<String> = Vec::new();

    // Columns: scalars and forward-relation FKs. Inverse edges store nothing here.
    for mem in &model.members {
        match &mem.kind {
            MemberKind::Scalar {
                ty,
                optional,
                many,
                column,
                default,
                ..
            } => {
                lines.push(column_line(
                    column,
                    sql_type(*ty, *many, dialect),
                    *optional,
                    default.as_ref(),
                    dialect,
                ));
            }
            MemberKind::Forward {
                fk_col,
                optional,
                target,
                ..
            } => {
                // FK column type mirrors the target's primary-key type (default uuid).
                let ty = fk_type(schema, target, dialect);
                lines.push(column_line(fk_col, ty, *optional, None, dialect));
            }
            MemberKind::Inverse { .. } => {}
        }
    }

    // Primary key — always `id`. It is the first member `skeleton` inserts.
    lines.push(format!("PRIMARY KEY ({})", dialect.quote("id")));

    // Column-level `(unique)` constraints, in member order. All dialects accept the
    // inline `CONSTRAINT … UNIQUE (…)` table clause.
    for mem in &model.members {
        if let MemberKind::Scalar {
            column,
            unique: true,
            ..
        } = &mem.kind
        {
            lines.push(format!(
                "CONSTRAINT {name} UNIQUE ({col})",
                name = dialect.quote(&constraint_name(
                    "uq",
                    &model.table,
                    std::slice::from_ref(column)
                )),
                col = dialect.quote(column),
            ));
        }
    }

    let specs = index_specs(model);

    // MariaDB inlines the indexes as `KEY` / `UNIQUE KEY` clauses; SQLite and Postgres
    // have no inline form, so they trail the table as `CREATE INDEX` statements.
    if dialect == Dialect::MariaDb {
        for spec in &specs {
            lines.push(inline_index_clause(dialect, spec));
        }
    }

    let body = lines
        .iter()
        .map(|l| format!("  {l}"))
        .collect::<Vec<_>>()
        .join(",\n");
    let mut out = format!(
        "CREATE TABLE {} (\n{body}\n);\n",
        dialect.quote(&model.table)
    );

    if dialect != Dialect::MariaDb {
        for spec in &specs {
            out.push_str(&create_index_stmt(dialect, &model.table, spec));
        }
    }
    out
}

/// A single column definition: `` `name` TYPE (NOT NULL|NULL) [DEFAULT x] ``.
fn column_line(
    column: &str,
    ty: &str,
    optional: bool,
    default: Option<&DefaultVal>,
    dialect: Dialect,
) -> String {
    let mut s = format!(
        "{} {ty} {}",
        dialect.quote(column),
        if optional { "NULL" } else { "NOT NULL" }
    );
    if let Some(dv) = default {
        s.push_str(" DEFAULT ");
        s.push_str(&render_default(dv, dialect));
    }
    s
}

/// A declared/inferred index as an inline MariaDB table clause. A unique index
/// becomes `UNIQUE KEY`, otherwise `KEY`. The name keeps field-derived readability;
/// the column list is physical (a relation field is its FK column, resolved upstream).
fn inline_index_clause(dialect: Dialect, spec: &IndexSpec) -> String {
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    let kind = if spec.unique { "UNIQUE KEY" } else { "KEY" };
    format!("{kind} {name} ({cols})", name = dialect.quote(&spec.name))
}

/// A declared/inferred index as a standalone `CREATE INDEX` statement (SQLite and
/// Postgres have no inline table-index clause). A unique index becomes `CREATE UNIQUE
/// INDEX`.
fn create_index_stmt(dialect: Dialect, table: &str, spec: &IndexSpec) -> String {
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    let kind = if spec.unique {
        "CREATE UNIQUE INDEX"
    } else {
        "CREATE INDEX"
    };
    format!(
        "{kind} {name} ON {table} ({cols});\n",
        name = dialect.quote(&spec.name),
        table = dialect.quote(table),
    )
}

/// Physical column backing a field: a scalar's column, or a forward relation's FK.
/// Falls back to the field name (an inverse edge or unknown field — the latter
/// sema already rejected via `E0122`).
fn physical_col(model: &RModel, field: &str) -> String {
    match model.member(field).map(|m| &m.kind) {
        Some(MemberKind::Scalar { column, .. }) => column.clone(),
        Some(MemberKind::Forward { fk_col, .. }) => fk_col.clone(),
        _ => field.to_string(),
    }
}

/// Stable, readable constraint/index name: `<prefix>_<table>_<col1>_<col2>`.
fn constraint_name(prefix: &str, table: &str, columns: &[String]) -> String {
    let mut name = format!("{prefix}_{table}");
    for c in columns {
        name.push('_');
        name.push_str(c);
    }
    name
}

/// SQL column type for a scalar primitive, per dialect (see the module type table).
/// A to-many scalar has no columnar form, so it is stored as a JSON array — the
/// dialect's JSON type (`JSON` on MariaDB, `TEXT` on SQLite, which has no JSON type).
/// `pub(crate)` so the migration renderer (`migrate`) maps neutral snapshot types
/// through the *same* table — one dialect type map, never a second that can drift (P4).
pub(crate) fn sql_type(ty: Primitive, many: bool, dialect: Dialect) -> &'static str {
    match dialect {
        Dialect::MariaDb => {
            if many {
                return "JSON";
            }
            match ty {
                Primitive::Text => "VARCHAR(255)",
                Primitive::Int => "BIGINT",
                Primitive::Bool => "BOOLEAN",
                Primitive::Timestamp => "DATETIME",
                Primitive::Date => "DATE",
                Primitive::Json => "JSON",
                Primitive::Uuid | Primitive::Id => "UUID",
            }
        }
        // SQLite has a tiny type set (its dynamic typing means these are affinities,
        // not constraints). The mapping mirrors the runtime `SqliteDb` value mapping:
        // bool ⇒ integer 0/1, json/uuid/timestamp/date ⇒ text.
        Dialect::Sqlite => {
            if many {
                return "TEXT";
            }
            match ty {
                Primitive::Text => "TEXT",
                Primitive::Int | Primitive::Bool => "INTEGER",
                Primitive::Timestamp | Primitive::Date => "TEXT",
                Primitive::Json => "TEXT",
                Primitive::Uuid | Primitive::Id => "TEXT",
            }
        }
        // Postgres has a rich, standards-track type set: real `BOOLEAN`, native `UUID`,
        // tz-aware `TIMESTAMPTZ`, and `JSONB` (the indexable/`@>`-queryable JSON form —
        // matching the DML `has` -> `@>` lowering). `text` is unbounded (no VARCHAR cap).
        Dialect::Postgres => {
            if many {
                return "JSONB";
            }
            match ty {
                Primitive::Text => "TEXT",
                Primitive::Int => "BIGINT",
                Primitive::Bool => "BOOLEAN",
                Primitive::Timestamp => "TIMESTAMPTZ",
                Primitive::Date => "DATE",
                Primitive::Json => "JSONB",
                Primitive::Uuid | Primitive::Id => "UUID",
            }
        }
    }
}

/// The SQL type of a relation's FK column — the target model's primary-key type.
/// Defaults to the dialect's id type (from the implicit `id`) when the target or
/// its key is missing, which sema would already have flagged.
fn fk_type(schema: &CheckedSchema, target: &str, dialect: Dialect) -> &'static str {
    match schema
        .model(target)
        .and_then(|m| m.member("id"))
        .map(|m| &m.kind)
    {
        Some(MemberKind::Scalar { ty, .. }) => sql_type(*ty, false, dialect),
        _ => sql_type(Primitive::Uuid, false, dialect),
    }
}

/// Render a `(default …)` value as a SQL literal / expression, per dialect. Only the
/// bool literal differs: MariaDB has `TRUE`/`FALSE` keywords; SQLite stores bools as
/// integers, so a bool default renders `1`/`0`.
fn render_default(dv: &DefaultVal, dialect: Dialect) -> String {
    match dv {
        DefaultVal::Lit(Literal::Str(s)) => format!("'{}'", s.replace('\'', "''")),
        DefaultVal::Lit(Literal::Int(i)) => i.to_string(),
        DefaultVal::Lit(Literal::Float(f)) => f.to_string(),
        DefaultVal::Lit(Literal::Bool(b)) => dialect.bool_lit(*b).to_string(),
        DefaultVal::Lit(Literal::Null) => "NULL".to_string(),
        // `now()` is the only value-position function (ir::KNOWN_FUNCS).
        DefaultVal::Func(_) => "CURRENT_TIMESTAMP".to_string(),
    }
}
