//! SQL DDL generation: `CheckedSchema` -> `CREATE TABLE` statements.
//!
//! One `CREATE TABLE` per model, emitted in schema order (deterministic). Each
//! table carries its columns, the `id` primary key, `(unique)` constraints, and
//! declared `@index`es. No foreign-key constraints are emitted — they are
//! opt-in, so the FK *column* exists but no `FOREIGN KEY` clause references it.
//!
//! The table's indexes are exactly the written `@index` set. On a `@soft_delete`
//! model a non-unique index's tombstone column is physically prepended
//! (predicate-leading — MariaDB has no partial indexes), so the written index still
//! leads with the column that selects.
//!
//! ## Type mapping
//! | primitive   | MariaDB        | SQLite    | Postgres      | note |
//! |-------------|----------------|-----------|---------------|------|
//! | `text`      | `VARCHAR(255)` | `TEXT`    | `TEXT`        | MariaDB bounds it so it is index/unique-able; SQLite/Postgres have no length cap |
//! | `int`       | `BIGINT`       | `INTEGER` | `BIGINT`      | avoids silent overflow on money/counts (SQLite `INTEGER` is 64-bit) |
//! | `bool`      | `BOOLEAN`      | `INTEGER` | `BOOLEAN`     | SQLite has no bool type — stored as `0`/`1` (matches the runtime `SqliteDb` mapping) |
//! | `timestamp` | `DATETIME`     | `TEXT`    | `TIMESTAMPTZ` | MariaDB dodges `TIMESTAMP`'s implicit ON UPDATE + 2038; Postgres has a real tz-aware type |
//! | `date`      | `DATE`         | `TEXT`    | `DATE`        | |
//! | `json`      | `JSON`         | `TEXT`    | `JSONB`       | Postgres `JSONB` is the indexable/`@>`-queryable form (matches the DML `has` -> `@>`) |
//! | `uuid`/`Id` | `CHAR(36)`     | `TEXT`    | `UUID`        | holds the app-minted v4 string; runs on every MySQL/MariaDB version. Native `UUID` (MariaDB 10.7+) via `raw`. Postgres has a native type. |
//! | `ulid`      | `CHAR(26)`     | `TEXT`    | `TEXT`        | an app-minted 26-char sortable string (not a valid `UUID` value) — a PK strategy (D110), valid only as `id` |
//! | `serial`    | `BIGINT`+AI    | `INTEGER` | `BIGINT`+ID   | a DB-generated sequential PK — `AUTO_INCREMENT` / `PRIMARY KEY AUTOINCREMENT` / `GENERATED ALWAYS AS IDENTITY` on the id column (see `serial_pk_column`); an FK to it is a plain integer |
//!
//! A to-many scalar (`text[]`) has no columnar form; it maps to the dialect's JSON
//! type (a JSON array) — `JSON` on MariaDB, `TEXT` on SQLite, `JSONB` on Postgres.
//!
//! ## Index + quoting syntax (dialect-specific)
//! MariaDB emits declared + inferred indexes *inline* as `KEY` / `UNIQUE KEY` table
//! clauses. SQLite and Postgres have no inline index clause, so they emit separate
//! `CREATE INDEX` / `CREATE UNIQUE INDEX` statements after the table. Column-level
//! `(unique)` constraints stay inline in all three. Identifiers are backtick-quoted on
//! MariaDB/SQLite and double-quoted on Postgres ([`Dialect::quote`]).

use based_ast::{DefaultVal, Literal, Primitive, RawSpec};
use based_sema::{CheckedSchema, ForeignKeys, MemberKind, RMember, RModel};

use crate::Dialect;

pub mod dml;
pub mod mutations;

pub use dml::{lower_queries, LoweredQuery, ARRAY_MARK, KEYSET_PREFIX, NEST_PRESENT, NEST_SEP};
pub use mutations::{lower_mutations, LoweredMutation, LoweredWrite};

/// Render the whole schema as a DDL script under the default `foreign_keys` convention
/// (`none` — a relation gets an FK only if it writes `@fk`). Convenience over
/// [`ddl_with`] for callers that don't thread the manifest convention.
pub fn ddl(schema: &CheckedSchema, dialect: Dialect) -> String {
    ddl_with(schema, dialect, ForeignKeys::None)
}

/// Render the whole schema as a DDL script (statements separated by blank lines) under a
/// given `foreign_keys` convention. FK constraints are emitted inline in each `CREATE
/// TABLE`, resolved per relation (the convention ⊕ `@fk`/`@no_fk`).
pub fn ddl_with(schema: &CheckedSchema, dialect: Dialect, fks: ForeignKeys) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "-- Generated by `based gen sql` (dialect: {}). Do not edit by hand.\n",
        dialect.name()
    ));
    for model in &schema.models {
        out.push('\n');
        out.push_str(&create_table(schema, model, dialect, fks));
    }
    out
}

/// The set of index-like clauses a model carries, resolved to physical columns and
/// names. Shared by both dialects: MariaDB inlines them into the `CREATE TABLE`;
/// SQLite emits them as trailing `CREATE INDEX` statements.
struct IndexSpec {
    name: String,
    columns: Vec<String>,
    unique: bool,
    /// `using <method>` — an access method the target must have (checked in sema).
    method: Option<String>,
    /// An opaque `@index raw("…")` body: everything after `ON <table>`.
    raw: Option<String>,
}

/// Every declared `@index` on a model, resolved to physical columns + a stable
/// name. A non-unique index on a `@soft_delete` model is rendered predicate-leading:
/// the always-filtered tombstone column is physically prepended (neither MariaDB nor
/// SQLite has partial indexes), so the written index still leads with what selects. A
/// unique index is a constraint — its column set is never reshaped.
fn index_specs(schema: &CheckedSchema, model: &RModel, dialect: Dialect) -> Vec<IndexSpec> {
    model
        .indexes
        .iter()
        .map(|idx| {
            if let Some(spec) = &idx.raw {
                return IndexSpec {
                    name: raw_index_name(&model.table, spec),
                    columns: Vec::new(),
                    unique: false,
                    method: None,
                    raw: Some(
                        spec.for_dialect(dialect.name())
                            .unwrap_or_default()
                            .to_string(),
                    ),
                };
            }
            let mut columns = idx.columns.clone();
            if !idx.unique {
                if let Some(sd) = &model.soft_delete {
                    if columns.first() != Some(&sd.field) {
                        columns.insert(0, sd.field.clone());
                    }
                }
            }
            IndexSpec {
                name: constraint_name(
                    if idx.unique { "uq" } else { "idx" },
                    &model.table,
                    &columns,
                ),
                columns: columns
                    .iter()
                    .flat_map(|c| physical_cols(schema, model, c))
                    .collect(),
                unique: idx.unique,
                method: idx.method.clone(),
                raw: None,
            }
        })
        .collect()
}

/// The physical column(s) backing a field in an index: a scalar's column or a single-column
/// FK, else the ordered `<field>_<part>` columns of a composite FK (so `@index enrollment`
/// on a relation into a composite-key model covers the whole multi-column FK).
fn physical_cols(schema: &CheckedSchema, model: &RModel, field: &str) -> Vec<String> {
    match model.member(field) {
        Some(mem) if matches!(mem.kind, MemberKind::Forward { .. }) => {
            let fks = schema.fk_columns(mem);
            if fks.len() > 1 {
                return fks.into_iter().map(|(c, _)| c).collect();
            }
            vec![physical_col(model, field)]
        }
        _ => vec![physical_col(model, field)],
    }
}

/// A stable, order-independent name for an opaque index: `idx_<table>_raw_<hash>` over
/// the canonical `raw(…)` body, so reordering a model's indexes never looks like a
/// rename and two different bodies never collide in the snapshot.
pub(crate) fn raw_index_name(table: &str, spec: &RawSpec) -> String {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in spec.canonical().as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("idx_{table}_raw_{:08x}", h as u32)
}

/// Is this index one MariaDB expresses as a table clause? The opaque `raw` form is
/// always a standalone `CREATE INDEX` (its body is not a column list).
fn inline_on_mariadb(spec: &IndexSpec) -> bool {
    spec.raw.is_none()
}

/// One `CREATE TABLE` for a model: columns in declaration order, then the table
/// constraints (primary key, uniques, and — on MariaDB — the indexes inline). On
/// SQLite the indexes follow as separate `CREATE INDEX` statements (no inline form).
fn create_table(
    schema: &CheckedSchema,
    model: &RModel,
    dialect: Dialect,
    fks: ForeignKeys,
) -> String {
    let mut lines: Vec<String> = column_lines(schema, model, dialect);

    // Primary key — the PK member's physical column(s): the `id` field's, the column a
    // single-column `@key(field)` nominates, or the ordered columns of a composite
    // `@key(f1, f2, …)`. A `@no_id` (keyless legacy) table has none. SQLite spells a
    // `serial` PK inline on the column (`INTEGER PRIMARY KEY AUTOINCREMENT`), so it needs no
    // separate clause; every other case (and every other dialect's serial) gets the clause.
    let sqlite_serial = dialect == Dialect::Sqlite && model.pk_is_db_generated();
    let pk_cols = model.pk_columns();
    if !pk_cols.is_empty() && !sqlite_serial {
        let cols = pk_cols
            .iter()
            .map(|c| dialect.quote(c))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("PRIMARY KEY ({cols})"));
    }

    // MariaDB/MySQL require an `AUTO_INCREMENT` column be the first column of some key. When
    // a composite key's `serial` part is *not* the leading PK column, the composite PRIMARY
    // KEY doesn't satisfy that, so add a covering `KEY` on the serial column alone.
    if dialect.is_mysql_family() {
        if let Some(sc) = model.serial_key_column() {
            if pk_cols.first() != Some(&sc) {
                lines.push(format!("KEY ({})", dialect.quote(&sc)));
            }
        }
    }
    lines.extend(constraint_lines(schema, model, dialect, fks));

    let specs = index_specs(schema, model, dialect);

    // MySQL/MariaDB inline the indexes as `KEY` / `UNIQUE KEY` clauses; SQLite and Postgres
    // have no inline form, so they trail the table as `CREATE INDEX` statements.
    if dialect.is_mysql_family() {
        for spec in specs.iter().filter(|s| inline_on_mariadb(s)) {
            lines.push(inline_index_clause(dialect, spec));
        }
    }

    let body = lines
        .iter()
        .map(|l| format!("  {l}"))
        .collect::<Vec<_>>()
        .join(",\n");
    let schema = model.schema.as_deref();
    let mut out = format!(
        "CREATE TABLE {} (\n{body}\n);\n",
        dialect.quote_table(schema, &model.table)
    );

    for spec in specs
        .iter()
        .filter(|s| !dialect.is_mysql_family() || !inline_on_mariadb(s))
    {
        out.push_str(&create_index_stmt(dialect, schema, &model.table, spec));
    }
    out
}

/// The column definitions: scalars and forward-relation FKs. Inverse edges store nothing.
fn column_lines(schema: &CheckedSchema, model: &RModel, dialect: Dialect) -> Vec<String> {
    let serial_pk = model.pk_is_db_generated();
    let serial_key_part = model.serial_key_member().map(|m| m.name.clone());
    let mut lines = Vec::new();
    for mem in &model.members {
        match &mem.kind {
            // A `serial` primary key: the DB owns the value, so its column carries the
            // dialect's auto-increment/identity clause instead of a plain type.
            MemberKind::Scalar { column, .. } if serial_pk && mem.name == "id" => {
                lines.push(serial_pk_column(dialect, column));
            }
            // A composite `@key`'s `serial` part: DB-generated on Postgres/MariaDB — its
            // column carries the identity/auto-increment clause (no inline PRIMARY KEY; the
            // composite PK clause covers it). SQLite has no auto-increment for a non-sole-PK
            // column, so it falls through to a plain `INTEGER` (this pattern needs the raw
            // hatch on SQLite).
            MemberKind::Scalar { column, .. }
                if serial_key_part.as_deref() == Some(mem.name.as_str())
                    && matches!(
                        dialect,
                        Dialect::Postgres | Dialect::MariaDb | Dialect::MySql
                    ) =>
            {
                lines.push(serial_pk_column(dialect, column));
            }
            MemberKind::Scalar {
                ty,
                optional,
                many,
                column,
                default,
                enum_name,
                raw_type,
                unique: _,
            } => {
                let en = enum_name.as_deref().and_then(|n| schema.enum_(n));
                // An opaque column's DB type is the literal the author wrote.
                let col_ty = match raw_type {
                    Some(spec) => spec
                        .for_dialect(dialect.name())
                        .unwrap_or_default()
                        .to_string(),
                    None => sql_type(*ty, *many, dialect),
                };
                lines.push(column_line(
                    column,
                    &col_ty,
                    *optional,
                    default.as_ref(),
                    en,
                    dialect,
                ));
            }
            MemberKind::Forward { optional, .. } => {
                // FK column(s) mirror the target's primary key: one column for a
                // single-column-key target, one `<field>_<part>` column per key part for a
                // composite-key target. Each column's type is that key part's own type.
                for (col, part) in schema.fk_columns(mem) {
                    let ty = key_part_sql_type(schema, part, dialect);
                    lines.push(column_line(&col, &ty, *optional, None, None, dialect));
                }
            }
            MemberKind::Inverse { .. } => {}
        }
    }
    lines
}

/// The table-level constraint clauses, in emission order: column `(unique)` constraints,
/// enum CHECKs, then foreign keys.
fn constraint_lines(
    schema: &CheckedSchema,
    model: &RModel,
    dialect: Dialect,
    fks: ForeignKeys,
) -> Vec<String> {
    let mut lines = Vec::new();

    // Column-level `(unique)` constraints, in member order. All dialects accept the
    // inline `CONSTRAINT … UNIQUE (…)` table clause.
    for mem in &model.members {
        if let MemberKind::Scalar {
            column,
            unique: true,
            ..
        } = &mem.kind
        {
            lines.push(format!(
                "CONSTRAINT {name} UNIQUE ({col})",
                name = dialect.quote(&constraint_name(
                    "uq",
                    &model.table,
                    std::slice::from_ref(column)
                )),
                col = dialect.quote(column),
            ));
        }
    }

    // Enum columns carry a DB-native CHECK constraint (`col IN ('v1', …)`) — the
    // dialect-honest form on every target (SQLite has no native enum type; Postgres's
    // `CREATE TYPE` and MariaDB's inline `ENUM(…)` both make a variant change an awkward
    // `ALTER TYPE`/`MODIFY`, so a text column + CHECK is the uniform, migration-simple
    // representation). Membership is also enforced by the DSL layer (E0154).
    for mem in &model.members {
        if let MemberKind::Scalar {
            column,
            enum_name: Some(en_name),
            ..
        } = &mem.kind
        {
            if let Some(en) = schema.enum_(en_name) {
                let values: Vec<String> = en
                    .variants
                    .iter()
                    .map(|v| enum_value_sql(&v.value))
                    .collect();
                lines.push(enum_check_clause(dialect, &model.table, column, &values));
            }
        }
    }

    // Foreign-key constraints — opt-in (the `foreign_keys` convention ⊕ per-relation
    // `@fk`/`@no_fk`). An inline table constraint works on all three targets (SQLite too).
    for fk in crate::migrate::foreign_key_snaps(schema, model, fks) {
        lines.push(fk_constraint_clause(dialect, &model.table, &fk));
    }
    lines
}

/// A single column definition: `` `name` TYPE (NOT NULL|NULL) [DEFAULT x] ``. `en` is the
/// column's enum, when enum-typed, so a variant default renders as its wire value.
fn column_line(
    column: &str,
    ty: &str,
    optional: bool,
    default: Option<&DefaultVal>,
    en: Option<&based_sema::REnum>,
    dialect: Dialect,
) -> String {
    let mut s = format!(
        "{} {ty} {}",
        dialect.quote(column),
        if optional { "NULL" } else { "NOT NULL" }
    );
    if let Some(dv) = default {
        s.push_str(" DEFAULT ");
        s.push_str(&render_default(dv, en, dialect));
    }
    s
}

/// A declared/inferred index as an inline MariaDB table clause. A unique index
/// becomes `UNIQUE KEY`, otherwise `KEY`. The name keeps field-derived readability;
/// the column list is physical (a relation field is its FK column, resolved upstream).
fn inline_index_clause(dialect: Dialect, spec: &IndexSpec) -> String {
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    // MariaDB spells its two exotic access methods as index *kinds* (`FULLTEXT KEY`),
    // and its B-tree/hash choice as a trailing `USING` — never Postgres's leading form.
    let (kind, using) = match spec.method.as_deref() {
        Some("fulltext") => ("FULLTEXT KEY", String::new()),
        Some("spatial") => ("SPATIAL KEY", String::new()),
        Some(m) => (
            if spec.unique { "UNIQUE KEY" } else { "KEY" },
            format!(" USING {}", m.to_uppercase()),
        ),
        None => (
            if spec.unique { "UNIQUE KEY" } else { "KEY" },
            String::new(),
        ),
    };
    format!(
        "{kind} {name} ({cols}){using}",
        name = dialect.quote(&spec.name)
    )
}

/// A declared/inferred index as a standalone `CREATE INDEX` statement (SQLite and
/// Postgres have no inline table-index clause). A unique index becomes `CREATE UNIQUE
/// INDEX`.
fn create_index_stmt(
    dialect: Dialect,
    schema: Option<&str>,
    table: &str,
    spec: &IndexSpec,
) -> String {
    format!("{};\n", create_index_sql(dialect, schema, table, spec))
}

/// A standalone `CREATE [UNIQUE] INDEX`, bare (no trailing `;`). An opaque index's body
/// rides verbatim in place of the column list; `using <method>` renders as Postgres's
/// leading `USING <m>` (MariaDB spells methods inline — see `inline_index_clause`).
fn create_index_sql(
    dialect: Dialect,
    schema: Option<&str>,
    table: &str,
    spec: &IndexSpec,
) -> String {
    let kind = if spec.unique {
        "CREATE UNIQUE INDEX"
    } else {
        "CREATE INDEX"
    };
    let name = dialect.quote(&spec.name);
    let table_q = dialect.quote_table(schema, table);
    if let Some(raw) = &spec.raw {
        return format!("{kind} {name} ON {table_q} {raw}");
    }
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    match spec.method.as_deref() {
        Some(m) => format!("{kind} {name} ON {table_q} USING {m} ({cols})"),
        None => format!("{kind} {name} ON {table_q} ({cols})"),
    }
}

/// Physical column backing a field: a scalar's column, or a forward relation's FK.
/// Falls back to the field name (an inverse edge or unknown field — the latter
/// sema already rejected via `E0122`).
fn physical_col(model: &RModel, field: &str) -> String {
    match model.member(field).map(|m| &m.kind) {
        Some(MemberKind::Scalar { column, .. }) => column.clone(),
        Some(MemberKind::Forward { fk_col, .. }) => fk_col.clone(),
        _ => field.to_string(),
    }
}

/// A single enum wire value rendered as a SQL literal: a string quoted, an int bare.
pub(crate) fn enum_value_sql(v: &based_sema::EnumValue) -> String {
    match v {
        based_sema::EnumValue::Str(s) => format!("'{}'", s.replace('\'', "''")),
        based_sema::EnumValue::Int(n) => n.to_string(),
    }
}

/// The `CONSTRAINT ck_<table>_<col> CHECK (<col> IN (v1, …))` clause enforcing an enum
/// column's values (each already rendered as a SQL literal — `'paid'` or `0`). Shared
/// with the migration renderer so a from-scratch migration matches `based gen sql`.
pub(crate) fn enum_check_clause(
    dialect: Dialect,
    table: &str,
    column: &str,
    values: &[String],
) -> String {
    let list = values.join(", ");
    format!(
        "CONSTRAINT {name} CHECK ({col} IN ({list}))",
        name = dialect.quote(&constraint_name(
            "ck",
            table,
            std::slice::from_ref(&column.to_string())
        )),
        col = dialect.quote(column),
    )
}

/// A `CONSTRAINT fk_<table>_<col> FOREIGN KEY (<col>) REFERENCES <ref>(<ref_col>) [ON
/// DELETE <a>] [ON UPDATE <a>]` clause. Valid inline on all three dialects (SQLite honors
/// an inline table FK); shared by `based gen sql` and the migration create-table renderer,
/// so a from-scratch migration matches the generated DDL.
pub(crate) fn fk_constraint_clause(
    dialect: Dialect,
    table: &str,
    fk: &crate::migrate::ForeignKeySnap,
) -> String {
    let name = constraint_name("fk", table, &fk.columns);
    let quote_list = |cols: &[String]| {
        cols.iter()
            .map(|c| dialect.quote(c))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let mut s = format!(
        "CONSTRAINT {name} FOREIGN KEY ({col}) REFERENCES {ref_table} ({ref_col})",
        name = dialect.quote(&name),
        col = quote_list(&fk.columns),
        ref_table = dialect.quote_table(fk.ref_schema.as_deref(), &fk.ref_table),
        ref_col = quote_list(&fk.ref_columns),
    );
    if let Some(a) = &fk.on_delete {
        s.push_str(&format!(" ON DELETE {}", fk_action_sql(a)));
    }
    if let Some(a) = &fk.on_update {
        s.push_str(&format!(" ON UPDATE {}", fk_action_sql(a)));
    }
    s
}

/// The SQL clause for a neutral referential-action spelling (`cascade` → `CASCADE`, …). A
/// hand-edited/unknown value rides through uppercased (parse/verify guards this upstream).
pub(crate) fn fk_action_sql(a: &str) -> String {
    match based_sema::FkAction::parse(a) {
        Some(act) => act.sql().to_string(),
        None => a.to_uppercase().replace('_', " "),
    }
}

/// Stable, readable constraint/index name: `<prefix>_<table>_<col1>_<col2>`.
fn constraint_name(prefix: &str, table: &str, columns: &[String]) -> String {
    let mut name = format!("{prefix}_{table}");
    for c in columns {
        name.push('_');
        name.push_str(c);
    }
    name
}

/// The full column definition for a `serial` (DB-generated sequential) primary key, from
/// one neutral spelling: MySQL/MariaDB `BIGINT NOT NULL AUTO_INCREMENT`, Postgres `BIGINT
/// GENERATED ALWAYS AS IDENTITY`, SQLite `INTEGER PRIMARY KEY AUTOINCREMENT` (SQLite's
/// only native auto-increment form is inline on the column, so the PK clause is omitted
/// for it — see `create_table`). Shared with the migration create-table renderer so a
/// from-scratch migration matches `based gen sql`.
pub(crate) fn serial_pk_column(dialect: Dialect, column: &str) -> String {
    let col = dialect.quote(column);
    match dialect {
        Dialect::MariaDb | Dialect::MySql => format!("{col} BIGINT NOT NULL AUTO_INCREMENT"),
        Dialect::Postgres => format!("{col} BIGINT GENERATED ALWAYS AS IDENTITY"),
        Dialect::Sqlite => format!("{col} INTEGER PRIMARY KEY AUTOINCREMENT"),
    }
}

/// SQL column type for a scalar primitive, per dialect (see the module type table).
/// A to-many scalar has no columnar form, so it is stored as a JSON array — the
/// dialect's JSON type (`JSON` on MariaDB, `TEXT` on SQLite, which has no JSON type).
/// `pub(crate)` so the migration renderer (`migrate`) maps neutral snapshot types
/// through the *same* table — one dialect type map, never a second that can drift.
pub(crate) fn sql_type(ty: Primitive, many: bool, dialect: Dialect) -> String {
    match dialect {
        // The MySQL/MariaDB family. `uuid`/`Id` is `CHAR(36)` — it holds the app-minted v4
        // string exactly and executes on every version (MySQL has no `UUID` type; MariaDB
        // added it only in 10.7). Native `UUID` (MariaDB 10.7+) stays reachable via `raw`.
        Dialect::MariaDb | Dialect::MySql => {
            if many {
                return "JSON".into();
            }
            match ty {
                Primitive::Text => "VARCHAR(255)".into(),
                Primitive::Int => "BIGINT".into(),
                Primitive::Bool => "BOOLEAN".into(),
                Primitive::Timestamp => "DATETIME".into(),
                Primitive::Date => "DATE".into(),
                Primitive::Time => "TIME".into(),
                // A binary blob — `BLOB` (no length; up to 64 KiB, the family's plain
                // variable binary). A bigger payload takes a raw `MEDIUMBLOB`/`LONGBLOB`.
                Primitive::Bytes => "BLOB".into(),
                Primitive::Json => "JSON".into(),
                Primitive::Uuid | Primitive::Id => "CHAR(36)".into(),
                // `ulid` is a 26-char Crockford-base32 string (not a UUID) — a fixed CHAR.
                Primitive::Ulid => "CHAR(26)".into(),
                // `serial`'s *storage* type — a plain `BIGINT` (the `AUTO_INCREMENT`
                // clause rides the PK column definition, not here; FK columns mirror this).
                Primitive::Serial => "BIGINT".into(),
                Primitive::Float => "DOUBLE".into(),
                Primitive::Decimal { precision, scale } => format!("DECIMAL({precision}, {scale})"),
            }
        }
        // SQLite has a tiny type set (its dynamic typing means these are affinities,
        // not constraints). The mapping mirrors the runtime `SqliteDb` value mapping:
        // bool ⇒ integer 0/1, json/uuid/timestamp/date ⇒ text. `decimal` takes TEXT
        // affinity (not SQLite's lossy NUMERIC): it is stored + returned as its exact
        // string, so no digit is lost and the wire form stays a JSON string as it is on
        // MariaDB/Postgres. (Comparison is therefore lexicographic on SQLite — a fixed
        // affinity limitation; production dialects use a true numeric DECIMAL.)
        Dialect::Sqlite => {
            if many {
                return "TEXT".into();
            }
            match ty {
                Primitive::Text => "TEXT".into(),
                Primitive::Int | Primitive::Bool => "INTEGER".into(),
                // SQLite has no native TIME — store the canonical `HH:MM:SS` string as
                // `TEXT` (the same degradation `date`/`timestamp`/`decimal` take here).
                Primitive::Timestamp | Primitive::Date | Primitive::Time => "TEXT".into(),
                Primitive::Bytes => "BLOB".into(),
                Primitive::Json => "TEXT".into(),
                Primitive::Uuid | Primitive::Id | Primitive::Ulid => "TEXT".into(),
                // `serial`'s storage type (the `PRIMARY KEY AUTOINCREMENT` rides the column).
                Primitive::Serial => "INTEGER".into(),
                Primitive::Float => "REAL".into(),
                Primitive::Decimal { .. } => "TEXT".into(),
            }
        }
        // Postgres has a rich, standards-track type set: real `BOOLEAN`, native `UUID`,
        // tz-aware `TIMESTAMPTZ`, and `JSONB` (the indexable/`@>`-queryable JSON form —
        // matching the DML `has` -> `@>` lowering). `text` is unbounded (no VARCHAR cap).
        Dialect::Postgres => {
            if many {
                return "JSONB".into();
            }
            match ty {
                Primitive::Text => "TEXT".into(),
                Primitive::Int => "BIGINT".into(),
                Primitive::Bool => "BOOLEAN".into(),
                Primitive::Timestamp => "TIMESTAMPTZ".into(),
                Primitive::Date => "DATE".into(),
                Primitive::Time => "TIME".into(),
                Primitive::Bytes => "BYTEA".into(),
                Primitive::Json => "JSONB".into(),
                Primitive::Uuid | Primitive::Id => "UUID".into(),
                // `ulid` is a 26-char string, not a valid `UUID` value — store as text.
                Primitive::Ulid => "TEXT".into(),
                // `serial`'s storage type (the `GENERATED … AS IDENTITY` clause rides the
                // PK column definition; FK columns mirror this plain `BIGINT`).
                Primitive::Serial => "BIGINT".into(),
                Primitive::Float => "DOUBLE PRECISION".into(),
                Primitive::Decimal { precision, scale } => format!("NUMERIC({precision}, {scale})"),
            }
        }
    }
}

/// The table the DB-backed idempotency store keeps its keys in — created in the same
/// database the mutations write to, so a keyed retry deduplicates across every app
/// instance sharing that database.
pub const IDEMPOTENCY_TABLE: &str = "_based_idempotency";

/// `CREATE TABLE IF NOT EXISTS` for the DB-backed idempotency store, rendered per dialect
/// through the shared DDL type map (not hand-rolled per driver). The `(callable, key)`
/// primary key is the unique index that makes a concurrent retry's claim block on the
/// first, still-uncommitted attempt and then replay its result; `response` is NULL while a
/// claim is in flight and set — inside the mutation's own transaction — when the write
/// records its result, so key + writes + response commit atomically. `created_at` anchors a
/// future age-based reclaim.
pub fn idempotency_table_ddl(dialect: Dialect) -> String {
    let text = sql_type(Primitive::Text, false, dialect);
    let ts = sql_type(Primitive::Timestamp, false, dialect);
    format!(
        "CREATE TABLE IF NOT EXISTS {tbl} (\n  \
         {callable} {text} NOT NULL,\n  \
         {key} {text} NOT NULL,\n  \
         {fp} {text} NOT NULL,\n  \
         {response} {text},\n  \
         {created} {ts} NOT NULL,\n  \
         PRIMARY KEY ({callable}, {key})\n);",
        tbl = dialect.quote(IDEMPOTENCY_TABLE),
        callable = dialect.quote("callable"),
        key = dialect.quote("key"),
        fp = dialect.quote("fingerprint"),
        response = dialect.quote("response"),
        created = dialect.quote("created_at"),
    )
}

/// The SQL type of a relation's FK column — the target model's primary-key type.
/// A PK with a `raw` type (e.g. native `UUID`) propagates that literal so the escape
/// hatch composes across the FK. Defaults to the dialect's id type (from the implicit
/// `id`) when the target or its key is missing, which sema would already have flagged.
fn fk_type(schema: &CheckedSchema, target: &str, dialect: Dialect) -> String {
    let id_kind = schema
        .model(target)
        .and_then(RModel::pk_member)
        .map(|m| &m.kind);
    if let Some(spec) = id_kind.and_then(|k| k.opaque()) {
        return spec
            .for_dialect(dialect.name())
            .unwrap_or_default()
            .to_string();
    }
    match id_kind {
        Some(MemberKind::Scalar { ty, .. }) => sql_type(*ty, false, dialect),
        _ => sql_type(Primitive::Uuid, false, dialect),
    }
}

/// The SQL type of a primary-key part column — used to type the FK column(s) that mirror
/// it. A scalar part carries its own (raw or primitive) type; a relation part (a junction
/// key `@key(order, product)`) carries its own target's key type, so the mirror composes.
fn key_part_sql_type(schema: &CheckedSchema, part: &RMember, dialect: Dialect) -> String {
    match &part.kind {
        MemberKind::Scalar {
            raw_type: Some(spec),
            ..
        } => spec
            .for_dialect(dialect.name())
            .unwrap_or_default()
            .to_string(),
        MemberKind::Scalar { ty, .. } => sql_type(*ty, false, dialect),
        MemberKind::Forward { target, .. } => fk_type(schema, target, dialect),
        MemberKind::Inverse { .. } => sql_type(Primitive::Uuid, false, dialect),
    }
}

/// Render a `(default …)` value as a SQL literal / expression, per dialect. Only the
/// bool literal differs: MariaDB has `TRUE`/`FALSE` keywords; SQLite stores bools as
/// integers, so a bool default renders `1`/`0`.
fn render_default(dv: &DefaultVal, en: Option<&based_sema::REnum>, dialect: Dialect) -> String {
    match dv {
        DefaultVal::Lit(Literal::Str(s)) => format!("'{}'", s.replace('\'', "''")),
        DefaultVal::Lit(Literal::Int(i)) => i.to_string(),
        DefaultVal::Lit(Literal::Decimal(s)) => s.clone(),
        DefaultVal::Lit(Literal::Bool(b)) => dialect.bool_lit(*b).to_string(),
        DefaultVal::Lit(Literal::Null) => "NULL".to_string(),
        // `now()` is the only value-position function (ir::KNOWN_FUNCS).
        DefaultVal::Func(_) => "CURRENT_TIMESTAMP".to_string(),
        // An enum default (`default pending`) is its variant's wire value: a quoted
        // string for a string enum, a bare integer for an int enum.
        DefaultVal::Variant(v) => en.and_then(|e| e.wire_of(&v.node)).map_or_else(
            || format!("'{}'", v.node.replace('\'', "''")),
            enum_value_sql,
        ),
    }
}
