/// Run generated Rust through `rustfmt`, so a checked-in generated client is formatted
/// exactly as `cargo fmt` would leave it: a re-`gen` never shows up as a whitespace diff,
/// and a consumer's `cargo fmt` leaves the file untouched. Applied at the write boundary
/// (`based gen client` and the staleness tests), keeping [`client`] itself a pure
/// schema→string function. Comment-preserving (unlike a syn round-trip,
/// which would drop the `// Generated by …` header and inline notes). Falls back to the
/// unformatted source if `rustfmt` is unavailable or rejects the input — the client still
/// compiles, just wider.
pub fn format_rust(src: &str) -> String {
    use std::io::Write;
    use std::process::{Command, Stdio};

    let Ok(mut child) = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout", "--quiet"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
    else {
        return src.to_string();
    };
    // Write the source and close stdin (drop) so rustfmt sees EOF before we read stdout.
    if let Some(mut stdin) = child.stdin.take() {
        if stdin.write_all(src.as_bytes()).is_err() {
            return src.to_string();
        }
    }
    match child.wait_with_output() {
        Ok(out) if out.status.success() => {
            String::from_utf8(out.stdout).unwrap_or_else(|_| src.to_string())
        }
        _ => src.to_string(),
    }
}
