use based_artifacts::{publish, Artifact, Error, Format, Policy};
use std::{
    fs,
    path::Path,
    time::{Duration, SystemTime},
};
use tempfile::TempDir;

fn artifact(root: &Path, name: &str, value: &str) -> Artifact {
    Artifact {
        path: root.join(name),
        format: Format::Rust,
        bytes: Format::Rust
            .annotate(
                &format!("// Generated by `based gen client`\n{value}\n"),
                "based gen client --out generated/client.rs",
            )
            .unwrap(),
    }
}

fn write() -> Policy {
    Policy::Write {
        overwrite_user_owned: false,
    }
}

#[test]
fn nested_generation_is_atomic_and_identical_outputs_keep_mtimes() {
    let root = TempDir::new().unwrap();
    let outputs = [artifact(root.path(), "generated/nested/client.rs", "old")];
    assert_eq!(
        publish(&outputs, write()).unwrap().written,
        [outputs[0].path.clone()]
    );
    let time = SystemTime::UNIX_EPOCH + Duration::from_secs(100_000);
    fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&outputs[0].path)
        .unwrap()
        .set_times(fs::FileTimes::new().set_modified(time))
        .unwrap();
    let before = fs::metadata(&outputs[0].path).unwrap().modified().unwrap();
    let report = publish(&outputs, write()).unwrap();
    assert!(report.written.is_empty());
    assert_eq!(
        fs::metadata(&outputs[0].path).unwrap().modified().unwrap(),
        before
    );
    let changed = [artifact(root.path(), "generated/nested/client.rs", "new")];
    publish(&changed, write()).unwrap();
    assert_eq!(fs::read(&changed[0].path).unwrap(), changed[0].bytes);
    assert_eq!(
        fs::read_dir(changed[0].path.parent().unwrap())
            .unwrap()
            .count(),
        1
    );
}

#[test]
fn check_is_nonwriting_for_missing_and_stale_outputs() {
    let root = TempDir::new().unwrap();
    let outputs = [artifact(root.path(), "missing/client.rs", "new")];
    assert!(matches!(
        publish(&outputs, Policy::Check),
        Err(Error::Stale(_))
    ));
    assert!(!root.path().join("missing").exists());
    fs::write(root.path().join("client.rs"), "handwritten").unwrap();
    let outputs = [artifact(root.path(), "client.rs", "new")];
    assert!(matches!(
        publish(&outputs, Policy::Check),
        Err(Error::Stale(_))
    ));
    assert_eq!(fs::read_to_string(&outputs[0].path).unwrap(), "handwritten");
}

#[test]
fn one_user_owned_output_prevents_publication_of_the_entire_set() {
    let root = TempDir::new().unwrap();
    let old = [artifact(root.path(), "first.rs", "old")];
    publish(&old, write()).unwrap();
    fs::write(root.path().join("second.rs"), "handwritten").unwrap();
    let outputs = [
        artifact(root.path(), "first.rs", "new"),
        artifact(root.path(), "second.rs", "new"),
    ];
    assert!(matches!(
        publish(&outputs, write()),
        Err(Error::UserOwned(_))
    ));
    assert_eq!(fs::read(&old[0].path).unwrap(), old[0].bytes);
    assert_eq!(
        fs::read_to_string(root.path().join("second.rs")).unwrap(),
        "handwritten"
    );
    publish(
        &outputs,
        Policy::Write {
            overwrite_user_owned: true,
        },
    )
    .unwrap();
    assert_eq!(fs::read(&outputs[1].path).unwrap(), outputs[1].bytes);
}

#[test]
fn duplicate_and_invalid_outputs_never_publish_a_partial_set() {
    let root = TempDir::new().unwrap();
    let duplicate = [
        artifact(root.path(), "client.rs", "first"),
        artifact(root.path(), "client.rs", "second"),
    ];
    assert!(publish(&duplicate, write()).is_err());
    assert!(!root.path().join("client.rs").exists());
    let invalid = [
        artifact(root.path(), "client.rs", "first"),
        Artifact {
            path: root.path().join("invalid.rs"),
            bytes: b"handwritten".to_vec(),
            format: Format::Rust,
        },
    ];
    assert!(publish(&invalid, write()).is_err());
    assert!(!root.path().join("client.rs").exists());
}

#[test]
fn json_metadata_round_trips_and_identifies_ownership() {
    let bytes = Format::OpenApi
        .annotate(
            r#"{"openapi":"3.1.0"}"#,
            "based gen openapi --out generated/api.json",
        )
        .unwrap();
    assert!(Format::OpenApi.owns(&bytes));
    let value: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(
        value["x-based-generated"]["regenerate"],
        "based gen openapi --out generated/api.json"
    );
    assert!(!Format::OpenApi.owns(br#"{"openapi":"3.1.0"}"#));
}

#[cfg(unix)]
#[test]
fn symlinks_are_never_followed_even_with_force() {
    let root = TempDir::new().unwrap();
    let target = root.path().join("handwritten.rs");
    fs::write(&target, "keep").unwrap();
    std::os::unix::fs::symlink(&target, root.path().join("client.rs")).unwrap();
    let outputs = [artifact(root.path(), "client.rs", "new")];
    assert!(publish(
        &outputs,
        Policy::Write {
            overwrite_user_owned: true
        }
    )
    .is_err());
    assert_eq!(fs::read_to_string(target).unwrap(), "keep");
}
