//! `CREATE TABLE` assembly: one table per model in schema order, carrying its columns,
//! primary key, `(unique)`/enum/FK constraints, and `@index`es. MariaDB inlines indexes
//! as `KEY`/`UNIQUE KEY` clauses; SQLite and Postgres trail them as `CREATE INDEX`
//! statements. FK constraints are opt-in, so an FK column exists without a `FOREIGN KEY`
//! clause unless the relation resolves to one. Identifiers quote per [`Dialect::quote`].

use super::*;

/// Render the whole schema as a DDL script under the default `foreign_keys` convention
/// (`none` — a relation gets an FK only if it writes `@fk`). Convenience over
/// [`ddl_with`] for callers that don't thread the manifest convention.
pub fn ddl(schema: &CheckedSchema, dialect: Dialect) -> String {
    ddl_with(schema, dialect, ForeignKeys::None)
}

/// Render the whole schema as a DDL script (statements separated by blank lines) under a
/// given `foreign_keys` convention. FK constraints are emitted inline in each `CREATE
/// TABLE`, resolved per relation (the convention ⊕ `@fk`/`@no_fk`).
pub fn ddl_with(schema: &CheckedSchema, dialect: Dialect, fks: ForeignKeys) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "-- Generated by `based gen sql` (dialect: {}). Do not edit by hand.\n",
        dialect.name()
    ));
    for model in &schema.models {
        out.push('\n');
        out.push_str(&create_table(schema, model, dialect, fks));
    }
    out
}

/// The set of index-like clauses a model carries, resolved to physical columns and
/// names. Shared by both dialects: MariaDB inlines them into the `CREATE TABLE`;
/// SQLite emits them as trailing `CREATE INDEX` statements.
struct IndexSpec {
    name: String,
    columns: Vec<String>,
    unique: bool,
    /// `using <method>` — an access method the target must have (checked in sema).
    method: Option<String>,
    /// An opaque `@index raw("…")` body: everything after `ON <table>`.
    raw: Option<String>,
}

/// Every declared `@index` on a model, resolved to physical columns + a stable
/// name. A non-unique index on a `@soft_delete` model is rendered predicate-leading:
/// the always-filtered tombstone column is physically prepended (neither MariaDB nor
/// SQLite has partial indexes), so the written index still leads with what selects. A
/// unique index is a constraint — its column set is never reshaped.
fn index_specs(schema: &CheckedSchema, model: &RModel, dialect: Dialect) -> Vec<IndexSpec> {
    model
        .indexes
        .iter()
        .map(|idx| {
            if let Some(spec) = &idx.raw {
                return IndexSpec {
                    name: raw_index_name(&model.table, spec),
                    columns: Vec::new(),
                    unique: false,
                    method: None,
                    raw: Some(
                        spec.for_dialect(dialect.name())
                            .unwrap_or_default()
                            .to_string(),
                    ),
                };
            }
            let mut columns = idx.columns.clone();
            if !idx.unique {
                if let Some(sd) = &model.soft_delete {
                    if columns.first() != Some(&sd.field) {
                        columns.insert(0, sd.field.clone());
                    }
                }
            }
            IndexSpec {
                name: constraint_name(
                    if idx.unique { "uq" } else { "idx" },
                    &model.table,
                    &columns,
                ),
                columns: columns
                    .iter()
                    .flat_map(|c| physical_cols(schema, model, c))
                    .collect(),
                unique: idx.unique,
                method: idx.method.clone(),
                raw: None,
            }
        })
        .collect()
}

/// The physical column(s) backing a field in an index: a scalar's column or a single-column
/// FK, else the ordered `<field>_<part>` columns of a composite FK (so `@index enrollment`
/// on a relation into a composite-key model covers the whole multi-column FK).
fn physical_cols(schema: &CheckedSchema, model: &RModel, field: &str) -> Vec<String> {
    match model.member(field) {
        Some(mem) if matches!(mem.kind, MemberKind::Forward { .. }) => {
            let fks = schema.fk_columns(mem);
            if fks.len() > 1 {
                return fks.into_iter().map(|(c, _)| c).collect();
            }
            vec![physical_col(model, field)]
        }
        _ => vec![physical_col(model, field)],
    }
}

/// A stable, order-independent name for an opaque index: `idx_<table>_raw_<hash>` over
/// the canonical `raw(…)` body, so reordering a model's indexes never looks like a
/// rename and two different bodies never collide in the snapshot.
pub(crate) fn raw_index_name(table: &str, spec: &RawSpec) -> String {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in spec.canonical().as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("idx_{table}_raw_{:08x}", h as u32)
}

/// Is this index one MariaDB expresses as a table clause? The opaque `raw` form is
/// always a standalone `CREATE INDEX` (its body is not a column list).
fn inline_on_mariadb(spec: &IndexSpec) -> bool {
    spec.raw.is_none()
}

/// One `CREATE TABLE` for a model: columns in declaration order, then the table
/// constraints (primary key, uniques, and — on MariaDB — the indexes inline). On
/// SQLite the indexes follow as separate `CREATE INDEX` statements (no inline form).
fn create_table(
    schema: &CheckedSchema,
    model: &RModel,
    dialect: Dialect,
    fks: ForeignKeys,
) -> String {
    let mut lines: Vec<String> = column_lines(schema, model, dialect);

    // Primary key — the PK member's physical column(s): the `id` field's, the column a
    // single-column `@key(field)` nominates, or the ordered columns of a composite
    // `@key(f1, f2, …)`. A `@no_id` (keyless legacy) table has none. SQLite spells a
    // `serial` PK inline on the column (`INTEGER PRIMARY KEY AUTOINCREMENT`), so it needs no
    // separate clause; every other case (and every other dialect's serial) gets the clause.
    let sqlite_serial = dialect == Dialect::Sqlite && model.pk_is_db_generated();
    let pk_cols = model.pk_columns();
    if !pk_cols.is_empty() && !sqlite_serial {
        let cols = pk_cols
            .iter()
            .map(|c| dialect.quote(c))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("PRIMARY KEY ({cols})"));
    }

    // MariaDB/MySQL require an `AUTO_INCREMENT` column be the first column of some key. When
    // a composite key's `serial` part is *not* the leading PK column, the composite PRIMARY
    // KEY doesn't satisfy that, so add a covering `KEY` on the serial column alone.
    if dialect.is_mysql_family() {
        if let Some(sc) = model.serial_key_column() {
            if pk_cols.first() != Some(&sc) {
                lines.push(format!("KEY ({})", dialect.quote(&sc)));
            }
        }
    }
    lines.extend(constraint_lines(schema, model, dialect, fks));

    let specs = index_specs(schema, model, dialect);

    // MySQL/MariaDB inline the indexes as `KEY` / `UNIQUE KEY` clauses; SQLite and Postgres
    // have no inline form, so they trail the table as `CREATE INDEX` statements.
    if dialect.is_mysql_family() {
        for spec in specs.iter().filter(|s| inline_on_mariadb(s)) {
            lines.push(inline_index_clause(dialect, spec));
        }
    }

    let body = lines
        .iter()
        .map(|l| format!("  {l}"))
        .collect::<Vec<_>>()
        .join(",\n");
    let schema = model.schema.as_deref();
    let mut out = format!(
        "CREATE TABLE {} (\n{body}\n);\n",
        dialect.quote_table(schema, &model.table)
    );

    for spec in specs
        .iter()
        .filter(|s| !dialect.is_mysql_family() || !inline_on_mariadb(s))
    {
        out.push_str(&create_index_stmt(dialect, schema, &model.table, spec));
    }
    out
}

/// The column definitions: scalars and forward-relation FKs. Inverse edges store nothing.
fn column_lines(schema: &CheckedSchema, model: &RModel, dialect: Dialect) -> Vec<String> {
    let serial_pk = model.pk_is_db_generated();
    let serial_key_part = model.serial_key_member().map(|m| m.name.clone());
    let mut lines = Vec::new();
    for mem in &model.members {
        match &mem.kind {
            // A `serial` primary key: the DB owns the value, so its column carries the
            // dialect's auto-increment/identity clause instead of a plain type.
            MemberKind::Scalar { column, .. } if serial_pk && mem.name == "id" => {
                lines.push(serial_pk_column(dialect, column));
            }
            // A composite `@key`'s `serial` part: DB-generated on Postgres/MariaDB — its
            // column carries the identity/auto-increment clause (no inline PRIMARY KEY; the
            // composite PK clause covers it). SQLite has no auto-increment for a non-sole-PK
            // column, so it falls through to a plain `INTEGER` (this pattern needs the raw
            // hatch on SQLite).
            MemberKind::Scalar { column, .. }
                if serial_key_part.as_deref() == Some(mem.name.as_str())
                    && matches!(
                        dialect,
                        Dialect::Postgres | Dialect::MariaDb | Dialect::MySql
                    ) =>
            {
                lines.push(serial_pk_column(dialect, column));
            }
            MemberKind::Scalar {
                ty,
                optional,
                many,
                column,
                default,
                enum_name,
                raw_type,
                unique: _,
                generated,
            } => {
                let en = enum_name.as_deref().and_then(|n| schema.enum_(n));
                // An opaque column's DB type is the literal the author wrote.
                let col_ty = match raw_type {
                    Some(spec) => spec
                        .for_dialect(dialect.name())
                        .unwrap_or_default()
                        .to_string(),
                    None => sql_type(*ty, *many, dialect),
                };
                // A generated column carries a `GENERATED ALWAYS AS (<expr>) STORED` clause
                // in place of a nullability/default; its value is derived, never stored by hand.
                if let Some(expr) = generated {
                    lines.push(format!(
                        "{} {col_ty} GENERATED ALWAYS AS ({}) STORED",
                        dialect.quote(column),
                        generated_expr(Some(schema), Some(model), expr, Emit::Sql(dialect)),
                    ));
                } else {
                    lines.push(column_line(
                        column,
                        &col_ty,
                        *optional,
                        default.as_ref(),
                        en,
                        dialect,
                    ));
                }
            }
            MemberKind::Forward { optional, .. } => {
                // FK column(s) mirror the target's primary key: one column for a
                // single-column-key target, one `<field>_<part>` column per key part for a
                // composite-key target. Each column's type is that key part's own type.
                for (col, part) in schema.fk_columns(mem) {
                    let ty = key_part_sql_type(schema, part, dialect);
                    lines.push(column_line(&col, &ty, *optional, None, None, dialect));
                }
            }
            MemberKind::Inverse { .. } => {}
        }
    }
    lines
}

/// The table-level constraint clauses, in emission order: column `(unique)` constraints,
/// enum CHECKs, then foreign keys.
fn constraint_lines(
    schema: &CheckedSchema,
    model: &RModel,
    dialect: Dialect,
    fks: ForeignKeys,
) -> Vec<String> {
    let mut lines = Vec::new();

    // Column-level `(unique)` constraints, in member order. All dialects accept the
    // inline `CONSTRAINT … UNIQUE (…)` table clause.
    for mem in &model.members {
        if let MemberKind::Scalar {
            column,
            unique: true,
            ..
        } = &mem.kind
        {
            lines.push(format!(
                "CONSTRAINT {name} UNIQUE ({col})",
                name = dialect.quote(&constraint_name(
                    "uq",
                    &model.table,
                    std::slice::from_ref(column)
                )),
                col = dialect.quote(column),
            ));
        }
    }

    // Enum columns carry a DB-native CHECK constraint (`col IN ('v1', …)`) — the
    // dialect-honest form on every target (SQLite has no native enum type; Postgres's
    // `CREATE TYPE` and MariaDB's inline `ENUM(…)` both make a variant change an awkward
    // `ALTER TYPE`/`MODIFY`, so a text column + CHECK is the uniform, migration-simple
    // representation). Membership is also enforced by the DSL layer.
    for mem in &model.members {
        if let MemberKind::Scalar {
            column,
            enum_name: Some(en_name),
            ..
        } = &mem.kind
        {
            if let Some(en) = schema.enum_(en_name) {
                let values: Vec<String> = en
                    .variants
                    .iter()
                    .map(|v| enum_value_sql(&v.value))
                    .collect();
                lines.push(enum_check_clause(dialect, &model.table, column, &values));
            }
        }
    }

    // Foreign-key constraints — opt-in (the `foreign_keys` convention ⊕ per-relation
    // `@fk`/`@no_fk`). An inline table constraint works on all three targets (SQLite too).
    for fk in crate::migrate::foreign_key_snaps(schema, model, fks) {
        lines.push(fk_constraint_clause(dialect, &model.table, &fk));
    }
    lines
}

/// A single column definition: `` `name` TYPE (NOT NULL|NULL) [DEFAULT x] ``. `en` is the
/// column's enum, when enum-typed, so a variant default renders as its wire value.
fn column_line(
    column: &str,
    ty: &str,
    optional: bool,
    default: Option<&DefaultVal>,
    en: Option<&based_sema::REnum>,
    dialect: Dialect,
) -> String {
    let mut s = format!(
        "{} {ty} {}",
        dialect.quote(column),
        if optional { "NULL" } else { "NOT NULL" }
    );
    if let Some(dv) = default {
        s.push_str(" DEFAULT ");
        s.push_str(&render_default(dv, en, dialect));
    }
    s
}

/// A declared/inferred index as an inline MariaDB table clause. A unique index
/// becomes `UNIQUE KEY`, otherwise `KEY`. The name keeps field-derived readability;
/// the column list is physical (a relation field is its FK column, resolved upstream).
fn inline_index_clause(dialect: Dialect, spec: &IndexSpec) -> String {
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    // MariaDB spells its two exotic access methods as index *kinds* (`FULLTEXT KEY`),
    // and its B-tree/hash choice as a trailing `USING`.
    let (kind, using) = match spec.method.as_deref() {
        Some("fulltext") => ("FULLTEXT KEY", String::new()),
        Some("spatial") => ("SPATIAL KEY", String::new()),
        Some(m) => (
            if spec.unique { "UNIQUE KEY" } else { "KEY" },
            format!(" USING {}", m.to_uppercase()),
        ),
        None => (
            if spec.unique { "UNIQUE KEY" } else { "KEY" },
            String::new(),
        ),
    };
    format!(
        "{kind} {name} ({cols}){using}",
        name = dialect.quote(&spec.name)
    )
}

/// A declared/inferred index as a standalone `CREATE INDEX` statement (SQLite and
/// Postgres have no inline table-index clause). A unique index becomes `CREATE UNIQUE
/// INDEX`.
fn create_index_stmt(
    dialect: Dialect,
    schema: Option<&str>,
    table: &str,
    spec: &IndexSpec,
) -> String {
    format!("{};\n", create_index_sql(dialect, schema, table, spec))
}

/// A standalone `CREATE [UNIQUE] INDEX`, bare (no trailing `;`). An opaque index's body
/// rides verbatim in place of the column list; `using <method>` renders as Postgres's
/// leading `USING <m>` (MariaDB spells methods inline — see `inline_index_clause`).
fn create_index_sql(
    dialect: Dialect,
    schema: Option<&str>,
    table: &str,
    spec: &IndexSpec,
) -> String {
    let kind = if spec.unique {
        "CREATE UNIQUE INDEX"
    } else {
        "CREATE INDEX"
    };
    let name = dialect.quote(&spec.name);
    let table_q = dialect.quote_table(schema, table);
    if let Some(raw) = &spec.raw {
        return format!("{kind} {name} ON {table_q} {raw}");
    }
    let cols = spec
        .columns
        .iter()
        .map(|c| dialect.quote(c))
        .collect::<Vec<_>>()
        .join(", ");
    match spec.method.as_deref() {
        Some(m) => format!("{kind} {name} ON {table_q} USING {m} ({cols})"),
        None => format!("{kind} {name} ON {table_q} ({cols})"),
    }
}

/// Physical column backing a field: a scalar's column, or a forward relation's FK.
/// Falls back to the field name (an inverse edge or unknown field — the latter sema
/// already rejected).
pub(crate) fn physical_col(model: &RModel, field: &str) -> String {
    match model.member(field).map(|m| &m.kind) {
        Some(MemberKind::Scalar { column, .. }) => column.clone(),
        Some(MemberKind::Forward { fk_col, .. }) => fk_col.clone(),
        _ => field.to_string(),
    }
}

/// Stable, readable constraint/index name: `<prefix>_<table>_<col1>_<col2>`.
pub(crate) fn constraint_name(prefix: &str, table: &str, columns: &[String]) -> String {
    let mut name = format!("{prefix}_{table}");
    for c in columns {
        name.push('_');
        name.push_str(c);
    }
    name
}

/// The table the DB-backed idempotency store keeps its keys in — created in the same
/// database the mutations write to, so a keyed retry deduplicates across every app
/// instance sharing that database.
pub const IDEMPOTENCY_TABLE: &str = "_based_idempotency";

/// `CREATE TABLE IF NOT EXISTS` for the DB-backed idempotency store, rendered per dialect
/// through the shared DDL type map (not hand-rolled per driver). The `(callable, key)`
/// primary key is the unique index that makes a concurrent retry's claim block on the
/// first, still-uncommitted attempt and then replay its result; `response` is NULL while a
/// claim is in flight and set — inside the mutation's own transaction — when the write
/// records its result, so key + writes + response commit atomically. `created_at` anchors a
/// future age-based reclaim.
pub fn idempotency_table_ddl(dialect: Dialect) -> String {
    let text = sql_type(Primitive::Text, false, dialect);
    let ts = sql_type(Primitive::Timestamp, false, dialect);
    format!(
        "CREATE TABLE IF NOT EXISTS {tbl} (\n  \
         {callable} {text} NOT NULL,\n  \
         {key} {text} NOT NULL,\n  \
         {fp} {text} NOT NULL,\n  \
         {response} {text},\n  \
         {created} {ts} NOT NULL,\n  \
         PRIMARY KEY ({callable}, {key})\n);",
        tbl = dialect.quote(IDEMPOTENCY_TABLE),
        callable = dialect.quote("callable"),
        key = dialect.quote("key"),
        fp = dialect.quote("fingerprint"),
        response = dialect.quote("response"),
        created = dialect.quote("created_at"),
    )
}

/// Render a `(default …)` value as a SQL literal / expression, per dialect. Only the
/// bool literal differs: MariaDB has `TRUE`/`FALSE` keywords; SQLite stores bools as
/// integers, so a bool default renders `1`/`0`.
fn render_default(dv: &DefaultVal, en: Option<&based_sema::REnum>, dialect: Dialect) -> String {
    match dv {
        DefaultVal::Lit(Literal::Str(s)) => format!("'{}'", s.replace('\'', "''")),
        DefaultVal::Lit(Literal::Int(i)) => i.to_string(),
        DefaultVal::Lit(Literal::Decimal(s)) => s.clone(),
        DefaultVal::Lit(Literal::Bool(b)) => dialect.bool_lit(*b).to_string(),
        DefaultVal::Lit(Literal::Null) => "NULL".to_string(),
        // `now()` is the only value-position function (ir::KNOWN_FUNCS).
        DefaultVal::Func(_) => "CURRENT_TIMESTAMP".to_string(),
        // An enum default (`default pending`) is its variant's wire value: a quoted
        // string for a string enum, a bare integer for an int enum.
        DefaultVal::Variant(v) => en.and_then(|e| e.wire_of(&v.node)).map_or_else(
            || format!("'{}'", v.node.replace('\'', "''")),
            enum_value_sql,
        ),
    }
}
