//! SQL DML generation (M3, read side): a `query` lowers to a parameterized SELECT.
//!
//! This is where the headline soft-delete guarantee (soft-delete.md) becomes real:
//! the tombstone predicate is injected into every generated SELECT — on the root
//! table (in `WHERE`) and on every joined table (in its `ON`, so a `LEFT JOIN`
//! stays a left join). `@scope` (auth.md) rides the same injection path. The user
//! never writes either; both are compiler primitives.
//!
//! ## What a query lowers to
//! - FROM the target model's table (aliased by its table name).
//! - Projection from the return **shape**: bare fields are local columns, `out =
//!   path` reaches across relations (each relation step becomes a JOIN), `out =
//!   sql`…`` is an inline expression. A bare-model return projects every stored
//!   column. (Nested shape sub-objects are deferred — see PLAN M3.)
//! - WHERE from the query filter (bare-param same-name equality, per-param
//!   bindings, or an explicit `where`), then the injected soft-delete + scope.
//! - ORDER from the sort cascade (query `order` > model `@sort`); keyset queries
//!   get the unique `id` tiebreaker appended, shown not written (pagination.md).
//! - LIMIT / OFFSET from `page (...)`; `with count` emits a second COUNT(*).
//!
//! ## Parameter placeholders
//! Signature inputs render as `:name` named placeholders (`$ctx.org` -> `:ctx_org`).
//! The generated client (M4) binds them; MariaDB's native positional `?` is a
//! client-layer translation. Named placeholders keep the emitted SQL legible —
//! readable over terse (CLAUDE.md).
//!
//! ## Deferred (documented, not silently wrong)
//! - Nested shape sub-objects (`field { ... }`): need JSON aggregation / a second
//!   query; skipped in projection for now.
//! - Named-filter calls inside `where`: filter bodies aren't resolved against the
//!   call site yet (sema resume #2), so a `FilterCall` renders as a visible
//!   `TRUE /* filter … deferred */` no-op rather than wrong SQL.
//! - Keyset cursor comparison + opaque cursor encoding: runtime concern; the base
//!   SELECT carries only ORDER + LIMIT + tiebreaker.

use std::collections::HashMap;

use based_ast::*;
use based_sema::{CheckedSchema, MemberKind, RModel, RQuery, SoftDelete, SoftMode};

use crate::Dialect;

/// Render every query in the schema as a parameterized SELECT (mutations join in a
/// later increment). Statements are separated by blank lines, in declaration order.
pub fn dml(schema: &CheckedSchema, decls: &[Decl], dialect: Dialect) -> String {
    let Dialect::MariaDb = dialect;
    let queries: HashMap<&str, &RQuery> = schema
        .queries
        .iter()
        .map(|q| (q.name.as_str(), q))
        .collect();

    let mut out = String::new();
    out.push_str("-- Generated by `based gen sql` (dialect: mariadb). Do not edit by hand.\n");
    out.push_str("-- Query templates: `:name` placeholders are bound by the generated client.\n");
    for decl in decls {
        if let Decl::Query(q) = decl {
            if let Some(rq) = queries.get(q.name.node.as_str()) {
                out.push('\n');
                out.push_str(&render_query(schema, decls, q, rq));
            }
        }
    }
    out
}

// ---------- per-query lowering --------------------------------------------

fn render_query(schema: &CheckedSchema, decls: &[Decl], q: &Query, rq: &RQuery) -> String {
    let root = schema.model(&rq.target).expect("target resolved by sema");
    let mut sel = Select::new(schema, root);

    // 1. Projection (drives the SELECT list; also seeds joins for reached columns).
    let projection = build_projection(&mut sel, decls, rq, root);

    // 2. Filter conditions: the query's own predicate first, then injected guards.
    let mut wheres: Vec<String> = Vec::new();
    collect_filter(&mut sel, q, root, &mut wheres);
    if let Some(sd) = &root.soft_delete {
        wheres.push(soft_pred(&sel.root_alias, root, sd));
    }
    if let Some(scope) = &root.scope {
        wheres.push(sel.predicate(scope, root));
    }

    // 3. Sort cascade + keyset tiebreaker.
    let order = build_order(&mut sel, q, root);

    // Assemble. Joins were accumulated by every resolve above, so emit them now.
    let mut sql = format!(
        "-- query {}\nSELECT\n{}\nFROM `{}`",
        q.name.node, projection, root.table
    );
    for j in &sel.joins {
        sql.push_str(&format!(
            "\n{} `{}` AS `{}` ON {}",
            j.kind, j.table, j.alias, j.on
        ));
    }
    if !wheres.is_empty() {
        sql.push_str(&format!("\nWHERE {}", wheres.join(" AND ")));
    }
    if !order.is_empty() {
        sql.push_str(&format!("\nORDER BY {}", order.join(", ")));
    }
    if let Some(page) = query_page(q) {
        sql.push_str(&format!("\nLIMIT {}", page.size));
        if page.offset {
            sql.push_str(" OFFSET :offset");
        }
    }
    sql.push_str(";\n");

    // `with count`: a second query for the live-row total (soft-delete applied, no
    // LIMIT). Meaningless for keyset, hence opt-in (pagination.md).
    if query_page(q).is_some_and(|p| p.with_count) {
        let mut cnt = format!(
            "-- query {} (count)\nSELECT COUNT(*) AS `count`\nFROM `{}`",
            q.name.node, root.table
        );
        for j in &sel.joins {
            cnt.push_str(&format!(
                "\n{} `{}` AS `{}` ON {}",
                j.kind, j.table, j.alias, j.on
            ));
        }
        if !wheres.is_empty() {
            cnt.push_str(&format!("\nWHERE {}", wheres.join(" AND ")));
        }
        cnt.push_str(";\n");
        sql.push('\n');
        sql.push_str(&cnt);
    }
    sql
}

// ---------- projection -----------------------------------------------------

/// Build the indented SELECT-list text. Uses the return shape when present, else
/// projects every stored column of a bare-model return.
fn build_projection(sel: &mut Select, decls: &[Decl], rq: &RQuery, root: &RModel) -> String {
    let mut cols: Vec<String> = Vec::new();
    match &rq.ret_shape {
        Some(name) => {
            if let Some(shape) = find_shape(decls, name, &rq.target) {
                project_body(sel, &shape.body, root, &mut cols);
            }
        }
        None => {
            // Bare-model return: every stored column, aliased to its field name.
            for mem in &root.members {
                match &mem.kind {
                    MemberKind::Scalar { column, .. } => {
                        cols.push(format!(
                            "`{}`.`{}` AS `{}`",
                            sel.root_alias, column, mem.name
                        ));
                    }
                    MemberKind::Forward { fk_col, .. } => {
                        cols.push(format!(
                            "`{}`.`{}` AS `{}`",
                            sel.root_alias, fk_col, mem.name
                        ));
                    }
                    MemberKind::Inverse { .. } => {}
                }
            }
        }
    }
    cols.iter()
        .map(|c| format!("  {c}"))
        .collect::<Vec<_>>()
        .join(",\n")
}

/// Project a shape body against `model`, appending `expr AS out` lines to `cols`.
fn project_body(sel: &mut Select, fields: &[ShapeField], model: &RModel, cols: &mut Vec<String>) {
    for f in fields {
        match f {
            ShapeField::Bare(id) => {
                let (alias, col) = sel.resolve(&single(&id.node), model);
                cols.push(format!("`{alias}`.`{col}` AS `{}`", id.node));
            }
            ShapeField::Rename { out, value } => match value {
                ShapeValue::Path(p) => {
                    let (alias, col) = sel.resolve(p, model);
                    cols.push(format!("`{alias}`.`{col}` AS `{}`", out.node));
                }
                ShapeValue::Raw(raw) => {
                    cols.push(format!(
                        "({}) AS `{}`",
                        render_raw(raw, &sel.root_alias, &model.table),
                        out.node
                    ));
                }
            },
            // Nested sub-objects need JSON aggregation / a second query — deferred
            // (PLAN M3). Skipped rather than emitting wrong SQL.
            ShapeField::Nest { .. } => {}
        }
    }
}

// ---------- filters (the query's own predicate) ---------------------------

/// Append the query's filter conditions. Bare/inline queries map each param to a
/// same-name equality (or its per-param binding); block/inline queries also carry
/// explicit `where` clauses referencing params via `$`.
fn collect_filter(sel: &mut Select, q: &Query, root: &RModel, out: &mut Vec<String>) {
    let is_block = matches!(q.body, QueryBody::Block(_));
    if !is_block {
        for p in &q.params {
            out.push(param_condition(sel, p, root));
        }
    }
    let clauses: &[Clause] = match &q.body {
        QueryBody::Inline(cs) => cs,
        QueryBody::Block(s) => &s.clauses,
        QueryBody::Bare => &[],
    };
    for c in clauses {
        if let Clause::Where(pred) = c {
            out.push(sel.predicate(pred, root));
        }
    }
}

/// One bare/inline param -> a filter condition (queries.md per-param bindings).
fn param_condition(sel: &mut Select, p: &Param, root: &RModel) -> String {
    let ph = format!(":{}", p.name.node);
    match &p.binding {
        // `user -> author`: equality on the named relation's FK column.
        Some(ParamBinding::Edge(edge)) => {
            let (alias, col) = sel.resolve(&single(&edge.node), root);
            format!("`{alias}`.`{col}` = {ph}")
        }
        // `since: timestamp > created_at`: explicit column + operator.
        Some(ParamBinding::ColOp { op, col }) => {
            let (alias, c) = sel.resolve(&single(&col.node), root);
            format!("`{alias}`.`{c}` {} {ph}", sql_op(*op))
        }
        // same-name equality on the mapped column (a relation field maps to its FK).
        None => {
            let (alias, col) = sel.resolve(&single(&p.name.node), root);
            format!("`{alias}`.`{col}` = {ph}")
        }
    }
}

// ---------- sort cascade ---------------------------------------------------

/// query `order (...)` > model `@sort` > none (sema already lints the empty case).
/// Keyset queries (paginated, not `offset`) append `id` as a unique tiebreaker.
fn build_order(sel: &mut Select, q: &Query, root: &RModel) -> Vec<String> {
    let query_order: Option<&[SortTerm]> = match &q.body {
        QueryBody::Inline(cs) => cs.iter().find_map(order_of),
        QueryBody::Block(s) => s.clauses.iter().find_map(order_of),
        QueryBody::Bare => None,
    };
    let terms: &[SortTerm] = query_order.unwrap_or(&root.sort);

    let mut out: Vec<String> = Vec::new();
    let mut last_is_id = false;
    for t in terms {
        let (alias, col) = sel.resolve(&t.path, root);
        last_is_id = alias == sel.root_alias && col == "id";
        out.push(format!("`{alias}`.`{col}` {}", dir(t.dir)));
    }
    if let Some(page) = query_page(q) {
        if !page.offset && !last_is_id && !out.is_empty() {
            out.push(format!("`{}`.`id` ASC", sel.root_alias));
        }
    }
    out
}

// ---------- the join-accumulating resolver --------------------------------

/// A pending JOIN. Deduped by `alias` (one per traversed path prefix), so a shape
/// and a `where` that both reach through `placed_by` share the single join.
pub(crate) struct Join {
    pub(crate) kind: &'static str, // "JOIN" | "LEFT JOIN"
    pub(crate) table: String,
    pub(crate) alias: String,
    pub(crate) on: String,
}

/// Accumulates joins as paths are resolved, so the final FROM/JOIN block reflects
/// every column any clause reached across. Shared by the read side (this module)
/// and the write side (`mutations`), which reuses `predicate`/`value` so a
/// mutation `where` lowers identically to a query `where`.
pub(crate) struct Select<'a> {
    schema: &'a CheckedSchema,
    pub(crate) root_alias: String,
    pub(crate) joins: Vec<Join>,
    /// path-prefix key (e.g. "placed_by", "address.city") -> join alias.
    seen: HashMap<String, String>,
}

impl<'a> Select<'a> {
    pub(crate) fn new(schema: &'a CheckedSchema, root: &RModel) -> Self {
        Select {
            schema,
            root_alias: root.table.clone(),
            joins: Vec::new(),
            seen: HashMap::new(),
        }
    }

    /// Resolve a dotted path from `root` to `(table_alias, column)`, materializing
    /// a JOIN for each relation step. A terminal relation resolves to its FK column
    /// (so `where (org = $org)` compares `org_id`), never a join.
    pub(crate) fn resolve(&mut self, path: &Path, root: &RModel) -> (String, String) {
        let mut cur = root;
        let mut alias = self.root_alias.clone();
        let mut prefix = String::new();
        let n = path.segments.len();
        for (i, seg) in path.segments.iter().enumerate() {
            let name = &seg.node;
            let mem = match cur.member(name) {
                Some(m) => m,
                None => return (alias, name.clone()), // sema already flagged this
            };
            let last = i + 1 == n;
            match &mem.kind {
                MemberKind::Scalar { column, .. } => return (alias, column.clone()),
                MemberKind::Forward {
                    target,
                    fk_col,
                    optional,
                    ..
                } => {
                    if last {
                        return (alias, fk_col.clone());
                    }
                    let (next_alias, next) =
                        self.join_forward(&alias, &mut prefix, name, target, fk_col, *optional);
                    alias = next_alias;
                    cur = next;
                }
                MemberKind::Inverse { target, via } => {
                    if last {
                        // Equality against a to-many edge has no local column; fall
                        // back to the key (unusual; kept resolvable).
                        return (alias, "id".to_string());
                    }
                    let (next_alias, next) =
                        self.join_inverse(&alias, &mut prefix, name, target, via);
                    alias = next_alias;
                    cur = next;
                }
            }
        }
        (alias, "id".to_string())
    }

    /// FK on this table -> JOIN target ON target.id = cur.fk. Optional -> LEFT JOIN.
    fn join_forward(
        &mut self,
        cur_alias: &str,
        prefix: &mut String,
        field: &str,
        target: &str,
        fk_col: &str,
        optional: bool,
    ) -> (String, &'a RModel) {
        push_prefix(prefix, field);
        let tmodel = self.schema.model(target).expect("relation target resolved");
        if let Some(a) = self.seen.get(prefix) {
            return (a.clone(), tmodel);
        }
        let alias = format!("j_{}", prefix.replace('.', "_"));
        let kind = if optional { "LEFT JOIN" } else { "JOIN" };
        let mut on = format!("`{alias}`.`id` = `{cur_alias}`.`{fk_col}`");
        if let Some(sd) = &tmodel.soft_delete {
            on.push_str(&format!(" AND {}", soft_pred(&alias, tmodel, sd)));
        }
        self.record(kind, tmodel.table.clone(), alias.clone(), on, prefix);
        (alias, tmodel)
    }

    /// FK on the target table -> LEFT JOIN target ON target.<via_fk> = cur.id.
    fn join_inverse(
        &mut self,
        cur_alias: &str,
        prefix: &mut String,
        field: &str,
        target: &str,
        via: &str,
    ) -> (String, &'a RModel) {
        push_prefix(prefix, field);
        let tmodel = self.schema.model(target).expect("relation target resolved");
        if let Some(a) = self.seen.get(prefix) {
            return (a.clone(), tmodel);
        }
        let alias = format!("j_{}", prefix.replace('.', "_"));
        // The forward field `via` on the target carries the FK column back to us.
        let via_fk = match tmodel.member(via).map(|m| &m.kind) {
            Some(MemberKind::Forward { fk_col, .. }) => fk_col.clone(),
            _ => format!("{via}_id"),
        };
        let mut on = format!("`{alias}`.`{via_fk}` = `{cur_alias}`.`id`");
        if let Some(sd) = &tmodel.soft_delete {
            on.push_str(&format!(" AND {}", soft_pred(&alias, tmodel, sd)));
        }
        self.record("LEFT JOIN", tmodel.table.clone(), alias.clone(), on, prefix);
        (alias, tmodel)
    }

    fn record(
        &mut self,
        kind: &'static str,
        table: String,
        alias: String,
        on: String,
        prefix: &str,
    ) {
        self.seen.insert(prefix.to_string(), alias.clone());
        self.joins.push(Join {
            kind,
            table,
            alias,
            on,
        });
    }

    // ---------- predicate lowering (where / @scope) -----------------------

    pub(crate) fn predicate(&mut self, p: &Predicate, model: &RModel) -> String {
        match p {
            Predicate::And(a, b) => {
                format!(
                    "({} AND {})",
                    self.predicate(a, model),
                    self.predicate(b, model)
                )
            }
            Predicate::Or(a, b) => {
                format!(
                    "({} OR {})",
                    self.predicate(a, model),
                    self.predicate(b, model)
                )
            }
            Predicate::Not(inner) => format!("NOT ({})", self.predicate(inner, model)),
            Predicate::Cmp { path, op, value } => {
                let (alias, col) = self.resolve(path, model);
                let lhs = format!("`{alias}`.`{col}`");
                let rhs = self.value(value, model);
                match op {
                    // Collection ops don't fit plain infix: `in` needs a value list,
                    // `has` is MariaDB's `value MEMBER OF(json_array)`.
                    Op::In => format!("{lhs} IN ({rhs})"),
                    Op::Has => format!("{rhs} MEMBER OF({lhs})"),
                    _ => format!("{lhs} {} {rhs}", sql_op(*op)),
                }
            }
            // A bare atom is a bool column here (a zero-arg filter ref is deferred).
            Predicate::Bare(path) => {
                let (alias, col) = self.resolve(path, model);
                format!("`{alias}`.`{col}` = TRUE")
            }
            // Filter bodies aren't resolved against the call site yet (sema #2).
            Predicate::FilterCall { name, .. } => {
                format!("TRUE /* filter {} deferred */", name.node)
            }
            Predicate::Raw(raw) => format!("({})", render_raw(raw, &self.root_alias, &model.table)),
        }
    }

    pub(crate) fn value(&mut self, v: &Value, model: &RModel) -> String {
        match v {
            Value::Param(pr) => format!(":{}", param_key(pr)),
            Value::Path(p) => {
                let (alias, col) = self.resolve(p, model);
                format!("`{alias}`.`{col}`")
            }
            Value::Lit(l) => render_lit(l),
            Value::Func(f) => render_func(f),
        }
    }
}

// ---------- small helpers --------------------------------------------------

/// Soft-delete predicate for a table alias (soft-delete.md covered subset).
pub(crate) fn soft_pred(alias: &str, model: &RModel, sd: &SoftDelete) -> String {
    let col = column_of(model, &sd.field);
    match sd.mode {
        SoftMode::Timestamp => format!("`{alias}`.`{col}` IS NULL"),
        SoftMode::Bool => format!("`{alias}`.`{col}` = FALSE"),
    }
}

/// Physical column backing a scalar field (its `(column …)` override or its name).
fn column_of(model: &RModel, field: &str) -> String {
    match model.member(field).map(|m| &m.kind) {
        Some(MemberKind::Scalar { column, .. }) => column.clone(),
        _ => field.to_string(),
    }
}

/// Physical column backing any field: a scalar's column, or a forward relation's FK
/// (`<field>_id`). Falls back to the field name (inverse edge / unknown — the latter
/// sema already rejected). Used by the write side to map `field = $x` assignments.
pub(crate) fn physical_col(model: &RModel, field: &str) -> String {
    match model.member(field).map(|m| &m.kind) {
        Some(MemberKind::Scalar { column, .. }) => column.clone(),
        Some(MemberKind::Forward { fk_col, .. }) => fk_col.clone(),
        _ => field.to_string(),
    }
}

/// A one-segment path, for the many call sites that resolve a single field name.
pub(crate) fn single(name: &str) -> Path {
    Path {
        segments: vec![Spanned {
            node: name.to_string(),
            span: NO_SPAN,
        }],
    }
}

const NO_SPAN: Span = Span {
    file: FileId(0),
    start: 0,
    end: 0,
};

fn push_prefix(prefix: &mut String, seg: &str) {
    if !prefix.is_empty() {
        prefix.push('.');
    }
    prefix.push_str(seg);
}

/// `$ctx.org` -> `ctx_org`; `$id` -> `id`. Placeholder-safe (dots removed).
pub(crate) fn param_key(pr: &ParamRef) -> String {
    let mut k = pr.name.node.clone();
    for seg in &pr.path {
        k.push('_');
        k.push_str(&seg.node);
    }
    k
}

fn order_of(c: &Clause) -> Option<&[SortTerm]> {
    match c {
        Clause::Order(terms) => Some(terms),
        _ => None,
    }
}

fn query_page(q: &Query) -> Option<&PageClause> {
    let clauses: &[Clause] = match &q.body {
        QueryBody::Inline(cs) => cs,
        QueryBody::Block(s) => &s.clauses,
        QueryBody::Bare => return None,
    };
    clauses.iter().find_map(|c| match c {
        Clause::Page(p) => Some(p),
        _ => None,
    })
}

/// Find the shape body for a return. `full` is per-model, so match on `from` too.
fn find_shape<'a>(decls: &'a [Decl], name: &str, model: &str) -> Option<&'a Shape> {
    decls.iter().find_map(|d| match d {
        Decl::Shape(s) if s.name.node == name && (name != "full" || s.from.node == model) => {
            Some(s)
        }
        _ => None,
    })
}

pub(crate) fn sql_op(op: Op) -> &'static str {
    match op {
        Op::Eq => "=",
        Op::Ne => "<>",
        Op::Gt => ">",
        Op::Lt => "<",
        Op::Ge => ">=",
        Op::Le => "<=",
        Op::Like => "LIKE",
        Op::In => "IN",
        Op::Has => "MEMBER OF", // JSON array containment (MariaDB `x MEMBER OF(json)`)
    }
}

fn dir(d: SortDir) -> &'static str {
    match d {
        SortDir::Asc => "ASC",
        SortDir::Desc => "DESC",
    }
}

pub(crate) fn render_lit(l: &Literal) -> String {
    match l {
        Literal::Str(s) => format!("'{}'", s.replace('\'', "''")),
        Literal::Int(i) => i.to_string(),
        Literal::Float(f) => f.to_string(),
        Literal::Bool(b) => if *b { "TRUE" } else { "FALSE" }.to_string(),
        Literal::Null => "NULL".to_string(),
    }
}

pub(crate) fn render_func(f: &FuncCall) -> String {
    // `now()` is the only value-position function (ir::KNOWN_FUNCS).
    match f.name.node.as_str() {
        "now" => "CURRENT_TIMESTAMP".to_string(),
        other => format!("{other}()"),
    }
}

/// Render a raw-SQL fragment (raw.md): text verbatim, `${param}` -> `:param`,
/// `{table}`/`{id}` -> safe engine interpolation (root table / its `id`).
pub(crate) fn render_raw(raw: &RawSql, root_alias: &str, table: &str) -> String {
    let mut s = String::new();
    for part in &raw.parts {
        match part {
            RawPart::Text(t) => s.push_str(t),
            RawPart::Param(pr) => s.push_str(&format!(":{}", param_key(pr))),
            RawPart::Engine(id) => match id.node.as_str() {
                "table" => s.push_str(&format!("`{table}`")),
                "id" => s.push_str(&format!("`{root_alias}`.`id`")),
                other => s.push_str(&format!("`{other}`")),
            },
        }
    }
    s
}
