//! SQL DML generation (M3, write side): a `mutation` body lowers to INSERT /
//! UPDATE / DELETE statements.
//!
//! The headline guarantee here mirrors the read side (soft-delete.md): a `delete`
//! on a `@soft_delete` model is **rewritten to the tombstone UPDATE — never a real
//! DELETE**. `restore` is its inverse. `hard delete` is the loud, explicit opt-out
//! that does emit a real `DELETE`. The soft-delete live predicate (and `@scope`,
//! auth.md) is injected into every UPDATE/DELETE `WHERE` so a write can't touch a
//! tombstoned — or out-of-scope — row. The user writes none of this.
//!
//! ## What each action lowers to
//! - `create M { f = $x }` -> `INSERT INTO m (...) VALUES (...)`. The app-generated
//!   `id` (D1: uuid, no SQL default) is bound as `:id` unless the model declares its
//!   own `id`; `@created`/`@updated` columns are set to `CURRENT_TIMESTAMP` (D2, no
//!   DB default).
//! - `update M where (p) { f = $x }` -> `UPDATE m SET ... WHERE p AND <live> [AND
//!   <scope>]`; `@updated` is bumped.
//! - `delete M where (p)` -> soft model: `UPDATE m SET <tombstone> WHERE p AND
//!   <live>`; plain model: `DELETE FROM m WHERE p`.
//! - `restore M where (p)` -> `UPDATE m SET <cleared tombstone> WHERE p` (targets the
//!   deleted rows, so no live predicate is injected).
//! - `hard delete M where (p)` -> real `DELETE FROM m WHERE p` (soft-delete opt-out;
//!   `@scope` still applies).
//! - `tx { ... }` -> the inner statements, run in one engine-owned transaction
//!   (principle 7; the engine, not this SQL, owns BEGIN/COMMIT). Sibling `create`s
//!   get distinct id binds (`:id_<step>`), and a `^.field` back-reference reads the
//!   immediately preceding create — `^.id` binds that create's generated id.
//!
//! ## Deferred (documented, not silently wrong)
//! - Returning the declared shape after a write (RETURNING vs. re-select) is a
//!   runtime concern (PLAN M3); no trailing SELECT is emitted.
//! - Multi-row WHERE that reaches across relations lowers to MariaDB's multi-table
//!   `UPDATE m JOIN ...` / `DELETE m FROM m JOIN ...`, reusing the read-side joiner.

use based_ast::*;
use based_sema::{CheckedSchema, RModel, SoftDelete, SoftMode};

use crate::sql::dml::{physical_col, render_raw, soft_pred, BackCtx, Join, Select};
use crate::Dialect;

/// A mutation lowered to its ordered write statements. The whole body already runs
/// under one engine-owned transaction (principle 7), so a `tx { ... }` block is
/// flattened here — its statements sit inline in execution order. The in-process
/// runtime (M6 write path) consumes this directly, exactly as it consumes
/// [`super::LoweredQuery`] for reads, so the executed SQL and its bind surface can
/// never drift from `based gen sql` (principle 4). `render_mutation` (the text
/// emitter) and the runtime both read this one lowering.
#[derive(Debug, Clone)]
pub struct LoweredMutation {
    pub name: String,
    pub stmts: Vec<LoweredWrite>,
}

/// One write statement of a mutation: header-free SQL plus the metadata the runtime
/// needs to bind and respond.
#[derive(Debug, Clone)]
pub struct LoweredWrite {
    /// The `-- create …` / `-- delete (soft): …` comment lines the text emitter
    /// frames the SQL with (a `tx` banner is prepended to the block's first write).
    /// The runtime ignores this.
    pub header: String,
    /// Header-free SQL, ending in `;\n`. `:name` placeholders — including the engine
    /// `:id` / `:id_<step>` for a create — are bound by the runtime.
    pub sql: String,
    /// The model this statement writes. A create's model identifies the row the
    /// mutation's declared return refers to (empty for a raw write, which has none).
    pub model: String,
    /// For a `create` whose `id` the engine generates (D1, no caller-set id), the
    /// bind name that id fills (`id`, or `id_<step>` inside a `tx`); else `None`.
    pub gen_id: Option<String>,
}

/// Render every mutation in the schema as its INSERT/UPDATE/DELETE statements, in
/// declaration order, separated by blank lines. Delegates the SQL to
/// [`lower_mutations`] and frames each write with its comment header.
pub fn mutations(schema: &CheckedSchema, decls: &[Decl], dialect: Dialect) -> String {
    let Dialect::MariaDb = dialect;
    let mut out = String::new();
    out.push_str("-- Generated by `based gen sql` (dialect: mariadb). Do not edit by hand.\n");
    out.push_str(
        "-- Mutation templates: `:name` placeholders are bound by the generated client.\n",
    );
    for lm in lower_mutations(schema, decls) {
        out.push('\n');
        out.push_str(&format!("-- mutation {}\n", lm.name));
        for w in &lm.stmts {
            out.push_str(&w.header);
            out.push_str(&w.sql);
        }
    }
    out
}

/// Lower every mutation in the schema to its structured write statements, in
/// declaration order. The in-process runtime consumes this directly.
pub fn lower_mutations(schema: &CheckedSchema, decls: &[Decl]) -> Vec<LoweredMutation> {
    let mut out = Vec::new();
    for decl in decls {
        if let Decl::Mutation(m) = decl {
            out.push(lower_mutation(schema, decls, m));
        }
    }
    out
}

fn lower_mutation<'a>(
    schema: &'a CheckedSchema,
    decls: &'a [Decl],
    m: &'a Mutation,
) -> LoweredMutation {
    let mut stmts = Vec::new();
    for stmt in &m.body {
        lower_write(schema, decls, stmt, "id", None, &mut stmts);
    }
    LoweredMutation {
        name: m.name.node.clone(),
        stmts,
    }
}

/// Lower one write statement, pushing its [`LoweredWrite`](s) onto `out`. `id_param`
/// is the bind name a `create`'s app-generated `id` is emitted under (`id` at top
/// level, `id_<step>` inside a `tx` so sibling creates stay distinct); `back` is the
/// preceding create a `^.field` reads from (mutations.md). A `tx` flattens: it
/// pushes its inner writes inline and prepends the tx banner to the first of them.
fn lower_write<'a>(
    schema: &'a CheckedSchema,
    decls: &'a [Decl],
    stmt: &'a WriteStmt,
    id_param: &str,
    back: Option<BackCtx<'a>>,
    out: &mut Vec<LoweredWrite>,
) {
    match stmt {
        WriteStmt::Create { model, assigns } => {
            if let Some(m) = schema.model(&model.node) {
                out.push(lower_create(schema, decls, m, assigns, id_param, back));
            }
        }
        WriteStmt::Update {
            model,
            where_,
            assigns,
        } => {
            if let Some(m) = schema.model(&model.node) {
                out.push(lower_update(schema, decls, m, where_, assigns, back));
            }
        }
        WriteStmt::Delete { model, where_ } => {
            if let Some(m) = schema.model(&model.node) {
                out.push(lower_delete(schema, decls, m, where_, false));
            }
        }
        WriteStmt::HardDelete { model, where_ } => {
            if let Some(m) = schema.model(&model.node) {
                out.push(lower_delete(schema, decls, m, where_, true));
            }
        }
        WriteStmt::Restore { model, where_ } => {
            if let Some(m) = schema.model(&model.node) {
                out.push(lower_restore(schema, decls, m, where_));
            }
        }
        WriteStmt::Tx(inner) => {
            let start = out.len();
            // `^` reads the immediately preceding create; number creates so their
            // generated ids get distinct binds and a back-reference can name one.
            let mut prev: Option<BackCtx<'a>> = back;
            let mut step = 0usize;
            for st in inner {
                let idp = match st {
                    WriteStmt::Create { .. } => format!("id_{step}"),
                    _ => "id".to_string(),
                };
                lower_write(schema, decls, st, &idp, prev.clone(), out);
                if let WriteStmt::Create { assigns, .. } = st {
                    prev = Some(BackCtx {
                        id_param: idp,
                        assigns,
                    });
                    step += 1;
                }
            }
            // The tx is one engine-owned transaction (principle 7): the runtime wraps
            // the whole body, so the flattened statements need no per-tx marker beyond
            // this banner on the first write (text surface only).
            if let Some(first) = out.get_mut(start) {
                first.header = format!(
                    "-- tx: one engine-owned transaction (principle 7); rolls back together\n{}",
                    first.header
                );
            }
        }
        // A raw write is an escape hatch (raw.md): text verbatim, `${param}` -> `:param`.
        // No model is attached, so `{table}`/`{id}` interpolation has no root to bind.
        WriteStmt::Raw(raw) => out.push(LoweredWrite {
            header: String::new(),
            sql: format!("{};\n", render_raw(raw, "", "")),
            model: String::new(),
            gen_id: None,
        }),
    }
}

// ---------- create ---------------------------------------------------------

fn lower_create<'a>(
    schema: &'a CheckedSchema,
    decls: &'a [Decl],
    model: &RModel,
    assigns: &'a [Assign],
    id_param: &str,
    back: Option<BackCtx<'a>>,
) -> LoweredWrite {
    let mut sel = Select::new(schema, decls, model).with_back(back);
    let mut cols: Vec<String> = Vec::new();
    let mut vals: Vec<String> = Vec::new();
    let mut assigned: Vec<String> = Vec::new();

    for a in assigns {
        let col = physical_col(model, &a.col.node);
        cols.push(format!("`{col}`"));
        vals.push(sel.value(&a.value, model));
        assigned.push(col);
    }

    // Implicit `id` is app-generated (D1: uuid, no SQL default) — bind it unless the
    // model declares its own `id` that the caller sets explicitly. Only then does the
    // engine generate the id at runtime, under this bind name.
    let gen_id = if !assigned.iter().any(|c| c == "id") {
        cols.insert(0, "`id`".to_string());
        vals.insert(0, format!(":{id_param}"));
        Some(id_param.to_string())
    } else {
        None
    };

    // `@created`/`@updated` are set on insert (D2), unless the caller already did.
    for col in timestamp_cols(model, &[model.created.as_deref(), model.updated.as_deref()]) {
        if !assigned.contains(&col) {
            cols.push(format!("`{col}`"));
            vals.push("CURRENT_TIMESTAMP".to_string());
        }
    }

    LoweredWrite {
        header: format!("-- create {}\n", model.name),
        sql: format!(
            "INSERT INTO `{}` ({})\nVALUES ({});\n",
            model.table,
            cols.join(", "),
            vals.join(", ")
        ),
        model: model.name.clone(),
        gen_id,
    }
}

// ---------- update ---------------------------------------------------------

fn lower_update<'a>(
    schema: &'a CheckedSchema,
    decls: &'a [Decl],
    model: &RModel,
    where_: &Predicate,
    assigns: &'a [Assign],
    back: Option<BackCtx<'a>>,
) -> LoweredWrite {
    let mut sel = Select::new(schema, decls, model).with_back(back);
    let mut sets: Vec<String> = Vec::new();
    let mut assigned: Vec<String> = Vec::new();

    for a in assigns {
        let col = physical_col(model, &a.col.node);
        let val = sel.value(&a.value, model);
        sets.push(format!("`{}`.`{col}` = {val}", sel.root_alias));
        assigned.push(col);
    }
    if let Some(bump) = updated_bump(&sel, model, &assigned) {
        sets.push(bump);
    }

    let mut wheres = vec![sel.predicate(where_, model)];
    inject_guards(&mut sel, model, &mut wheres, /* live = */ true);
    LoweredWrite {
        header: String::new(),
        sql: update_stmt(&sel, model, &sets, &wheres),
        model: model.name.clone(),
        gen_id: None,
    }
}

// ---------- delete / hard delete -------------------------------------------

fn lower_delete(
    schema: &CheckedSchema,
    decls: &[Decl],
    model: &RModel,
    where_: &Predicate,
    hard: bool,
) -> LoweredWrite {
    let mut sel = Select::new(schema, decls, model);

    // Soft model + plain `delete` -> tombstone UPDATE, never a real DELETE.
    if let (Some(sd), false) = (&model.soft_delete, hard) {
        let mut sets = vec![tombstone_set(
            &sel.root_alias,
            model,
            sd,
            /* deleting = */ true,
        )];
        if let Some(bump) = updated_bump(&sel, model, &[]) {
            sets.push(bump);
        }
        let mut wheres = vec![sel.predicate(where_, model)];
        inject_guards(&mut sel, model, &mut wheres, /* live = */ true);
        return LoweredWrite {
            header: "-- delete (soft): tombstone, never a real DELETE\n".to_string(),
            sql: update_stmt(&sel, model, &sets, &wheres),
            model: model.name.clone(),
            gen_id: None,
        };
    }

    // Plain model, or the loud `hard delete` opt-out -> real DELETE.
    let mut wheres = vec![sel.predicate(where_, model)];
    inject_guards(&mut sel, model, &mut wheres, /* live = */ false);
    let header = if hard {
        "-- hard delete: real DELETE (explicit soft-delete opt-out)\n".to_string()
    } else {
        String::new()
    };
    LoweredWrite {
        header,
        sql: delete_stmt(&sel, model, &wheres),
        model: model.name.clone(),
        gen_id: None,
    }
}

// ---------- restore --------------------------------------------------------

fn lower_restore(
    schema: &CheckedSchema,
    decls: &[Decl],
    model: &RModel,
    where_: &Predicate,
) -> LoweredWrite {
    let mut sel = Select::new(schema, decls, model);
    // sema (E-restore) guarantees a soft-delete model here; fall back defensively.
    let mut sets = match &model.soft_delete {
        Some(sd) => vec![tombstone_set(
            &sel.root_alias,
            model,
            sd,
            /* deleting = */ false,
        )],
        None => Vec::new(),
    };
    if let Some(bump) = updated_bump(&sel, model, &[]) {
        sets.push(bump);
    }
    // Restore targets the *deleted* rows, so the live predicate is NOT injected;
    // `@scope` still applies (you can only restore within your scope).
    let mut wheres = vec![sel.predicate(where_, model)];
    if let Some(scope) = &model.scope {
        wheres.push(sel.predicate(scope, model));
    }
    LoweredWrite {
        header: "-- restore: clear the tombstone\n".to_string(),
        sql: update_stmt(&sel, model, &sets, &wheres),
        model: model.name.clone(),
        gen_id: None,
    }
}

// ---------- statement assembly ---------------------------------------------

/// `UPDATE t [JOIN ...] SET ... WHERE ...`. Joins (from a relation-reaching `where`)
/// make it MariaDB's multi-table UPDATE; without them it is a plain single-table one.
fn update_stmt(sel: &Select, model: &RModel, sets: &[String], wheres: &[String]) -> String {
    let mut s = format!("UPDATE `{}`", model.table);
    push_joins(&mut s, &sel.joins);
    s.push_str(&format!("\nSET {}", sets.join(", ")));
    push_where(&mut s, wheres);
    s.push_str(";\n");
    s
}

/// `DELETE FROM t WHERE ...`, or the multi-table `DELETE t FROM t JOIN ...` form
/// when the `where` reaches across relations.
fn delete_stmt(sel: &Select, model: &RModel, wheres: &[String]) -> String {
    let mut s = String::new();
    if sel.joins.is_empty() {
        s.push_str(&format!("DELETE FROM `{}`", model.table));
    } else {
        s.push_str(&format!(
            "DELETE `{}` FROM `{}`",
            sel.root_alias, model.table
        ));
        push_joins(&mut s, &sel.joins);
    }
    push_where(&mut s, wheres);
    s.push_str(";\n");
    s
}

fn push_joins(s: &mut String, joins: &[Join]) {
    for j in joins {
        s.push_str(&format!(
            "\n{} `{}` AS `{}` ON {}",
            j.kind, j.table, j.alias, j.on
        ));
    }
}

fn push_where(s: &mut String, wheres: &[String]) {
    if !wheres.is_empty() {
        s.push_str(&format!("\nWHERE {}", wheres.join(" AND ")));
    }
}

// ---------- injected guards + engine columns -------------------------------

/// Append the soft-delete live predicate (when `live`) and `@scope` to a write's
/// `WHERE`, so a mutation can't touch a tombstoned or out-of-scope row.
fn inject_guards(sel: &mut Select, model: &RModel, wheres: &mut Vec<String>, live: bool) {
    if live {
        if let Some(sd) = &model.soft_delete {
            wheres.push(soft_pred(&sel.root_alias, model, sd));
        }
    }
    if let Some(scope) = &model.scope {
        wheres.push(sel.predicate(scope, model));
    }
}

/// `@updated` -> `t.updated_at = CURRENT_TIMESTAMP`, unless the caller set it.
fn updated_bump(sel: &Select, model: &RModel, assigned: &[String]) -> Option<String> {
    let field = model.updated.as_deref()?;
    let col = physical_col(model, field);
    if assigned.contains(&col) {
        return None;
    }
    Some(format!("`{}`.`{col}` = CURRENT_TIMESTAMP", sel.root_alias))
}

/// The `SET` fragment that writes (or clears) the tombstone for the covered subset
/// (soft-delete.md): timestamp `CURRENT_TIMESTAMP`/`NULL`, bool `TRUE`/`FALSE`.
fn tombstone_set(alias: &str, model: &RModel, sd: &SoftDelete, deleting: bool) -> String {
    let col = physical_col(model, &sd.field);
    let val = match (sd.mode, deleting) {
        (SoftMode::Timestamp, true) => "CURRENT_TIMESTAMP",
        (SoftMode::Timestamp, false) => "NULL",
        (SoftMode::Bool, true) => "TRUE",
        (SoftMode::Bool, false) => "FALSE",
    };
    format!("`{alias}`.`{col}` = {val}")
}

/// Resolve the distinct physical columns of the given engine timestamp fields
/// (`@created`/`@updated`), preserving order and dropping `None`s / duplicates.
fn timestamp_cols(model: &RModel, fields: &[Option<&str>]) -> Vec<String> {
    let mut cols: Vec<String> = Vec::new();
    for f in fields.iter().flatten() {
        let col = physical_col(model, f);
        if !cols.contains(&col) {
            cols.push(col);
        }
    }
    cols
}
