//! SQL DML generation (M3, write side): a `mutation` body lowers to INSERT /
//! UPDATE / DELETE statements.
//!
//! The headline guarantee here mirrors the read side (soft-delete.md): a `delete`
//! on a `@soft_delete` model is **rewritten to the tombstone UPDATE — never a real
//! DELETE**. `restore` is its inverse. `hard delete` is the loud, explicit opt-out
//! that does emit a real `DELETE`. The soft-delete live predicate (and `@scope`,
//! auth.md) is injected into every UPDATE/DELETE `WHERE` so a write can't touch a
//! tombstoned — or out-of-scope — row. The user writes none of this.
//!
//! ## What each action lowers to
//! - `create M { f = $x }` -> `INSERT INTO m (...) VALUES (...)`. The app-generated
//!   `id` (D1: uuid, no SQL default) is bound as `:id` unless the model declares its
//!   own `id`; `@created`/`@updated` columns are set to `CURRENT_TIMESTAMP` (D2, no
//!   DB default).
//! - `update M where (p) { f = $x }` -> `UPDATE m SET ... WHERE p AND <live> [AND
//!   <scope>]`; `@updated` is bumped.
//! - `delete M where (p)` -> soft model: `UPDATE m SET <tombstone> WHERE p AND
//!   <live>`; plain model: `DELETE FROM m WHERE p`.
//! - `restore M where (p)` -> `UPDATE m SET <cleared tombstone> WHERE p` (targets the
//!   deleted rows, so no live predicate is injected).
//! - `hard delete M where (p)` -> real `DELETE FROM m WHERE p` (soft-delete opt-out;
//!   `@scope` still applies).
//! - `tx { ... }` -> the inner statements, run in one engine-owned transaction
//!   (principle 7; the engine, not this SQL, owns BEGIN/COMMIT).
//!
//! ## Deferred (documented, not silently wrong)
//! - `^` tx back-references (`user = ^.id`): not in the lexer/AST yet (sema resume
//!   #6). A `tx` today is a flat, independent statement sequence.
//! - Returning the declared shape after a write (RETURNING vs. re-select) is a
//!   runtime concern (PLAN M3); no trailing SELECT is emitted.
//! - Multi-row WHERE that reaches across relations lowers to MariaDB's multi-table
//!   `UPDATE m JOIN ...` / `DELETE m FROM m JOIN ...`, reusing the read-side joiner.

use based_ast::*;
use based_sema::{CheckedSchema, RModel, SoftDelete, SoftMode};

use crate::sql::dml::{physical_col, render_raw, soft_pred, Join, Select};
use crate::Dialect;

/// Render every mutation in the schema as its INSERT/UPDATE/DELETE statements, in
/// declaration order, separated by blank lines.
pub fn mutations(schema: &CheckedSchema, decls: &[Decl], dialect: Dialect) -> String {
    let Dialect::MariaDb = dialect;
    let mut out = String::new();
    out.push_str("-- Generated by `based gen sql` (dialect: mariadb). Do not edit by hand.\n");
    out.push_str(
        "-- Mutation templates: `:name` placeholders are bound by the generated client.\n",
    );
    for decl in decls {
        if let Decl::Mutation(m) = decl {
            out.push('\n');
            out.push_str(&render_mutation(schema, m));
        }
    }
    out
}

fn render_mutation(schema: &CheckedSchema, m: &Mutation) -> String {
    let mut out = format!("-- mutation {}\n", m.name.node);
    for stmt in &m.body {
        out.push_str(&render_write(schema, stmt));
    }
    out
}

/// One write statement -> its SQL. `tx` recurses (a flat statement sequence; `^`
/// back-references are deferred, sema resume #6).
fn render_write(schema: &CheckedSchema, stmt: &WriteStmt) -> String {
    match stmt {
        WriteStmt::Create { model, assigns } => match schema.model(&model.node) {
            Some(m) => render_create(schema, m, assigns),
            None => String::new(),
        },
        WriteStmt::Update {
            model,
            where_,
            assigns,
        } => match schema.model(&model.node) {
            Some(m) => render_update(schema, m, where_, assigns),
            None => String::new(),
        },
        WriteStmt::Delete { model, where_ } => match schema.model(&model.node) {
            Some(m) => render_delete(schema, m, where_, false),
            None => String::new(),
        },
        WriteStmt::HardDelete { model, where_ } => match schema.model(&model.node) {
            Some(m) => render_delete(schema, m, where_, true),
            None => String::new(),
        },
        WriteStmt::Restore { model, where_ } => match schema.model(&model.node) {
            Some(m) => render_restore(schema, m, where_),
            None => String::new(),
        },
        WriteStmt::Tx(inner) => {
            let mut s = "-- tx: one engine-owned transaction (principle 7); rolls back together\n"
                .to_string();
            for st in inner {
                s.push_str(&render_write(schema, st));
            }
            s
        }
        // A raw write is an escape hatch (raw.md): text verbatim, `${param}` -> `:param`.
        // No model is attached, so `{table}`/`{id}` interpolation has no root to bind.
        WriteStmt::Raw(raw) => format!("{};\n", render_raw(raw, "", "")),
    }
}

// ---------- create ---------------------------------------------------------

fn render_create(schema: &CheckedSchema, model: &RModel, assigns: &[Assign]) -> String {
    let mut sel = Select::new(schema, model);
    let mut cols: Vec<String> = Vec::new();
    let mut vals: Vec<String> = Vec::new();
    let mut assigned: Vec<String> = Vec::new();

    for a in assigns {
        let col = physical_col(model, &a.col.node);
        cols.push(format!("`{col}`"));
        vals.push(sel.value(&a.value, model));
        assigned.push(col);
    }

    // Implicit `id` is app-generated (D1: uuid, no SQL default) — bind it unless the
    // model declares its own `id` that the caller sets explicitly.
    if !assigned.iter().any(|c| c == "id") {
        cols.insert(0, "`id`".to_string());
        vals.insert(0, ":id".to_string());
    }

    // `@created`/`@updated` are set on insert (D2), unless the caller already did.
    for col in timestamp_cols(model, &[model.created.as_deref(), model.updated.as_deref()]) {
        if !assigned.contains(&col) {
            cols.push(format!("`{col}`"));
            vals.push("CURRENT_TIMESTAMP".to_string());
        }
    }

    format!(
        "-- create {}\nINSERT INTO `{}` ({})\nVALUES ({});\n",
        model.name,
        model.table,
        cols.join(", "),
        vals.join(", ")
    )
}

// ---------- update ---------------------------------------------------------

fn render_update(
    schema: &CheckedSchema,
    model: &RModel,
    where_: &Predicate,
    assigns: &[Assign],
) -> String {
    let mut sel = Select::new(schema, model);
    let mut sets: Vec<String> = Vec::new();
    let mut assigned: Vec<String> = Vec::new();

    for a in assigns {
        let col = physical_col(model, &a.col.node);
        let val = sel.value(&a.value, model);
        sets.push(format!("`{}`.`{col}` = {val}", sel.root_alias));
        assigned.push(col);
    }
    if let Some(bump) = updated_bump(&sel, model, &assigned) {
        sets.push(bump);
    }

    let mut wheres = vec![sel.predicate(where_, model)];
    inject_guards(&mut sel, model, &mut wheres, /* live = */ true);
    update_stmt(&sel, model, &sets, &wheres, None)
}

// ---------- delete / hard delete -------------------------------------------

fn render_delete(schema: &CheckedSchema, model: &RModel, where_: &Predicate, hard: bool) -> String {
    let mut sel = Select::new(schema, model);

    // Soft model + plain `delete` -> tombstone UPDATE, never a real DELETE.
    if let (Some(sd), false) = (&model.soft_delete, hard) {
        let mut sets = vec![tombstone_set(
            &sel.root_alias,
            model,
            sd,
            /* deleting = */ true,
        )];
        if let Some(bump) = updated_bump(&sel, model, &[]) {
            sets.push(bump);
        }
        let mut wheres = vec![sel.predicate(where_, model)];
        inject_guards(&mut sel, model, &mut wheres, /* live = */ true);
        return update_stmt(
            &sel,
            model,
            &sets,
            &wheres,
            Some("-- delete (soft): tombstone, never a real DELETE\n"),
        );
    }

    // Plain model, or the loud `hard delete` opt-out -> real DELETE.
    let mut wheres = vec![sel.predicate(where_, model)];
    inject_guards(&mut sel, model, &mut wheres, /* live = */ false);
    let comment = hard.then_some("-- hard delete: real DELETE (explicit soft-delete opt-out)\n");
    delete_stmt(&sel, model, &wheres, comment)
}

// ---------- restore --------------------------------------------------------

fn render_restore(schema: &CheckedSchema, model: &RModel, where_: &Predicate) -> String {
    let mut sel = Select::new(schema, model);
    // sema (E-restore) guarantees a soft-delete model here; fall back defensively.
    let mut sets = match &model.soft_delete {
        Some(sd) => vec![tombstone_set(
            &sel.root_alias,
            model,
            sd,
            /* deleting = */ false,
        )],
        None => Vec::new(),
    };
    if let Some(bump) = updated_bump(&sel, model, &[]) {
        sets.push(bump);
    }
    // Restore targets the *deleted* rows, so the live predicate is NOT injected;
    // `@scope` still applies (you can only restore within your scope).
    let mut wheres = vec![sel.predicate(where_, model)];
    if let Some(scope) = &model.scope {
        wheres.push(sel.predicate(scope, model));
    }
    update_stmt(
        &sel,
        model,
        &sets,
        &wheres,
        Some("-- restore: clear the tombstone\n"),
    )
}

// ---------- statement assembly ---------------------------------------------

/// `UPDATE t [JOIN ...] SET ... WHERE ...`. Joins (from a relation-reaching `where`)
/// make it MariaDB's multi-table UPDATE; without them it is a plain single-table one.
fn update_stmt(
    sel: &Select,
    model: &RModel,
    sets: &[String],
    wheres: &[String],
    comment: Option<&str>,
) -> String {
    let mut s = String::new();
    if let Some(c) = comment {
        s.push_str(c);
    }
    s.push_str(&format!("UPDATE `{}`", model.table));
    push_joins(&mut s, &sel.joins);
    s.push_str(&format!("\nSET {}", sets.join(", ")));
    push_where(&mut s, wheres);
    s.push_str(";\n");
    s
}

/// `DELETE FROM t WHERE ...`, or the multi-table `DELETE t FROM t JOIN ...` form
/// when the `where` reaches across relations.
fn delete_stmt(sel: &Select, model: &RModel, wheres: &[String], comment: Option<&str>) -> String {
    let mut s = String::new();
    if let Some(c) = comment {
        s.push_str(c);
    }
    if sel.joins.is_empty() {
        s.push_str(&format!("DELETE FROM `{}`", model.table));
    } else {
        s.push_str(&format!(
            "DELETE `{}` FROM `{}`",
            sel.root_alias, model.table
        ));
        push_joins(&mut s, &sel.joins);
    }
    push_where(&mut s, wheres);
    s.push_str(";\n");
    s
}

fn push_joins(s: &mut String, joins: &[Join]) {
    for j in joins {
        s.push_str(&format!(
            "\n{} `{}` AS `{}` ON {}",
            j.kind, j.table, j.alias, j.on
        ));
    }
}

fn push_where(s: &mut String, wheres: &[String]) {
    if !wheres.is_empty() {
        s.push_str(&format!("\nWHERE {}", wheres.join(" AND ")));
    }
}

// ---------- injected guards + engine columns -------------------------------

/// Append the soft-delete live predicate (when `live`) and `@scope` to a write's
/// `WHERE`, so a mutation can't touch a tombstoned or out-of-scope row.
fn inject_guards(sel: &mut Select, model: &RModel, wheres: &mut Vec<String>, live: bool) {
    if live {
        if let Some(sd) = &model.soft_delete {
            wheres.push(soft_pred(&sel.root_alias, model, sd));
        }
    }
    if let Some(scope) = &model.scope {
        wheres.push(sel.predicate(scope, model));
    }
}

/// `@updated` -> `t.updated_at = CURRENT_TIMESTAMP`, unless the caller set it.
fn updated_bump(sel: &Select, model: &RModel, assigned: &[String]) -> Option<String> {
    let field = model.updated.as_deref()?;
    let col = physical_col(model, field);
    if assigned.contains(&col) {
        return None;
    }
    Some(format!("`{}`.`{col}` = CURRENT_TIMESTAMP", sel.root_alias))
}

/// The `SET` fragment that writes (or clears) the tombstone for the covered subset
/// (soft-delete.md): timestamp `CURRENT_TIMESTAMP`/`NULL`, bool `TRUE`/`FALSE`.
fn tombstone_set(alias: &str, model: &RModel, sd: &SoftDelete, deleting: bool) -> String {
    let col = physical_col(model, &sd.field);
    let val = match (sd.mode, deleting) {
        (SoftMode::Timestamp, true) => "CURRENT_TIMESTAMP",
        (SoftMode::Timestamp, false) => "NULL",
        (SoftMode::Bool, true) => "TRUE",
        (SoftMode::Bool, false) => "FALSE",
    };
    format!("`{alias}`.`{col}` = {val}")
}

/// Resolve the distinct physical columns of the given engine timestamp fields
/// (`@created`/`@updated`), preserving order and dropping `None`s / duplicates.
fn timestamp_cols(model: &RModel, fields: &[Option<&str>]) -> Vec<String> {
    let mut cols: Vec<String> = Vec::new();
    for f in fields.iter().flatten() {
        let col = physical_col(model, f);
        if !cols.contains(&col) {
            cols.push(col);
        }
    }
    cols
}
