//! Neutral migration step vocabulary (`up.mig`) and the diff engine.
//!
//! The [`Step`] / [`ScopeChange`] / [`ColumnChange`] types, the destructive-marker
//! policy ([`Step::destructive`]), and [`diff`] — which compares a prior [`Snapshot`] to
//! the current schema and emits the neutral step list. Dialect-neutral throughout; SQL
//! rendering is [`super::sql`], neutral `up.mig` text is [`super::up_mig`].

use super::model::{ColumnSnap, IndexSnap, Rename, ScopeDeclSnap, Snapshot, TableSnap};
use crate::Dialect;
use based_sema::CheckedSchema;
use std::collections::HashSet;

// ---------- neutral step vocabulary (`up.mig`) ----------------------------

/// One neutral migration step (migrations.md's `up.mig` vocabulary). Dialect-neutral:
/// E3 renders each to per-dialect DDL over the `Dialect` seam. A [`Step`] carrying
/// `destructive: true` (drops, type-narrowing, a new `not_null` without a default, a new
/// unique over existing data) is *marked* so apply (E4) can gate it on an acknowledgement
/// — this engine marks, never applies.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Step {
    /// Full `CREATE TABLE` — `0001_init` is entirely these.
    CreateTable(TableSnap),
    /// `drop table <name>` — DESTRUCTIVE.
    DropTable(String),
    /// `add column <table>.<col> …`.
    AddColumn { table: String, column: ColumnSnap },
    /// `drop column <table>.<col>` — DESTRUCTIVE.
    DropColumn { table: String, column: String },
    /// `alter column <table>.<col> …` — one or more changes.
    AlterColumn {
        table: String,
        column: String,
        changes: Vec<ColumnChange>,
        /// The resulting column state. Carried because MariaDB alters a column via a
        /// full `MODIFY COLUMN <full definition>` — it cannot express a piecemeal
        /// null/type change — so the renderer (E3) needs the whole target column, not
        /// just the deltas. Postgres/SQLite render from the `changes` alone.
        after: ColumnSnap,
    },
    /// `add index <name> (<cols>)`.
    AddIndex { table: String, index: IndexSnap },
    /// `drop index <name>`.
    DropIndex { table: String, name: String },
    /// `add unique <name> (<cols>)` — DESTRUCTIVE over existing data.
    AddUnique { table: String, index: IndexSnap },
    /// `drop unique <name>`.
    DropUnique { table: String, name: String },
    /// `rename table <old> -> <new>` — only ever emitted via a model `@was` (never
    /// auto-guessed, migrations.md). Safe: an in-place `ALTER TABLE … RENAME`.
    RenameTable { from: String, to: String },
    /// `rename column <table>.<old> -> <new>` — only ever emitted via a field `@was`.
    /// Safe: an in-place `ALTER TABLE … RENAME COLUMN`, so existing data survives.
    RenameColumn {
        table: String,
        from: String,
        to: String,
    },
    /// A `raw(<dialect>)` escape step (migrations.md): hand-authored SQL for one dialect,
    /// carried in `up.mig`, run verbatim only when the target matches. Never generated by
    /// the diff — the neutral vocabulary can't model a backfill / dialect-specific cast —
    /// so it is parsed from `up.mig` ([`super::parse_raw_steps`]) and layered onto the
    /// snapshot-derived steps. Not offline-verifiable (opaque SQL), so a raw-carrying
    /// migration is stamped `partial` by `verify`.
    Raw { dialect: Dialect, sql: String },
    /// A scope-contract change (auth.md Handle 2): a scope decl added/dropped/retyped, or a
    /// model joining/leaving a scope. A scope emits **no DDL** (it is an injected filter in
    /// generated code, not a DB object), so this renders as a neutral note and produces no
    /// SQL — it exists so the change lands in a reviewable migration and advances the
    /// snapshot, keeping the offline drift check honest.
    ScopeChange(ScopeChange),
}

/// The kinds of scope-contract change a diff surfaces (auth.md / DNF). None emit SQL.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ScopeChange {
    /// A new `scope Name (…)` decl.
    Add(ScopeDeclSnap),
    /// A `scope Name` decl removed.
    Drop(String),
    /// A surviving `scope Name` decl whose terms changed; carries the new state.
    Alter(ScopeDeclSnap),
    /// A surviving table's `@scope` alternative set changed (joined/left/re-shaped a scope).
    Table {
        table: String,
        alts: Vec<Vec<String>>,
    },
}

/// One field-level change inside an [`Step::AlterColumn`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ColumnChange {
    /// `type <new>` — DESTRUCTIVE when narrowing (see [`is_narrowing`]).
    Type { from: String, to: String },
    /// `null` — always safe (relaxing a constraint).
    SetNull,
    /// `not_null` — DESTRUCTIVE without a default (existing NULLs violate it).
    SetNotNull { has_default: bool },
    /// `default=<lit>` — safe.
    SetDefault(String),
    /// `drop default` — safe.
    DropDefault,
}

impl Step {
    /// Does this step risk losing or rejecting data (migrations.md's destructive
    /// policy)? Apply (E4) gates a destructive step on `--allow-destructive` /
    /// `unsafe("reason")`; this engine only reports the marker.
    pub fn destructive(&self) -> bool {
        match self {
            Step::DropTable(_) | Step::DropColumn { .. } | Step::AddUnique { .. } => true,
            Step::AlterColumn { changes, .. } => changes.iter().any(|c| match c {
                ColumnChange::Type { from, to } => is_narrowing(from, to),
                ColumnChange::SetNotNull { has_default } => !has_default,
                _ => false,
            }),
            _ => false,
        }
    }
}

/// Is a type change `from -> to` narrowing (potentially truncating/failing)? Widening
/// is safe (`int -> text`); a same-family no-op is not a change at all. Anything that is
/// not a recognized safe widening is treated as narrowing (conservative — principle 1).
fn is_narrowing(from: &str, to: &str) -> bool {
    if from == to {
        return false;
    }
    // The only unambiguously safe widenings: any scalar -> text (text holds any value),
    // and int -> its wider selves (we have one `int`, so this is really the text case).
    !matches!(to, "text")
}

// ---------- diff ----------------------------------------------------------

/// Diff a *prior* snapshot against the *current* schema, producing the neutral `up.mig`
/// step list. An empty prior snapshot (`0001_init`) yields a full create set — exactly
/// what `based gen sql` builds from scratch. Renames are never auto-guessed: a changed
/// name is a drop + add pair (the `@was`-driven rename is E5).
pub fn diff(prev: &Snapshot, schema: &CheckedSchema) -> Vec<Step> {
    diff_snapshots(prev, &Snapshot::from_schema(schema))
}

/// Diff two neutral snapshots (the pure core — used by [`diff`] and by verify/drift). The
/// step order is: drops last within a table isn't required, but table creates/drops are
/// grouped and columns/indexes are emitted in a stable name order so the `up.mig` is
/// deterministic and reviewable.
pub fn diff_snapshots(prev: &Snapshot, now: &Snapshot) -> Vec<Step> {
    let mut steps = Vec::new();

    // Table renames first (a valid `@was`: old present in `prev`, new present in `now`,
    // new absent from `prev`). A renamed table then diffs its columns as a survivor, so a
    // migration can rename *and* alter in one step. `renamed_from`/`_to` mark the prev/now
    // table consumed by a rename so it is not also reported as a drop/create.
    let mut renamed_from: HashSet<&str> = HashSet::new();
    let mut renamed_to: HashSet<&str> = HashSet::new();
    for r in &now.renames {
        if let Rename::Table { from, to } = r {
            if is_valid_table_rename(prev, now, from, to) {
                steps.push(Step::RenameTable {
                    from: from.clone(),
                    to: to.clone(),
                });
                renamed_from.insert(from.as_str());
                renamed_to.insert(to.as_str());
            }
        }
    }

    // Tables added (present now, absent before, not a rename target) → full CREATE.
    for t in &now.tables {
        if prev.table(&t.name).is_none() && !renamed_to.contains(t.name.as_str()) {
            steps.push(Step::CreateTable(t.clone()));
        }
    }

    // Tables surviving → column + index deltas. A survivor is a same-name pair or a
    // rename pair (prev's old table vs now's new table).
    for now_t in &now.tables {
        let prev_t = if renamed_to.contains(now_t.name.as_str()) {
            rename_source(&now.renames, &now_t.name).and_then(|from| prev.table(from))
        } else {
            prev.table(&now_t.name)
        };
        if let Some(prev_t) = prev_t {
            diff_table(prev_t, now_t, &now.renames, &mut steps);
        }
    }

    // Tables dropped (present before, absent now, not a rename source) → DROP.
    for t in &prev.tables {
        if now.table(&t.name).is_none() && !renamed_from.contains(t.name.as_str()) {
            steps.push(Step::DropTable(t.name.clone()));
        }
    }

    diff_scopes(prev, now, &mut steps);

    steps
}

/// A table `@was` is a real rename iff the old name is a table in `prev`, the new name is
/// a table in `now`, and the new name is *not* already in `prev` (else it's a spent/inert
/// `@was`, ignored — the diff finds no matching old name, migrations.md).
fn is_valid_table_rename(prev: &Snapshot, now: &Snapshot, from: &str, to: &str) -> bool {
    prev.table(from).is_some() && prev.table(to).is_none() && now.table(to).is_some()
}

/// The old table name a valid rename maps to `to`, if any.
fn rename_source<'a>(renames: &'a [Rename], to: &str) -> Option<&'a str> {
    renames.iter().find_map(|r| match r {
        Rename::Table { from, to: t } if t == to => Some(from.as_str()),
        _ => None,
    })
}

/// Diff the scope contract (top-level decls + membership on surviving tables). Emits
/// no-DDL [`Step::ScopeChange`] steps so a scope-only change still produces a reviewable
/// migration. Skipped for a from-scratch `0001_init` (empty prior): the initial scopes ride
/// in `schema.snap` and each table's `scope_alts` rides its `CreateTable`, so init stays
/// create-only (its `up.mig` matches `based gen sql` from scratch, which emits no scope SQL).
fn diff_scopes(prev: &Snapshot, now: &Snapshot, steps: &mut Vec<Step>) {
    if prev.tables.is_empty() && prev.scopes.is_empty() {
        return;
    }
    // Scope decls added / retyped (present now).
    for s in &now.scopes {
        match prev.scope(&s.name) {
            None => steps.push(Step::ScopeChange(ScopeChange::Add(s.clone()))),
            Some(old) if old != s => steps.push(Step::ScopeChange(ScopeChange::Alter(s.clone()))),
            Some(_) => {}
        }
    }
    // Scope decls dropped (present before, absent now).
    for s in &prev.scopes {
        if now.scope(&s.name).is_none() {
            steps.push(Step::ScopeChange(ScopeChange::Drop(s.name.clone())));
        }
    }
    // Surviving tables whose `@scope` membership changed (joined/left/re-shaped).
    for now_t in &now.tables {
        if let Some(prev_t) = prev.table(&now_t.name) {
            if prev_t.scope_alts != now_t.scope_alts {
                steps.push(Step::ScopeChange(ScopeChange::Table {
                    table: now_t.name.clone(),
                    alts: now_t.scope_alts.clone(),
                }));
            }
        }
    }
}

fn diff_table(prev: &TableSnap, now: &TableSnap, renames: &[Rename], steps: &mut Vec<Step>) {
    // Column renames first (a valid field `@was`: old present in `prev`, new present in
    // `now`, new absent from `prev`). A renamed column can also change attributes in the
    // same migration, so its old-vs-new is diffed into a trailing `alter column`.
    let mut renamed_from: HashSet<&str> = HashSet::new();
    let mut renamed_to: HashSet<&str> = HashSet::new();
    for r in renames {
        if let Rename::Column { table, from, to } = r {
            if table == &now.name
                && prev.column(from).is_some()
                && prev.column(to).is_none()
                && now.column(to).is_some()
            {
                steps.push(Step::RenameColumn {
                    table: now.name.clone(),
                    from: from.clone(),
                    to: to.clone(),
                });
                renamed_from.insert(from.as_str());
                renamed_to.insert(to.as_str());
                if let (Some(old), Some(new)) = (prev.column(from), now.column(to)) {
                    let changes = column_changes(old, new);
                    if !changes.is_empty() {
                        steps.push(Step::AlterColumn {
                            table: now.name.clone(),
                            column: to.clone(),
                            changes,
                            after: new.clone(),
                        });
                    }
                }
            }
        }
    }
    // Columns added (absent in prev, not a rename target).
    for c in &now.columns {
        if prev.column(&c.name).is_none() && !renamed_to.contains(c.name.as_str()) {
            steps.push(Step::AddColumn {
                table: now.name.clone(),
                column: c.clone(),
            });
        }
    }
    // Columns altered (present in both by the same name — rename targets handled above).
    for c in &now.columns {
        if renamed_to.contains(c.name.as_str()) {
            continue;
        }
        if let Some(old) = prev.column(&c.name) {
            let changes = column_changes(old, c);
            if !changes.is_empty() {
                steps.push(Step::AlterColumn {
                    table: now.name.clone(),
                    column: c.name.clone(),
                    changes,
                    after: c.clone(),
                });
            }
        }
    }
    // Columns dropped (absent in now, not a rename source).
    for c in &prev.columns {
        if now.column(&c.name).is_none() && !renamed_from.contains(c.name.as_str()) {
            steps.push(Step::DropColumn {
                table: now.name.clone(),
                column: c.name.clone(),
            });
        }
    }

    // Indexes added. A unique index is its own `add unique` step (destructive over
    // existing data); a plain index is `add index` (safe).
    for i in &now.indexes {
        if prev.index(&i.name).map(|p| p == i) != Some(true) && prev.index(&i.name).is_none() {
            if i.unique {
                steps.push(Step::AddUnique {
                    table: now.name.clone(),
                    index: i.clone(),
                });
            } else {
                steps.push(Step::AddIndex {
                    table: now.name.clone(),
                    index: i.clone(),
                });
            }
        }
    }
    // Indexes changed (same name, different columns/unique) → drop + re-add. Renaming
    // an index isn't auto-guessed either; a definition change is a drop then an add.
    for i in &now.indexes {
        if let Some(old) = prev.index(&i.name) {
            if old != i {
                drop_index_step(old, now, steps);
                if i.unique {
                    steps.push(Step::AddUnique {
                        table: now.name.clone(),
                        index: i.clone(),
                    });
                } else {
                    steps.push(Step::AddIndex {
                        table: now.name.clone(),
                        index: i.clone(),
                    });
                }
            }
        }
    }
    // Indexes dropped.
    for i in &prev.indexes {
        if now.index(&i.name).is_none() {
            drop_index_step(i, now, steps);
        }
    }
}

fn drop_index_step(idx: &IndexSnap, table: &TableSnap, steps: &mut Vec<Step>) {
    if idx.unique {
        steps.push(Step::DropUnique {
            table: table.name.clone(),
            name: idx.name.clone(),
        });
    } else {
        steps.push(Step::DropIndex {
            table: table.name.clone(),
            name: idx.name.clone(),
        });
    }
}

/// The field-level changes turning column `old` into `now`. Empty when identical.
fn column_changes(old: &ColumnSnap, now: &ColumnSnap) -> Vec<ColumnChange> {
    let mut changes = Vec::new();
    if old.ty != now.ty {
        changes.push(ColumnChange::Type {
            from: old.ty.clone(),
            to: now.ty.clone(),
        });
    }
    if old.nullable != now.nullable {
        if now.nullable {
            changes.push(ColumnChange::SetNull);
        } else {
            changes.push(ColumnChange::SetNotNull {
                has_default: now.default.is_some(),
            });
        }
    }
    if old.default != now.default {
        match &now.default {
            Some(d) => changes.push(ColumnChange::SetDefault(d.clone())),
            None => changes.push(ColumnChange::DropDefault),
        }
    }
    changes
}

// ---------- step presentation (drift diagnostic) --------------------------

impl Step {
    /// The table this step affects, if any — the anchor a drift diagnostic points at.
    /// `None` for a scope-contract change or a raw escape (no single owning table).
    pub fn table_name(&self) -> Option<&str> {
        match self {
            Step::CreateTable(t) => Some(&t.name),
            Step::DropTable(n) => Some(n),
            Step::AddColumn { table, .. }
            | Step::DropColumn { table, .. }
            | Step::AlterColumn { table, .. }
            | Step::AddIndex { table, .. }
            | Step::DropIndex { table, .. }
            | Step::AddUnique { table, .. }
            | Step::DropUnique { table, .. }
            | Step::RenameColumn { table, .. } => Some(table),
            Step::RenameTable { from, .. } => Some(from),
            Step::ScopeChange(_) | Step::Raw { .. } => None,
        }
    }

    /// A one-line human description of this step, for the offline drift diagnostic
    /// ("uncaptured schema change: …"). Names the change in the schema's vocabulary.
    pub fn describe(&self) -> String {
        match self {
            Step::CreateTable(t) => format!("new table `{}`", t.name),
            Step::DropTable(n) => format!("dropped table `{n}`"),
            Step::AddColumn { table, column } => format!("added column `{table}.{}`", column.name),
            Step::DropColumn { table, column } => format!("dropped column `{table}.{column}`"),
            Step::AlterColumn { table, column, .. } => format!("altered column `{table}.{column}`"),
            Step::AddIndex { index, .. } | Step::AddUnique { index, .. } => {
                format!("added index `{}`", index.name)
            }
            Step::DropIndex { name, .. } | Step::DropUnique { name, .. } => {
                format!("dropped index `{name}`")
            }
            Step::RenameTable { from, to } => format!("renamed table `{from}` → `{to}`"),
            Step::RenameColumn { table, from, to } => {
                format!("renamed column `{table}.{from}` → `{to}`")
            }
            Step::ScopeChange(_) => "scope contract change".to_string(),
            Step::Raw { dialect, .. } => format!("raw({}) step", dialect.name()),
        }
    }
}

// ---------- offline drift check (LSP + CLI) -------------------------------

/// Diff the last captured snapshot against the current schema for the **offline drift
/// diagnostic** (migrations.md): the steps a `based migrate gen` *would* capture. Empty =
/// the migrations are up to date. Renames ride the schema's `@was`, so a real rename
/// reads as one `rename` step, not a drop+add. This is the pure engine; the LSP anchors
/// each step at its owning declaration and the CLI (`verify`) gates on non-emptiness.
pub fn drift(prev: &Snapshot, schema: &CheckedSchema) -> Vec<Step> {
    diff(prev, schema)
}

// ---------- raw(dialect) escape step (parsed from up.mig) ------------------

/// Parse the `raw(<dialect>) `<sql>`` escape steps out of an `up.mig` (migrations.md).
/// The diff never *generates* these (opaque SQL the neutral vocabulary can't model), so
/// `apply`/`render` recover them from the authored `up.mig` and layer them onto the
/// snapshot-derived structural steps. One step per matching line; a line whose dialect
/// token isn't a known dialect is skipped (parse is lenient — `verify` flags the file).
pub fn parse_raw_steps(up_text: &str) -> Vec<Step> {
    let mut out = Vec::new();
    for line in up_text.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("raw(") else {
            continue;
        };
        let Some(close) = rest.find(')') else {
            continue;
        };
        let dialect_tok = rest[..close].trim();
        // The SQL is delimited by the first and last backtick on the line, so an inner
        // backtick (a MariaDB identifier quote) rides through unharmed.
        let after = &rest[close + 1..];
        let Some(open_q) = after.find('`') else {
            continue;
        };
        let Some(close_q) = after.rfind('`') else {
            continue;
        };
        if close_q <= open_q {
            continue;
        }
        let sql = after[open_q + 1..close_q].trim().to_string();
        if sql.is_empty() {
            continue;
        }
        // Only the three known dialects are raw targets; an unknown token is left out so
        // it can't masquerade as (say) MariaDB via `Dialect::parse`'s permissive fallback.
        let dialect = match dialect_tok {
            "sqlite" => Dialect::Sqlite,
            "mariadb" | "mysql" => Dialect::MariaDb,
            "postgres" | "postgresql" => Dialect::Postgres,
            _ => continue,
        };
        out.push(Step::Raw { dialect, sql });
    }
    out
}

/// Does an `up.mig` carry any `raw(...)` escape step? A raw-carrying migration is
/// "not offline-verifiable" — `verify` reports it `partial` (migrations.md).
pub fn has_raw_step(up_text: &str) -> bool {
    up_text.lines().any(|l| l.trim_start().starts_with("raw("))
}

/// An `up.mig` with its `raw(...)` lines removed — the structural residue `verify`
/// compares against the snapshot-derived (raw-free) regeneration.
pub fn strip_raw_steps(up_text: &str) -> String {
    up_text
        .lines()
        .filter(|l| !l.trim_start().starts_with("raw("))
        .collect::<Vec<_>>()
        .join("\n")
}
