//! Render a neutral [`Step`] list to the canonical `up.mig` text (dialect-neutral).
//!
//! The reviewable migration file: one line (or a few) per step in the neutral
//! step vocabulary, destructive steps flagged with a trailing `# DESTRUCTIVE`. Per-dialect
//! SQL is [`super::sql`]; the step vocabulary is [`super::diff`].

use super::diff::{ColumnChange, ScopeChange, Step};
use super::model::{render_scope_decl, ColumnSnap, TableSnap};
use std::fmt::Write as _;

// ---------- `up.mig` rendering --------------------------------------------

/// Render a neutral step list to the canonical `up.mig` text. Deterministic; each step
/// is one (or a few) line(s) in the neutral step vocabulary. A destructive step carries a
/// trailing `# DESTRUCTIVE` marker so a reviewer sees the gate before applying.
pub fn render_up(steps: &[Step]) -> String {
    let mut out = String::new();
    out.push_str("# up.mig — generated by `based migrate gen`; edit if needed, then apply.\n");
    for s in steps {
        render_step(&mut out, s);
    }
    out
}

fn render_step(out: &mut String, step: &Step) {
    let destructive = step.destructive();
    match step {
        Step::CreateTable(t) => render_create_table(out, t),
        Step::DropTable(name) => {
            let _ = writeln!(out, "drop table {name}  # DESTRUCTIVE");
        }
        Step::AddColumn { table, column } => {
            let _ = writeln!(out, "add column {table}.{}", column_spec(column));
        }
        Step::DropColumn { table, column } => {
            let _ = writeln!(out, "drop column {table}.{column}  # DESTRUCTIVE");
        }
        Step::AlterColumn {
            table,
            column,
            changes,
            ..
        } => {
            let parts = changes
                .iter()
                .map(render_change)
                .collect::<Vec<_>>()
                .join(" ");
            let tail = if destructive { "  # DESTRUCTIVE" } else { "" };
            let _ = writeln!(out, "alter column {table}.{column} {parts}{tail}");
        }
        Step::AddIndex { index, .. } => {
            let _ = writeln!(
                out,
                "add index {} ({})",
                index.name,
                index.columns.join(", ")
            );
        }
        Step::DropIndex { name, .. } => {
            let _ = writeln!(out, "drop index {name}");
        }
        Step::AddUnique { index, .. } => {
            let _ = writeln!(
                out,
                "add unique {} ({})  # DESTRUCTIVE",
                index.name,
                index.columns.join(", ")
            );
        }
        Step::DropUnique { name, .. } => {
            let _ = writeln!(out, "drop unique {name}");
        }
        Step::RenameTable { from, to } => {
            let _ = writeln!(out, "rename table {from} -> {to}");
        }
        Step::RenameColumn { table, from, to } => {
            let _ = writeln!(out, "rename column {table}.{from} -> {to}");
        }
        Step::Raw { dialect, sql } => {
            let _ = writeln!(out, "raw({}) `{sql}`", dialect.name());
        }
        Step::ScopeChange(sc) => {
            let _ = writeln!(out, "{}  # code-level; no DDL", scope_change_line(sc));
        }
    }
}

/// The neutral `up.mig` line for a scope-contract change (no SQL is emitted for it).
pub(crate) fn scope_change_line(sc: &ScopeChange) -> String {
    match sc {
        ScopeChange::Add(s) => render_scope_decl(s),
        ScopeChange::Alter(s) => format!("alter {}", render_scope_decl(s)),
        ScopeChange::Drop(name) => format!("drop scope {name}"),
        ScopeChange::Table { table, alts } => {
            let rhs = if alts.is_empty() {
                "unscoped".to_string()
            } else {
                alts.iter()
                    .map(|a| format!("({})", a.join(", ")))
                    .collect::<Vec<_>>()
                    .join(" ")
            };
            format!("scope table {table} = {rhs}")
        }
    }
}

fn render_create_table(out: &mut String, t: &TableSnap) {
    let _ = writeln!(out, "create table {} {{", t.name);
    for c in &t.columns {
        let _ = writeln!(out, "  column {}", column_spec(c));
    }
    for i in &t.indexes {
        let kind = if i.unique { "unique" } else { "index" };
        let _ = writeln!(out, "  {kind} {} ({})", i.name, i.columns.join(", "));
    }
    out.push_str("}\n");
}

/// The `<col> <type> null|not_null [default=…] [unique] [fk=…]` spec shared by
/// `create table` bodies and `add column` steps.
fn column_spec(c: &ColumnSnap) -> String {
    let mut s = format!(
        "{} {} {}",
        c.name,
        c.ty,
        if c.nullable { "null" } else { "not_null" }
    );
    if let Some(d) = &c.default {
        let _ = write!(s, " default={d}");
    }
    if c.unique {
        s.push_str(" unique");
    }
    if let Some(fk) = &c.fk {
        let _ = write!(s, " fk={fk}");
    }
    s
}

fn render_change(c: &ColumnChange) -> String {
    match c {
        ColumnChange::Type { to, .. } => format!("type {to}"),
        ColumnChange::SetNull => "null".to_string(),
        ColumnChange::SetNotNull { .. } => "not_null".to_string(),
        ColumnChange::SetDefault(d) => format!("default={d}"),
        ColumnChange::DropDefault => "drop default".to_string(),
    }
}
