//! OpenAPI codegen (`based gen openapi`): a `CheckedSchema` + AST -> one OpenAPI 3.1
//! document (pretty JSON) describing the JSON/HTTP wire `serve::dispatch` serves — one
//! `POST /q|/m/<name>` path per callable, one `components.schemas` entry per input/output
//! type. Documents the existing wire; invents no endpoint or shape. Mirrors the `client`
//! emitter so routes and schema names stay in lockstep.

use based_ast::*;
use based_sema::{CheckedSchema, MemberKind, RModel, RMutation, RQuery};
use serde_json::{json, Map, Value};

mod callable;
mod find_shape;
mod fixed;
mod input_schema;
mod naming;
mod output_schema;
mod paths;
mod types;

pub(crate) use callable::*;
pub(crate) use find_shape::*;
pub(crate) use fixed::*;
pub(crate) use input_schema::*;
pub(crate) use naming::*;
pub(crate) use output_schema::*;
pub(crate) use paths::*;
pub(crate) use types::*;

/// Render the whole schema as an OpenAPI 3.1 document (pretty-printed JSON).
pub fn openapi(schema: &CheckedSchema, decls: &[Decl]) -> String {
    let doc = document(schema, decls);
    // Pretty JSON keeps the artifact reviewable; a
    // trailing newline matches the SQL/client emitters.
    let mut s = serde_json::to_string_pretty(&doc).expect("openapi document serializes");
    s.push('\n');
    s
}

/// Assemble the full document: the per-callable paths, the deduped component schemas,
/// and the reusable header parameters.
fn document(schema: &CheckedSchema, decls: &[Decl]) -> Value {
    let callables = collect(schema, decls);
    let paths = paths_map(schema, &callables);
    let schemas = schemas_map(schema, decls, &callables);
    let parameters = parameters_map(&callables);

    json!({
        "openapi": "3.1.0",
        "info": {
            "title": "based API",
            "version": "0.1.0",
            "description": "Generated by `based gen openapi`. The closed RPC surface: \
                            one POST route per query/mutation, carrying \
                            arguments as JSON — never the DSL."
        },
        "paths": Value::Object(paths),
        "components": {
            "parameters": Value::Object(parameters),
            "schemas": Value::Object(schemas),
        }
    })
}

/// One `POST` path entry per callable, in declaration order.
fn paths_map(schema: &CheckedSchema, callables: &[Callable]) -> Map<String, Value> {
    let mut paths = Map::new();
    for c in callables {
        paths.insert(c.route.clone(), path_item(schema, c));
    }
    paths
}

/// The `components.schemas` map: the two fixed shared schemas (plus `Ack` when used), the
/// deduped output object schemas, the input-only shape schemas, then the input schemas.
fn schemas_map(
    schema: &CheckedSchema,
    decls: &[Decl],
    callables: &[Callable],
) -> Map<String, Value> {
    let mut schemas = Map::new();
    schemas.insert("Error".to_string(), error_schema());
    schemas.insert("MutationResult".to_string(), mutation_result_schema());
    if schema.mutations.iter().any(|m| m.ack) {
        schemas.insert("Ack".to_string(), ack_schema());
    }

    let mut seen: Vec<String> = Vec::new();
    for c in callables {
        register_out_schema(&c.out_schema, &mut schemas, &mut seen);
    }
    // Input-only shape schemas: a `create … from $param` references a shape that may
    // not appear as any return type — register its component so the `$ref` resolves.
    for c in callables {
        for p in c.params {
            let Some(te) = &p.ty else { continue };
            let BaseType::Model(name) = &te.base else {
                continue;
            };
            if let Some(os) = input_shape_out_schema(schema, decls, &name.node) {
                register_out_schema(&os, &mut schemas, &mut seen);
            }
        }
    }
    for c in callables {
        schemas.insert(input_name(c.name), input_schema(schema, c));
    }
    schemas
}

/// The reusable header parameters: the `$ctx` header every operation references, plus
/// the idempotency-key header when the schema has any mutation.
fn parameters_map(callables: &[Callable]) -> Map<String, Value> {
    let mut parameters = Map::new();
    parameters.insert("BasedContext".to_string(), context_header_param());
    if callables.iter().any(|c| c.is_mutation) {
        parameters.insert("IdempotencyKey".to_string(), idempotency_key_header_param());
    }
    parameters
}
