// Generated by `based gen client` (target: rust). Do not edit by hand.
//
// The closed RPC surface: one input type, one output type, and one route per
// signature. Transport is abstract — implement `Transport` to post JSON to a route
// and decode the reply; the runtime supplies the concrete HTTP client.
//
// Some generated items may be unused by a given consumer; suppress dead-code warnings by
// including this module under an outer `#[allow(dead_code)] mod client { … }` (an inner
// `#![allow]` would be rejected by `include!`).

use serde::{Deserialize, Serialize};
use std::marker::PhantomData;

// Semantic aliases for the wire types (mirrors the DDL mapping).
pub type Uuid = String;
pub type Timestamp = String;
pub type Date = String;
pub type Json = serde_json::Value;

/// A typed id: the primary key of entity `E`, carried on the wire as its raw string
/// (`#[serde(transparent)]`, so the wire is unchanged). The `E` marker keeps ids of
/// different entities distinct types, so a `User` id can't be passed where an `Org` id
/// is wanted. A `create_*` result already hands one back typed; turn a raw string into
/// one only through the explicit, greppable `Id::from_raw`.
#[derive(Serialize, Deserialize)]
#[serde(transparent, bound = "")]
pub struct Id<E> {
    raw: String,
    #[serde(skip)]
    _entity: PhantomData<fn() -> E>,
}

impl<E> Id<E> {
    /// Wrap a raw id string as a typed id — the explicit escape from an untyped string,
    /// used only where the string's entity is known (an id from outside the client).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Id {
            raw: raw.into(),
            _entity: PhantomData,
        }
    }
    /// The underlying id string.
    pub fn as_str(&self) -> &str {
        &self.raw
    }
    /// Consume into the raw id string.
    pub fn into_raw(self) -> String {
        self.raw
    }
}

// Hand-written so the marker `E` carries no trait bounds (a derive would demand
// `E: Clone`, `E: Ord`, … of a type that only ever tags).
impl<E> Clone for Id<E> {
    fn clone(&self) -> Self {
        Id {
            raw: self.raw.clone(),
            _entity: PhantomData,
        }
    }
}
impl<E> std::fmt::Debug for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Id({:?})", self.raw)
    }
}
impl<E> std::fmt::Display for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.raw)
    }
}
impl<E> PartialEq for Id<E> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}
impl<E> Eq for Id<E> {}
impl<E> PartialOrd for Id<E> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl<E> Ord for Id<E> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.raw.cmp(&other.raw)
    }
}
impl<E> std::hash::Hash for Id<E> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.raw.hash(state);
    }
}

/// An opaque keyset pagination cursor, carried on the wire as its underlying string
/// (`#[serde(transparent)]`, so the wire is unchanged). A page result hands one back and
/// the caller feeds it to the next call; its contents (the sort-key basis) are a runtime
/// concern the caller never assembles. Turn a raw string into one only through the
/// explicit, greppable `Cursor::from_raw`.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Cursor(String);

impl Cursor {
    /// Wrap a raw cursor string — the explicit escape used only where a cursor string
    /// arrives from outside the client (normally a page result already hands one back typed).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Cursor(raw.into())
    }
    /// The underlying cursor string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
    /// Consume into the raw cursor string.
    pub fn into_raw(self) -> String {
        self.0
    }
}

impl std::fmt::Debug for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Cursor({:?})", self.0)
    }
}
impl std::fmt::Display for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Pagination envelope: a paginated query returns rows + an opaque cursor.
/// Next page = the same call carrying `cursor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub cursor: Option<Cursor>,
    /// Total matching rows. `Some` exactly when the query declares `with count`
    /// (the wire carries `total` only then).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
}

/// What went wrong in a client call — lets a caller branch on the class of failure
/// without matching on the message text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientErrorKind {
    /// The request never completed a round-trip — a socket/connection/engine failure.
    /// Retryable in the same way the underlying transport is.
    Transport,
    /// The round-trip completed but a value could not be (de)serialized into its typed
    /// input or output. A bug in the caller's types or the payload, not a server error.
    Decode,
    /// The server ran the call and returned a structured error (its HTTP `status` and a
    /// stable machine `code`, e.g. `bad_arg`, `missing_ctx`, `database_error`).
    Api { status: u16, code: String },
}

/// An error from a client call: a transport failure, a (de)serialization failure, or a
/// structured error the server returned. Carries a stable machine [`code`](ClientError::code)
/// and a clear human message; a server error also carries its HTTP [`status`](ClientError::status).
/// Implements `std::error::Error`, so it chains with `?` and its underlying cause is reachable
/// via `source()`.
#[derive(Debug, Clone)]
pub struct ClientError {
    kind: ClientErrorKind,
    message: String,
    // Kept behind an `Arc` so `ClientError` stays `Clone` while still handing back a live
    // `&dyn Error` from `source()`.
    source: Option<std::sync::Arc<dyn std::error::Error + Send + Sync + 'static>>,
}

impl ClientError {
    /// A transport failure (the round-trip never completed), wrapping its cause.
    pub fn transport(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Transport,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A (de)serialization failure decoding an input or the reply, wrapping its cause.
    pub fn decode(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Decode,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A structured error the server returned: its HTTP `status`, stable machine `code`, and
    /// human `message` (the `{ error: { code, message } }` envelope).
    pub fn api(status: u16, code: impl Into<String>, message: impl Into<String>) -> Self {
        ClientError {
            kind: ClientErrorKind::Api {
                status,
                code: code.into(),
            },
            message: message.into(),
            source: None,
        }
    }

    /// The failure class (transport / decode / server-side api).
    pub fn kind(&self) -> &ClientErrorKind {
        &self.kind
    }

    /// The human-readable message.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// A stable machine-readable code: the server's `error.code` for an api failure, else
    /// `"transport"` / `"decode"`. Safe to branch on.
    pub fn code(&self) -> &str {
        match &self.kind {
            ClientErrorKind::Transport => "transport",
            ClientErrorKind::Decode => "decode",
            ClientErrorKind::Api { code, .. } => code,
        }
    }

    /// The HTTP status of a server-side (api) failure; `None` for a transport/decode failure.
    pub fn status(&self) -> Option<u16> {
        match &self.kind {
            ClientErrorKind::Api { status, .. } => Some(*status),
            _ => None,
        }
    }
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ClientErrorKind::Transport => write!(f, "transport error: {}", self.message),
            ClientErrorKind::Decode => write!(f, "decode error: {}", self.message),
            ClientErrorKind::Api { status, code } => {
                write!(f, "server error {status} [{code}]: {}", self.message)
            }
        }
    }
}

impl std::error::Error for ClientError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|e| &**e as &(dyn std::error::Error + 'static))
    }
}

// ---------- streaming ----------

/// A live row stream from a `-> stream` query, in sort order. Each item is one typed
/// row; an in-band server failure or a truncated body arrives as an `Err` item, and
/// after an `Err` item the stream is finished. **Drop = cancel**: dropping the stream
/// abandons the pass and releases its resources (the server gets its database
/// connection back).
pub type RowStream<O> =
    std::pin::Pin<Box<dyn futures_core::Stream<Item = Result<O, ClientError>> + Send>>;

/// Decode an NDJSON response body (any stream of byte chunks) into the typed row
/// stream, enforcing the framing contract: one `{"row":…}` envelope per line, then
/// exactly one terminal line — `{"done":{"rows":N}}` on success (`rows` doubles as an
/// integrity checksum) or `{"error":{code,message}}` for an in-band failure (an `Err`
/// item carrying the server's stable code). A body that ends **without** a terminal
/// line was truncated (connection cut, server death) and yields a transport-kind
/// `Err`, never silent completion. An HTTP `Transport` feeds its response body
/// through this, so the framing rules live here once.
pub fn decode_ndjson<O, B, C, E>(body: B) -> RowStream<O>
where
    O: serde::de::DeserializeOwned + Send + 'static,
    B: futures_core::Stream<Item = Result<C, E>> + Send + 'static,
    C: AsRef<[u8]>,
    E: std::error::Error + Send + Sync + 'static,
{
    Box::pin(NdjsonRows {
        body: Box::pin(body),
        buf: Vec::new(),
        rows_seen: 0,
        body_done: false,
        finished: false,
        _row: PhantomData,
    })
}

/// The stream behind [`decode_ndjson`]: buffers body chunks, decodes each complete
/// line as one envelope, and tracks the terminal-line contract.
struct NdjsonRows<B, O> {
    body: std::pin::Pin<Box<B>>,
    buf: Vec<u8>,
    /// Rows yielded so far, checked against the terminal `done.rows` checksum.
    rows_seen: u64,
    /// The body ended (EOF). Reaching it before a terminal line is truncation.
    body_done: bool,
    /// A terminal line (or terminal `Err` item) was emitted; the stream is over.
    finished: bool,
    _row: PhantomData<fn() -> O>,
}

impl<B, C, E, O> futures_core::Stream for NdjsonRows<B, O>
where
    B: futures_core::Stream<Item = Result<C, E>>,
    C: AsRef<[u8]>,
    E: std::error::Error + Send + Sync + 'static,
    O: serde::de::DeserializeOwned,
{
    type Item = Result<O, ClientError>;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        use std::task::Poll;
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }
        loop {
            // Decode every complete buffered line before touching the transport.
            while let Some(pos) = this.buf.iter().position(|&b| b == b'\n') {
                let line: Vec<u8> = this.buf.drain(..=pos).collect();
                let line = &line[..line.len() - 1];
                if line.iter().all(|b| b.is_ascii_whitespace()) {
                    continue;
                }
                let envelope: serde_json::Value = match serde_json::from_slice(line) {
                    Ok(v) => v,
                    Err(e) => {
                        this.finished = true;
                        return Poll::Ready(Some(Err(ClientError::decode(e))));
                    }
                };
                if let Some(row) = envelope.get("row") {
                    this.rows_seen += 1;
                    return Poll::Ready(Some(match serde_json::from_value::<O>(row.clone()) {
                        Ok(row) => Ok(row),
                        Err(e) => {
                            this.finished = true;
                            Err(ClientError::decode(e))
                        }
                    }));
                }
                if let Some(done) = envelope.get("done") {
                    this.finished = true;
                    // `done.rows` is the integrity checksum: a disagreement means a
                    // row line was lost in transit — report it, never silent success.
                    let counted = done.get("rows").and_then(serde_json::Value::as_u64);
                    if counted != Some(this.rows_seen) {
                        return Poll::Ready(Some(Err(ClientError::transport(format!(
                            "stream checksum mismatch: server reports {counted:?} rows, received {}",
                            this.rows_seen
                        )))));
                    }
                    return Poll::Ready(None);
                }
                if let Some(error) = envelope.get("error") {
                    this.finished = true;
                    // The 200 status line was spent before the failure; 503 is the
                    // status the same database failure carries before the body.
                    let code = error["code"].as_str().unwrap_or("error");
                    let message = error["message"].as_str().unwrap_or("stream failed");
                    return Poll::Ready(Some(Err(ClientError::api(503, code, message))));
                }
                this.finished = true;
                return Poll::Ready(Some(Err(ClientError::transport(format!(
                    "unrecognized stream envelope: {envelope}"
                )))));
            }
            if this.body_done {
                // EOF without a terminal line (a partial line in the buffer counts):
                // the body was truncated. Never treat it as completion.
                this.finished = true;
                return Poll::Ready(Some(Err(ClientError::transport(
                    "response body ended without a terminal `done`/`error` line (truncated)"
                        .to_string(),
                ))));
            }
            match this.body.as_mut().poll_next(cx) {
                Poll::Ready(Some(Ok(chunk))) => this.buf.extend_from_slice(chunk.as_ref()),
                Poll::Ready(Some(Err(e))) => {
                    this.finished = true;
                    return Poll::Ready(Some(Err(ClientError::transport(e))));
                }
                Poll::Ready(None) => this.body_done = true,
                Poll::Pending => return Poll::Pending,
            }
        }
    }
}

/// Post a typed input to a route, carry the typed request context (`$ctx`, carried out
/// of band as request context), and decode the typed output. A callable with no `$ctx`
/// requirements passes `ctx: &()`. Async: a transport awaits its round-trip (an HTTP
/// client's socket, or the in-process engine's execution). Codegen only depends on
/// this shape.
#[allow(async_fn_in_trait)]
pub trait Transport {
    async fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned;

    /// Like [`call`](Transport::call), carrying a mutation **idempotency key** out of
    /// band — an HTTP transport sends it as the `Idempotency-Key` header; the embedded
    /// transport hands it to `Engine::call_with_key`. A retry with the same key replays
    /// the first attempt's recorded response instead of running the write again.
    async fn call_with_key<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
        key: &str,
    ) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned;

    /// Start a `-> stream` query and return its live row stream. An `Err` here means
    /// the call never started — a transport failure or a pre-body rejection carrying
    /// its real HTTP status; a failure after the stream begins arrives as the stream's
    /// final `Err` item. An HTTP transport feeds the NDJSON response body through
    /// [`decode_ndjson`]; the embedded transport yields the engine's rows in-process.
    async fn call_stream<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
    ) -> Result<RowStream<O>, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned + Send + 'static;
}

/// The generated client, generic over a `Transport`.
pub struct Client<T> {
    pub transport: T,
}

/// Phantom entity tags for `Id<entity::M>` (types only, never constructed).
pub mod entity {
    pub enum Comment {}
    pub enum DraftNote {}
    pub enum Org {}
    pub enum Session {}
    pub enum Ticket {}
    pub enum TimeEntry {}
    pub enum User {}
}

// ---------- enums ----------
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "waiting_on_customer")]
    Waiting,
    #[serde(rename = "resolved")]
    Resolved,
    #[serde(rename = "closed")]
    Closed,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Priority {
    Low = 1,
    Normal = 2,
    High = 3,
    Urgent = 4,
}
impl serde::Serialize for Priority {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_i64(*self as i64)
    }
}
impl<'de> serde::Deserialize<'de> for Priority {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let n = i64::deserialize(d)?;
        match n {
            1 => Ok(Priority::Low),
            2 => Ok(Priority::Normal),
            3 => Ok(Priority::High),
            4 => Ok(Priority::Urgent),
            other => Err(serde::de::Error::custom(format!("invalid Priority value: {other}"))),
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "requester")]
    Requester,
    #[serde(rename = "agent")]
    Agent,
    #[serde(rename = "admin")]
    Admin,
}

// ---------- output types ----------

/// The empty acknowledgement a `-> ok` mutation answers with (`{}` on the wire —
/// a real DELETE leaves no row to return). Methods decode it and return `()`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Ack {}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommentRow {
    pub id: Id<entity::Comment>,
    pub body: String,
    pub created_at: Timestamp,
    pub author: UserRef,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRef {
    pub id: Id<entity::User>,
    pub name: String,
    pub email: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DraftRow {
    pub id: Id<entity::DraftNote>,
    pub body: String,
    pub created_at: Timestamp,
    pub ticket: Id<entity::Ticket>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrgRow {
    pub id: Id<entity::Org>,
    pub name: String,
    pub slug: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
    pub role: Role,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketRow {
    pub id: Id<entity::Ticket>,
    pub subject: String,
    pub status: Status,
    pub priority: Priority,
    pub created_at: Timestamp,
    pub requester_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketDetail {
    pub id: Id<entity::Ticket>,
    pub subject: String,
    pub status: Status,
    pub priority: Priority,
    pub tags: Option<Json>,
    pub created_at: Timestamp,
    pub updated_at: Timestamp,
    pub requester: UserRef,
    pub assignee: Option<UserRef>,
    pub duplicates: Vec<TicketRow>,
    pub comments: Vec<CommentRow>,
    pub time_entries: Vec<TicketDetailTimeEntries>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketDetailTimeEntries {
    pub hours: f64,
    pub amount: rust_decimal::Decimal,
    pub note: Option<String>,
    pub logged_at: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketExport {
    pub id: Id<entity::Ticket>,
    pub subject: String,
    pub status: Status,
    pub priority: Priority,
    pub created_at: Timestamp,
    pub org: String,
    pub requester: String,
    pub age_days: Json,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TimeEntryRow {
    pub id: Id<entity::TimeEntry>,
    pub hours: f64,
    pub amount: rust_decimal::Decimal,
    pub note: Option<String>,
    pub logged_at: Timestamp,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentWorkload {
    pub name: String,
    pub rate: Option<rust_decimal::Decimal>,
    pub open_tickets: Json,
    pub hours_logged: Json,
    pub billed: Json,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRow {
    pub id: Id<entity::User>,
    pub name: String,
    pub email: String,
    pub role: Role,
}

// ---------- inputs + routes ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddCommentInput {
    pub ticket: Id<entity::Ticket>,
    pub body: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AddCommentCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
}
/// Wire route for `add_comment`.
pub const ADD_COMMENT_ROUTE: &str = "/m/add_comment";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurgeCommentInput {
    pub id: Id<entity::Comment>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PurgeCommentCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `purge_comment`.
pub const PURGE_COMMENT_ROUTE: &str = "/m/purge_comment";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyDraftsInput {
    pub ticket: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyDraftsCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
}
/// Wire route for `my_drafts`.
pub const MY_DRAFTS_ROUTE: &str = "/q/my_drafts";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SaveDraftInput {
    pub ticket: Id<entity::Ticket>,
    pub body: String,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SaveDraftCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
}
/// Wire route for `save_draft`.
pub const SAVE_DRAFT_ROUTE: &str = "/m/save_draft";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateOrgInput {
    pub name: String,
    pub slug: String,
}
/// Wire route for `create_org`.
pub const CREATE_ORG_ROUTE: &str = "/m/create_org";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionByTokenInput {
    pub token: String,
}
/// Wire route for `session_by_token`.
pub const SESSION_BY_TOKEN_ROUTE: &str = "/q/session_by_token";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StartSessionInput {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
    pub token: String,
}
/// Wire route for `start_session`.
pub const START_SESSION_ROUTE: &str = "/m/start_session";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyTicketsInput;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyTicketsCtx {
    pub user: Id<entity::User>,
}
/// Wire route for `my_tickets`.
pub const MY_TICKETS_ROUTE: &str = "/q/my_tickets";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenTicketInput {
    pub subject: String,
    pub body: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub priority: Option<Priority>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OpenTicketCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
}
/// Wire route for `open_ticket`.
pub const OPEN_TICKET_ROUTE: &str = "/m/open_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketInput {
    pub id: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `ticket`.
pub const TICKET_ROUTE: &str = "/q/ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketsForInput {
    pub agent: Id<entity::User>,
    pub since: Timestamp,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TicketsForCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `tickets_for`.
pub const TICKETS_FOR_ROUTE: &str = "/q/tickets_for";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchTicketsInput {
    pub q: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<Cursor>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchTicketsCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `search_tickets`.
pub const SEARCH_TICKETS_ROUTE: &str = "/q/search_tickets";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueueInput;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QueueCtx {
    pub org: Id<entity::Org>,
    pub user: Id<entity::User>,
}
/// Wire route for `queue`.
pub const QUEUE_ROUTE: &str = "/q/queue";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaggedTicketsInput {
    pub tag: Json,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaggedTicketsCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `tagged_tickets`.
pub const TAGGED_TICKETS_ROUTE: &str = "/q/tagged_tickets";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssignTicketInput {
    pub id: Id<entity::Ticket>,
    pub agent: Id<entity::User>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssignTicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `assign_ticket`.
pub const ASSIGN_TICKET_ROUTE: &str = "/m/assign_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetStatusInput {
    pub id: Id<entity::Ticket>,
    pub status: Status,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SetStatusCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `set_status`.
pub const SET_STATUS_ROUTE: &str = "/m/set_status";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagTicketInput {
    pub id: Id<entity::Ticket>,
    pub tags: Json,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TagTicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `tag_ticket`.
pub const TAG_TICKET_ROUTE: &str = "/m/tag_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarkDuplicateInput {
    pub id: Id<entity::Ticket>,
    pub of: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarkDuplicateCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `mark_duplicate`.
pub const MARK_DUPLICATE_ROUTE: &str = "/m/mark_duplicate";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CloseTicketInput {
    pub id: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CloseTicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `close_ticket`.
pub const CLOSE_TICKET_ROUTE: &str = "/m/close_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArchiveTicketInput {
    pub id: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArchiveTicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `archive_ticket`.
pub const ARCHIVE_TICKET_ROUTE: &str = "/m/archive_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreTicketInput {
    pub id: Id<entity::Ticket>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreTicketCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `restore_ticket`.
pub const RESTORE_TICKET_ROUTE: &str = "/m/restore_ticket";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminTicketsInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
}
/// Wire route for `admin_tickets`.
pub const ADMIN_TICKETS_ROUTE: &str = "/q/admin_tickets";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExportTicketsInput {
    pub since: Timestamp,
}
/// Wire route for `export_tickets`.
pub const EXPORT_TICKETS_ROUTE: &str = "/q/export_tickets";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogTimeInput {
    pub ticket: Id<entity::Ticket>,
    pub hours: f64,
    pub amount: rust_decimal::Decimal,
    pub note: String,
    pub logged_at: Timestamp,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogTimeCtx {
    pub user: Id<entity::User>,
}
/// Wire route for `log_time`.
pub const LOG_TIME_ROUTE: &str = "/m/log_time";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WorkloadReportInput {
    pub org: Id<entity::Org>,
}
/// Wire route for `workload_report`.
pub const WORKLOAD_REPORT_ROUTE: &str = "/q/workload_report";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserInput {
    pub org: Id<entity::Org>,
    pub name: String,
    pub email: String,
    pub role: Role,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rate: Option<rust_decimal::Decimal>,
}
/// Wire route for `create_user`.
pub const CREATE_USER_ROUTE: &str = "/m/create_user";

// ---------- client ----------

impl<T: Transport> Client<T> {
    /// `POST /m/add_comment`
    pub async fn add_comment(&self, input: AddCommentInput, ctx: AddCommentCtx) -> Result<CommentRow, ClientError> {
        self.transport.call(ADD_COMMENT_ROUTE, &input, &ctx).await
    }
    /// `POST /m/add_comment` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn add_comment_with_key(
        &self,
        input: AddCommentInput,
        ctx: AddCommentCtx,
        key: &str,
    ) -> Result<CommentRow, ClientError> {
        self.transport.call_with_key(ADD_COMMENT_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/purge_comment` — a `-> ok` mutation: the delete ran (`Ok(())`), or the
    /// row was absent/out of scope (a `404 not_found` error).
    pub async fn purge_comment(&self, input: PurgeCommentInput, ctx: PurgeCommentCtx) -> Result<(), ClientError> {
        let _: Ack = self.transport.call(PURGE_COMMENT_ROUTE, &input, &ctx).await?;
        Ok(())
    }
    /// `POST /m/purge_comment` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn purge_comment_with_key(
        &self,
        input: PurgeCommentInput,
        ctx: PurgeCommentCtx,
        key: &str,
    ) -> Result<(), ClientError> {
        let _: Ack = self.transport.call_with_key(PURGE_COMMENT_ROUTE, &input, &ctx, key).await?;
        Ok(())
    }
    /// `POST /q/my_drafts`
    pub async fn my_drafts(&self, input: MyDraftsInput, ctx: MyDraftsCtx) -> Result<Vec<DraftRow>, ClientError> {
        self.transport.call(MY_DRAFTS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/save_draft`
    pub async fn save_draft(&self, input: SaveDraftInput, ctx: SaveDraftCtx) -> Result<DraftRow, ClientError> {
        self.transport.call(SAVE_DRAFT_ROUTE, &input, &ctx).await
    }
    /// `POST /m/save_draft` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn save_draft_with_key(
        &self,
        input: SaveDraftInput,
        ctx: SaveDraftCtx,
        key: &str,
    ) -> Result<DraftRow, ClientError> {
        self.transport.call_with_key(SAVE_DRAFT_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/create_org`
    pub async fn create_org(&self, input: CreateOrgInput, ctx: ()) -> Result<OrgRow, ClientError> {
        self.transport.call(CREATE_ORG_ROUTE, &input, &ctx).await
    }
    /// `POST /m/create_org` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn create_org_with_key(
        &self,
        input: CreateOrgInput,
        ctx: (),
        key: &str,
    ) -> Result<OrgRow, ClientError> {
        self.transport.call_with_key(CREATE_ORG_ROUTE, &input, &ctx, key).await
    }
    /// `POST /q/session_by_token`
    pub async fn session_by_token(&self, input: SessionByTokenInput, ctx: ()) -> Result<Option<SessionCtx>, ClientError> {
        self.transport.call(SESSION_BY_TOKEN_ROUTE, &input, &ctx).await
    }
    /// `POST /m/start_session`
    pub async fn start_session(&self, input: StartSessionInput, ctx: ()) -> Result<SessionCtx, ClientError> {
        self.transport.call(START_SESSION_ROUTE, &input, &ctx).await
    }
    /// `POST /m/start_session` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn start_session_with_key(
        &self,
        input: StartSessionInput,
        ctx: (),
        key: &str,
    ) -> Result<SessionCtx, ClientError> {
        self.transport.call_with_key(START_SESSION_ROUTE, &input, &ctx, key).await
    }
    /// `POST /q/my_tickets`
    pub async fn my_tickets(&self, input: MyTicketsInput, ctx: MyTicketsCtx) -> Result<Vec<TicketRow>, ClientError> {
        self.transport.call(MY_TICKETS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/open_ticket`
    pub async fn open_ticket(&self, input: OpenTicketInput, ctx: OpenTicketCtx) -> Result<TicketDetail, ClientError> {
        self.transport.call(OPEN_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/open_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn open_ticket_with_key(
        &self,
        input: OpenTicketInput,
        ctx: OpenTicketCtx,
        key: &str,
    ) -> Result<TicketDetail, ClientError> {
        self.transport.call_with_key(OPEN_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /q/ticket`
    pub async fn ticket(&self, input: TicketInput, ctx: TicketCtx) -> Result<Option<TicketDetail>, ClientError> {
        self.transport.call(TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /q/tickets_for`
    pub async fn tickets_for(&self, input: TicketsForInput, ctx: TicketsForCtx) -> Result<Vec<TicketRow>, ClientError> {
        self.transport.call(TICKETS_FOR_ROUTE, &input, &ctx).await
    }
    /// `POST /q/search_tickets`
    pub async fn search_tickets(&self, input: SearchTicketsInput, ctx: SearchTicketsCtx) -> Result<Page<TicketRow>, ClientError> {
        self.transport.call(SEARCH_TICKETS_ROUTE, &input, &ctx).await
    }
    /// `POST /q/queue`
    pub async fn queue(&self, input: QueueInput, ctx: QueueCtx) -> Result<Vec<TicketRow>, ClientError> {
        self.transport.call(QUEUE_ROUTE, &input, &ctx).await
    }
    /// `POST /q/tagged_tickets`
    pub async fn tagged_tickets(&self, input: TaggedTicketsInput, ctx: TaggedTicketsCtx) -> Result<Vec<TicketRow>, ClientError> {
        self.transport.call(TAGGED_TICKETS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/assign_ticket`
    pub async fn assign_ticket(&self, input: AssignTicketInput, ctx: AssignTicketCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(ASSIGN_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/assign_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn assign_ticket_with_key(
        &self,
        input: AssignTicketInput,
        ctx: AssignTicketCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(ASSIGN_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/set_status`
    pub async fn set_status(&self, input: SetStatusInput, ctx: SetStatusCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(SET_STATUS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/set_status` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn set_status_with_key(
        &self,
        input: SetStatusInput,
        ctx: SetStatusCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(SET_STATUS_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/tag_ticket`
    pub async fn tag_ticket(&self, input: TagTicketInput, ctx: TagTicketCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(TAG_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/tag_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn tag_ticket_with_key(
        &self,
        input: TagTicketInput,
        ctx: TagTicketCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(TAG_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/mark_duplicate`
    pub async fn mark_duplicate(&self, input: MarkDuplicateInput, ctx: MarkDuplicateCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(MARK_DUPLICATE_ROUTE, &input, &ctx).await
    }
    /// `POST /m/mark_duplicate` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn mark_duplicate_with_key(
        &self,
        input: MarkDuplicateInput,
        ctx: MarkDuplicateCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(MARK_DUPLICATE_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/close_ticket`
    pub async fn close_ticket(&self, input: CloseTicketInput, ctx: CloseTicketCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(CLOSE_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/close_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn close_ticket_with_key(
        &self,
        input: CloseTicketInput,
        ctx: CloseTicketCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(CLOSE_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/archive_ticket`
    pub async fn archive_ticket(&self, input: ArchiveTicketInput, ctx: ArchiveTicketCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(ARCHIVE_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/archive_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn archive_ticket_with_key(
        &self,
        input: ArchiveTicketInput,
        ctx: ArchiveTicketCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(ARCHIVE_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /m/restore_ticket`
    pub async fn restore_ticket(&self, input: RestoreTicketInput, ctx: RestoreTicketCtx) -> Result<TicketRow, ClientError> {
        self.transport.call(RESTORE_TICKET_ROUTE, &input, &ctx).await
    }
    /// `POST /m/restore_ticket` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn restore_ticket_with_key(
        &self,
        input: RestoreTicketInput,
        ctx: RestoreTicketCtx,
        key: &str,
    ) -> Result<TicketRow, ClientError> {
        self.transport.call_with_key(RESTORE_TICKET_ROUTE, &input, &ctx, key).await
    }
    /// `POST /q/admin_tickets`
    pub async fn admin_tickets(&self, input: AdminTicketsInput, ctx: ()) -> Result<Page<TicketRow>, ClientError> {
        self.transport.call(ADMIN_TICKETS_ROUTE, &input, &ctx).await
    }
    /// `POST /q/export_tickets` — a `-> stream` query: the rows arrive as a live typed
    /// stream; drop it to cancel the pass.
    pub async fn export_tickets(&self, input: ExportTicketsInput, ctx: ()) -> Result<RowStream<TicketExport>, ClientError> {
        self.transport.call_stream(EXPORT_TICKETS_ROUTE, &input, &ctx).await
    }
    /// `POST /m/log_time`
    pub async fn log_time(&self, input: LogTimeInput, ctx: LogTimeCtx) -> Result<TimeEntryRow, ClientError> {
        self.transport.call(LOG_TIME_ROUTE, &input, &ctx).await
    }
    /// `POST /m/log_time` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn log_time_with_key(
        &self,
        input: LogTimeInput,
        ctx: LogTimeCtx,
        key: &str,
    ) -> Result<TimeEntryRow, ClientError> {
        self.transport.call_with_key(LOG_TIME_ROUTE, &input, &ctx, key).await
    }
    /// `POST /q/workload_report`
    pub async fn workload_report(&self, input: WorkloadReportInput, ctx: ()) -> Result<Vec<AgentWorkload>, ClientError> {
        self.transport.call(WORKLOAD_REPORT_ROUTE, &input, &ctx).await
    }
    /// `POST /m/create_user`
    pub async fn create_user(&self, input: CreateUserInput, ctx: ()) -> Result<UserRow, ClientError> {
        self.transport.call(CREATE_USER_ROUTE, &input, &ctx).await
    }
    /// `POST /m/create_user` carrying `key` as the mutation **idempotency key**: a retry
    /// with the same key replays the first attempt's response instead of writing again.
    pub async fn create_user_with_key(
        &self,
        input: CreateUserInput,
        ctx: (),
        key: &str,
    ) -> Result<UserRow, ClientError> {
        self.transport.call_with_key(CREATE_USER_ROUTE, &input, &ctx, key).await
    }
}

// ---------- embedded bridge (based_runtime::Engine) ----------

/// A `Transport` backed by an in-process `based_runtime::Engine` — every callable runs
/// through the engine's dispatch core with no socket. Build one with [`embedded`].
pub struct Embedded<'a> {
    engine: &'a based_runtime::Engine,
}

impl Transport for Embedded<'_> {
    async fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        let resp = self.engine.call(route, args, ctx).await;
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(ClientError::decode)
        } else {
            // Preserve the server's structured error: its status + stable code + message.
            let code = resp.body["error"]["code"].as_str().unwrap_or("error");
            let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
            Err(ClientError::api(resp.status, code, message))
        }
    }

    /// The keyed door in-process: the same idempotent-replay contract the HTTP
    /// `Idempotency-Key` header gets, via `Engine::call_with_key` — no header dance.
    async fn call_with_key<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
        key: &str,
    ) -> Result<O, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        let resp = self
            .engine
            .call_with_key(route, args, ctx, Some(key.to_string()))
            .await;
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(ClientError::decode)
        } else {
            // Preserve the server's structured error: its status + stable code + message.
            let code = resp.body["error"]["code"].as_str().unwrap_or("error");
            let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
            Err(ClientError::api(resp.status, code, message))
        }
    }

    /// Start a `-> stream` query in-process: the engine's shaped row stream decoded
    /// into the typed shape — the same items the HTTP path yields, with no socket and
    /// no NDJSON round-trip. The stream owns its database connection; dropping it
    /// cancels the pass and returns the connection to the pool.
    async fn call_stream<I, C, O>(
        &self,
        route: &str,
        input: &I,
        ctx: &C,
    ) -> Result<RowStream<O>, ClientError>
    where
        I: Serialize + Sync,
        C: Serialize + Sync,
        O: serde::de::DeserializeOwned + Send + 'static,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        match self.engine.call_stream(route, args, ctx).await {
            Ok(rows) => Ok(Box::pin(EngineRows {
                inner: rows,
                finished: false,
                _row: PhantomData,
            })),
            // A pre-body rejection: the same status + stable code the wire would send.
            Err(resp) => {
                let code = resp.body["error"]["code"].as_str().unwrap_or("error");
                let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
                Err(ClientError::api(resp.status, code, message))
            }
        }
    }
}

/// A ready-to-use client over an in-process `based_runtime::Engine` — no bridge to write.
/// `$ctx` is a typed per-call argument the app sets, not the caller; a public callable
/// passes `()`, which maps to an empty context bag.
pub fn embedded(engine: &based_runtime::Engine) -> Client<Embedded<'_>> {
    Client {
        transport: Embedded { engine },
    }
}

/// The embedded transport's row stream: `based_runtime::ShapedStream` items decoded
/// into the typed shape. After an `Err` item the stream is finished (the engine's
/// stream already ends after its error; a decode failure ends this one).
struct EngineRows<O> {
    inner: based_runtime::ShapedStream,
    finished: bool,
    _row: PhantomData<fn() -> O>,
}

impl<O: serde::de::DeserializeOwned> futures_core::Stream for EngineRows<O> {
    type Item = Result<O, ClientError>;

    fn poll_next(
        self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Option<Self::Item>> {
        use std::task::Poll;
        let this = self.get_mut();
        if this.finished {
            return Poll::Ready(None);
        }
        match this.inner.as_mut().poll_next(cx) {
            Poll::Ready(Some(Ok(row))) => {
                Poll::Ready(Some(match serde_json::from_value::<O>(row) {
                    Ok(row) => Ok(row),
                    Err(e) => {
                        this.finished = true;
                        Err(ClientError::decode(e))
                    }
                }))
            }
            Poll::Ready(Some(Err(e))) => {
                this.finished = true;
                // A mid-pass database failure: the same stable code the wire's in-band
                // `error` line carries, with the 503 the failure maps to pre-body.
                Poll::Ready(Some(Err(ClientError::api(503, e.code(), e.message))))
            }
            Poll::Ready(None) => Poll::Ready(None),
            Poll::Pending => Poll::Pending,
        }
    }
}
