//! The `based gen sql` textual output: the file header and per-query `-- query` framing.

use super::*;

/// Render every query in the schema as a parameterized SELECT (mutations join in a
/// later increment). Statements are separated by blank lines, in declaration order.
pub fn dml(schema: &CheckedSchema, decls: &[Decl], dialect: Dialect) -> String {
    // The one lowering below is shared with the runtime, so the emitted and executed SQL
    // can never disagree per dialect (identifier quoting, bare-bool literal, JSON
    // containment all branch on the dialect inside `lower_query`).
    let queries = index_queries(schema);
    let mut out = String::new();
    out.push_str(&format!(
        "-- Generated by `based gen sql` (dialect: {}). Do not edit by hand.\n",
        dialect.name()
    ));
    out.push_str("-- Query templates: `:name` placeholders are bound by the generated client.\n");
    for decl in decls {
        if let Decl::Query(q) = decl {
            if let Some(rq) = queries.get(q.name.node.as_str()) {
                out.push('\n');
                out.push_str(&render_query(schema, decls, q, rq, dialect));
            }
        }
    }
    out
}

/// Text emitter for one query: the SQL body framed with `-- query` comment
/// headers (the `based gen sql` surface). Delegates the SQL to `lower_query`.
fn render_query(
    schema: &CheckedSchema,
    decls: &[Decl],
    q: &Query,
    rq: &RQuery,
    dialect: Dialect,
) -> String {
    let low = lower_query(schema, decls, q, rq, dialect);
    let mut out = format!("-- query {}\n{}", low.name, low.sql);
    if let Some(count) = &low.count_sql {
        out.push('\n');
        out.push_str(&format!("-- query {} (count)\n{}", low.name, count));
    }
    out
}
