// Generated by `based gen client` (target: rust). Do not edit by hand.
//
// The closed RPC surface (calling.md): one input type, one output type, and one
// route per signature. Transport is abstract — implement `Transport` to post JSON
// to a route and decode the reply; the runtime supplies the concrete HTTP client.
//
// Some generated items may be unused by a given consumer; suppress dead-code warnings by
// including this module under an outer `#[allow(dead_code)] mod client { … }` (the standard
// pattern for generated code — an inner `#![allow]` would be rejected by `include!`).

use serde::{Deserialize, Serialize};
use std::marker::PhantomData;

// Semantic aliases for the wire types (mirrors the DDL mapping).
pub type Uuid = String;
pub type Timestamp = String;
pub type Date = String;
pub type Json = serde_json::Value;

/// A typed id: the primary key of entity `E`, carried on the wire as its raw string
/// (`#[serde(transparent)]`, so the wire is unchanged). The `E` marker keeps ids of
/// different entities distinct types, so a `User` id can't be passed where an `Org` id
/// is wanted. A `create_*` result already hands one back typed; turn a raw string into
/// one only through the explicit, greppable `Id::from_raw`.
#[derive(Serialize, Deserialize)]
#[serde(transparent, bound = "")]
pub struct Id<E> {
    raw: String,
    #[serde(skip)]
    _entity: PhantomData<fn() -> E>,
}

impl<E> Id<E> {
    /// Wrap a raw id string as a typed id — the explicit escape from an untyped string,
    /// used only where the string's entity is known (an id from outside the client).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Id {
            raw: raw.into(),
            _entity: PhantomData,
        }
    }
    /// The underlying id string.
    pub fn as_str(&self) -> &str {
        &self.raw
    }
    /// Consume into the raw id string.
    pub fn into_raw(self) -> String {
        self.raw
    }
}

// Hand-written so the marker `E` carries no trait bounds (a derive would demand
// `E: Clone`, `E: Ord`, … of a type that only ever tags).
impl<E> Clone for Id<E> {
    fn clone(&self) -> Self {
        Id {
            raw: self.raw.clone(),
            _entity: PhantomData,
        }
    }
}
impl<E> std::fmt::Debug for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Id({:?})", self.raw)
    }
}
impl<E> std::fmt::Display for Id<E> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.raw)
    }
}
impl<E> PartialEq for Id<E> {
    fn eq(&self, other: &Self) -> bool {
        self.raw == other.raw
    }
}
impl<E> Eq for Id<E> {}
impl<E> PartialOrd for Id<E> {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}
impl<E> Ord for Id<E> {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.raw.cmp(&other.raw)
    }
}
impl<E> std::hash::Hash for Id<E> {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.raw.hash(state);
    }
}

/// An opaque keyset pagination cursor, carried on the wire as its underlying string
/// (`#[serde(transparent)]`, so the wire is unchanged). A page result hands one back and
/// the caller feeds it to the next call; its contents (the sort-key basis) are a runtime
/// concern the caller never assembles. Turn a raw string into one only through the
/// explicit, greppable `Cursor::from_raw`.
#[derive(Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct Cursor(String);

impl Cursor {
    /// Wrap a raw cursor string — the explicit escape used only where a cursor string
    /// arrives from outside the client (normally a page result already hands one back typed).
    pub fn from_raw(raw: impl Into<String>) -> Self {
        Cursor(raw.into())
    }
    /// The underlying cursor string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
    /// Consume into the raw cursor string.
    pub fn into_raw(self) -> String {
        self.0
    }
}

impl std::fmt::Debug for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Cursor({:?})", self.0)
    }
}
impl std::fmt::Display for Cursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Pagination envelope (calling.md): a paginated query returns rows + an opaque
/// cursor. Next page = the same call carrying `cursor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub cursor: Option<Cursor>,
}

/// What went wrong in a client call — lets a caller branch on the class of failure
/// without matching on the message text.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ClientErrorKind {
    /// The request never completed a round-trip — a socket/connection/engine failure.
    /// Retryable in the same way the underlying transport is.
    Transport,
    /// The round-trip completed but a value could not be (de)serialized into its typed
    /// input or output. A bug in the caller's types or the payload, not a server error.
    Decode,
    /// The server ran the call and returned a structured error (its HTTP `status` and a
    /// stable machine `code`, e.g. `bad_arg`, `missing_ctx`, `database_error`).
    Api { status: u16, code: String },
}

/// An error from a client call: a transport failure, a (de)serialization failure, or a
/// structured error the server returned. Carries a stable machine [`code`](ClientError::code)
/// and a clear human message; a server error also carries its HTTP [`status`](ClientError::status).
/// Implements `std::error::Error`, so it chains with `?` and its underlying cause is reachable
/// via `source()`.
#[derive(Debug, Clone)]
pub struct ClientError {
    kind: ClientErrorKind,
    message: String,
    // Kept behind an `Arc` so `ClientError` stays `Clone` while still handing back a live
    // `&dyn Error` from `source()`.
    source: Option<std::sync::Arc<dyn std::error::Error + Send + Sync + 'static>>,
}

impl ClientError {
    /// A transport failure (the round-trip never completed), wrapping its cause.
    pub fn transport(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Transport,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A (de)serialization failure decoding an input or the reply, wrapping its cause.
    pub fn decode(err: impl Into<Box<dyn std::error::Error + Send + Sync + 'static>>) -> Self {
        let err = err.into();
        ClientError {
            kind: ClientErrorKind::Decode,
            message: err.to_string(),
            source: Some(err.into()),
        }
    }

    /// A structured error the server returned: its HTTP `status`, stable machine `code`, and
    /// human `message` (the `{ error: { code, message } }` envelope).
    pub fn api(status: u16, code: impl Into<String>, message: impl Into<String>) -> Self {
        ClientError {
            kind: ClientErrorKind::Api {
                status,
                code: code.into(),
            },
            message: message.into(),
            source: None,
        }
    }

    /// The failure class (transport / decode / server-side api).
    pub fn kind(&self) -> &ClientErrorKind {
        &self.kind
    }

    /// The human-readable message.
    pub fn message(&self) -> &str {
        &self.message
    }

    /// A stable machine-readable code: the server's `error.code` for an api failure, else
    /// `"transport"` / `"decode"`. Safe to branch on.
    pub fn code(&self) -> &str {
        match &self.kind {
            ClientErrorKind::Transport => "transport",
            ClientErrorKind::Decode => "decode",
            ClientErrorKind::Api { code, .. } => code,
        }
    }

    /// The HTTP status of a server-side (api) failure; `None` for a transport/decode failure.
    pub fn status(&self) -> Option<u16> {
        match &self.kind {
            ClientErrorKind::Api { status, .. } => Some(*status),
            _ => None,
        }
    }
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match &self.kind {
            ClientErrorKind::Transport => write!(f, "transport error: {}", self.message),
            ClientErrorKind::Decode => write!(f, "decode error: {}", self.message),
            ClientErrorKind::Api { status, code } => {
                write!(f, "server error {status} [{code}]: {}", self.message)
            }
        }
    }
}

impl std::error::Error for ClientError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|e| &**e as &(dyn std::error::Error + 'static))
    }
}

/// Post a typed input to a route, carry the typed request context (`$ctx` — sent out
/// of band, never a body field, auth.md), and decode the typed output. A callable with
/// no `$ctx` requirements passes `ctx: &()`. Implemented by the runtime's HTTP client;
/// codegen only depends on this shape.
pub trait Transport {
    fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize,
        C: Serialize,
        O: serde::de::DeserializeOwned;
}

/// The generated client, generic over a `Transport`.
pub struct Client<T> {
    pub transport: T,
}

/// Phantom entity tags for `Id<entity::M>` (types only, never constructed).
pub mod entity {
    pub enum Order {}
    pub enum Org {}
    pub enum User {}
}

// ---------- output types ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrgRow {
    pub id: Id<entity::Org>,
    pub name: String,
    pub slug: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCard {
    pub id: Id<entity::Order>,
    pub status: String,
    pub total: i64,
    pub placed_by: OrderCardPlacedBy,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCardPlacedBy {
    pub name: String,
    pub email: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRow {
    pub id: Id<entity::User>,
    pub email: String,
    pub name: String,
}

// ---------- inputs + routes ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateOrgInput {
    pub name: String,
    pub slug: String,
}
/// Wire route for `create_org`.
pub const CREATE_ORG_ROUTE: &str = "/m/create_org";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderByIdInput {
    pub id: Id<entity::Order>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderByIdCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `order_by_id`.
pub const ORDER_BY_ID_ROUTE: &str = "/q/order_by_id";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrdersInput;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrdersCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `my_orders`.
pub const MY_ORDERS_ROUTE: &str = "/q/my_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentOrdersInput {
    pub cursor: Option<Cursor>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentOrdersCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `recent_orders`.
pub const RECENT_ORDERS_ROUTE: &str = "/q/recent_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaceOrderInput {
    pub buyer: Id<entity::User>,
    pub total: i64,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaceOrderCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `place_order`.
pub const PLACE_ORDER_ROUTE: &str = "/m/place_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CancelOrderInput {
    pub id: Id<entity::Order>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CancelOrderCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `cancel_order`.
pub const CANCEL_ORDER_ROUTE: &str = "/m/cancel_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreOrderInput {
    pub id: Id<entity::Order>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreOrderCtx {
    pub org: Id<entity::Org>,
}
/// Wire route for `restore_order`.
pub const RESTORE_ORDER_ROUTE: &str = "/m/restore_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserInput {
    pub email: String,
    pub name: String,
}
/// Wire route for `create_user`.
pub const CREATE_USER_ROUTE: &str = "/m/create_user";

// ---------- client ----------

impl<T: Transport> Client<T> {
    /// `POST /m/create_org`
    pub fn create_org(&self, input: CreateOrgInput, ctx: ()) -> Result<OrgRow, ClientError> {
        self.transport.call(CREATE_ORG_ROUTE, &input, &ctx)
    }
    /// `POST /q/order_by_id`
    pub fn order_by_id(&self, input: OrderByIdInput, ctx: OrderByIdCtx) -> Result<Option<OrderCard>, ClientError> {
        self.transport.call(ORDER_BY_ID_ROUTE, &input, &ctx)
    }
    /// `POST /q/my_orders`
    pub fn my_orders(&self, input: MyOrdersInput, ctx: MyOrdersCtx) -> Result<Vec<OrderCard>, ClientError> {
        self.transport.call(MY_ORDERS_ROUTE, &input, &ctx)
    }
    /// `POST /q/recent_orders`
    pub fn recent_orders(&self, input: RecentOrdersInput, ctx: RecentOrdersCtx) -> Result<Page<OrderCard>, ClientError> {
        self.transport.call(RECENT_ORDERS_ROUTE, &input, &ctx)
    }
    /// `POST /m/place_order`
    pub fn place_order(&self, input: PlaceOrderInput, ctx: PlaceOrderCtx) -> Result<OrderCard, ClientError> {
        self.transport.call(PLACE_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/cancel_order`
    pub fn cancel_order(&self, input: CancelOrderInput, ctx: CancelOrderCtx) -> Result<OrderCard, ClientError> {
        self.transport.call(CANCEL_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/restore_order`
    pub fn restore_order(&self, input: RestoreOrderInput, ctx: RestoreOrderCtx) -> Result<OrderCard, ClientError> {
        self.transport.call(RESTORE_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/create_user`
    pub fn create_user(&self, input: CreateUserInput, ctx: ()) -> Result<UserRow, ClientError> {
        self.transport.call(CREATE_USER_ROUTE, &input, &ctx)
    }
}

// ---------- embedded bridge (based_runtime::Engine) ----------

/// A `Transport` backed by an in-process `based_runtime::Engine` — every callable runs
/// through the engine's dispatch core with no socket. Build one with [`embedded`].
pub struct Embedded<'a> {
    engine: &'a based_runtime::Engine,
}

impl Transport for Embedded<'_> {
    fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize,
        C: Serialize,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(ClientError::decode)?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| if v.is_object() { v } else { serde_json::json!({}) })
            .map_err(ClientError::decode)?;
        let resp = self.engine.call(route, args, ctx);
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(ClientError::decode)
        } else {
            // Preserve the server's structured error: its status + stable code + message.
            let code = resp.body["error"]["code"].as_str().unwrap_or("error");
            let message = resp.body["error"]["message"].as_str().unwrap_or("call failed");
            Err(ClientError::api(resp.status, code, message))
        }
    }
}

/// A ready-to-use client over an in-process `based_runtime::Engine` — no bridge to write.
/// `$ctx` is a typed per-call argument (auth.md still holds: the app sets it, not the
/// caller); a public callable passes `()`, which maps to an empty context bag.
pub fn embedded(engine: &based_runtime::Engine) -> Client<Embedded<'_>> {
    Client {
        transport: Embedded { engine },
    }
}
