//! Serialize a [`Snapshot`] to the canonical `schema.snap` text. Deterministic — the
//! same snapshot renders byte-identically every time (no wall-clock, no map order).

use super::*;
use based_sema::CheckedSchema;
use std::fmt::Write as _;

/// Serialize a resolved schema to the canonical `schema.snap` text. Convenience over
/// [`Snapshot::from_schema`] + [`Snapshot::render`].
pub fn snapshot(schema: &CheckedSchema) -> String {
    Snapshot::from_schema(schema).render()
}

impl Snapshot {
    /// Render this snapshot to the canonical `schema.snap` text. Deterministic — the
    /// same snapshot renders byte-identically every time (no wall-clock, no map order).
    pub fn render(&self) -> String {
        let mut out = String::new();
        out.push_str("# schema.snap — generated by `based migrate gen`; do not edit by hand.\n");
        out.push_str("snapshot v1 dialect=neutral\n");
        for s in &self.scopes {
            out.push_str(&render_scope_decl(s));
            out.push('\n');
        }
        for r in &self.renames {
            out.push_str(&render_rename(r));
            out.push('\n');
        }
        for t in &self.tables {
            out.push('\n');
            render_table(&mut out, t);
        }
        out
    }
}

/// One `scope Name (col: Type = $ctx.field, …)` decl line.
pub(crate) fn render_scope_decl(s: &ScopeDeclSnap) -> String {
    let terms = s
        .terms
        .iter()
        .map(|t| format!("{}: {} = $ctx.{}", t.column, t.ty, t.ctx_field))
        .collect::<Vec<_>>()
        .join(", ");
    format!("scope {} ({terms})", s.name)
}

/// One `rename table <old> -> <new>` / `rename column <table>.<old> -> <new>` line —
/// the `@was` directive persisted so the diff re-derives the rename offline.
fn render_rename(r: &Rename) -> String {
    match r {
        Rename::Table { from, to } => format!("rename table {from} -> {to}"),
        Rename::Column { table, from, to } => format!("rename column {table}.{from} -> {to}"),
    }
}

fn render_table(out: &mut String, t: &TableSnap) {
    let mut header = format!("table {}", t.name);
    if let Some(s) = &t.schema {
        let _ = write!(header, " schema={s}");
    }
    if let Some((col, mode)) = &t.soft_delete {
        let _ = write!(header, " soft_delete={col}:{mode}");
    }
    if let Some(col) = &t.created {
        let _ = write!(header, " created={col}");
    }
    if let Some(col) = &t.updated {
        let _ = write!(header, " updated={col}");
    }
    // One `scope=(A, B)` group per `@scope` alternative (DNF): the commas inside a group
    // are the AND-conjunction, separate groups are the OR-alternatives.
    for alt in &t.scope_alts {
        let _ = write!(header, " scope=({})", alt.join(", "));
    }
    if !t.sort.is_empty() {
        let terms = t
            .sort
            .iter()
            .map(|(c, d)| format!("{c} {d}"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(header, " sort=({terms})");
    }
    if t.no_id {
        header.push_str(" no_id");
    }
    if !t.pk.is_empty() {
        let _ = write!(header, " pk={}", col_list_text(&t.pk));
    }
    header.push('\n');
    out.push_str(&header);

    for c in &t.columns {
        let mut line = format!(
            "  column {} {} {}",
            c.name,
            c.ty,
            if c.nullable { "null" } else { "not_null" }
        );
        if let Some(d) = &c.default {
            let _ = write!(line, " default={d}");
        }
        if c.unique {
            line.push_str(" unique");
        }
        if let Some(fk) = &c.fk {
            let _ = write!(line, " fk={fk}");
        }
        // A generated column trails its neutral expression in balanced parens; it may hold
        // spaces, so the parser pulls it out as one token (like a `raw(…)` type).
        if let Some(g) = &c.generated {
            let _ = write!(line, " generated=({g})");
        }
        line.push('\n');
        out.push_str(&line);
    }
    for i in &t.indexes {
        out.push_str(&format!("  index {}\n", index_spec_text(i)));
    }
    for f in &t.foreign_keys {
        out.push_str(&format!("  {}\n", fk_spec_text(f)));
    }
}

/// The `fk <col> -> <ref_table>.<ref_col> [on_delete=<a>] [on_update=<a>]` line shared by
/// the `schema.snap` FK line and the `up.mig` foreign-key step. A composite FK renders its
/// column lists as `(c1, c2)` tuples; a single-column FK stays the bare-name form.
pub fn fk_spec_text(f: &ForeignKeySnap) -> String {
    // A cross-schema target renders `schema::table` — `::` keeps the schema separable from
    // the `.` between the table and its column list on parse.
    let ref_table = match &f.ref_schema {
        Some(sc) => format!("{sc}::{}", f.ref_table),
        None => f.ref_table.clone(),
    };
    let mut s = format!(
        "fk {} -> {}.{}",
        col_list_text(&f.columns),
        ref_table,
        col_list_text(&f.ref_columns)
    );
    if let Some(a) = &f.on_delete {
        let _ = write!(s, " on_delete={a}");
    }
    if let Some(a) = &f.on_update {
        let _ = write!(s, " on_update={a}");
    }
    s
}

/// The `<name> (<cols>) [unique] [using <m>]` / `<name> raw(…)` spec shared by the
/// `schema.snap` index line and the `up.mig` index step, so both read identically.
pub(crate) fn index_spec_text(i: &IndexSnap) -> String {
    if let Some(raw) = &i.raw {
        return format!("{} {raw}", i.name);
    }
    let mut line = format!("{} ({})", i.name, i.columns.join(", "));
    if i.unique {
        line.push_str(" unique");
    }
    if let Some(m) = &i.method {
        line.push_str(&format!(" using {m}"));
    }
    line
}

/// Render an FK column list: a bare name for one column, a `(c1, c2)` tuple for several.
pub(crate) fn col_list_text(cols: &[String]) -> String {
    match cols {
        [c] => c.clone(),
        cs => format!("({})", cs.join(", ")),
    }
}
