//! CLI generation must not depend on PATH, invoking directory, or consumer rustfmt.
use std::path::{Path, PathBuf};
use std::process::Command;

struct Scratch(PathBuf);

impl Scratch {
    fn new() -> Self {
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path =
            std::env::temp_dir().join(format!("based-layout-{}-{stamp}", std::process::id()));
        std::fs::create_dir_all(&path).unwrap();
        Self(path)
    }

    fn write(&self, relative: &str, text: &str) {
        let path = self.0.join(relative);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, text).unwrap();
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn generate(root: &Path, cwd: &Path, path: Option<&Path>) -> Vec<u8> {
    let mut cmd = Command::new(env!("CARGO_BIN_EXE_based"));
    cmd.args(["gen", "client"]).arg(root).current_dir(cwd);
    if let Some(path) = path {
        cmd.env("PATH", path);
    }
    let output = cmd.output().unwrap();
    assert!(output.status.success(), "{output:?}");
    output.stdout
}

#[test]
fn generation_and_include_wrapper_ignore_consumer_formatting() {
    let scratch = Scratch::new();
    scratch.write("based.toml", "dialect = \"sqlite\"\n");
    scratch.write(
        "schema.bsl",
        "Item { id: Id name: text }\nquery item(id) -> Item;\n",
    );
    scratch.write("other/rustfmt.toml", "max_width = 60\n");
    let root = &scratch.0;
    let generated = generate(root, root, None);
    assert_eq!(
        generated,
        generate(root, root, Some(&root.join("no-tools")))
    );
    assert_eq!(generated, generate(root, &root.join("other"), None));
    assert_eq!(generated, generate(root, root, None));
    assert!(String::from_utf8_lossy(&generated).starts_with("// Generated by"));

    for edition in ["2021", "2024"] {
        scratch.write(
            "Cargo.toml",
            &format!("[package]\nname = \"layout-consumer\"\nversion = \"0.1.0\"\nedition = \"{edition}\"\n[workspace]\n"),
        );
        scratch.write("rustfmt.toml", "max_width = 60\n");
        scratch.write(
            "generated/client.rs",
            std::str::from_utf8(&generated).unwrap(),
        );
        scratch.write(
            "src/lib.rs",
            "#[allow(dead_code)] mod client {include!(\"../generated/client.rs\");}\n",
        );
        let output = Command::new("cargo")
            .arg("fmt")
            .current_dir(root)
            .output()
            .unwrap();
        assert!(output.status.success(), "{output:?}");
        let formatted = std::fs::read_to_string(root.join("src/lib.rs")).unwrap();
        assert!(
            formatted.contains("mod client {\n"),
            "wrapper was not formatted"
        );
        let check = Command::new("cargo")
            .args(["fmt", "--check"])
            .current_dir(root)
            .output()
            .unwrap();
        assert!(check.status.success(), "{check:?}");
        assert_eq!(
            generated,
            std::fs::read(root.join("generated/client.rs")).unwrap()
        );
    }
}
