//! Ownership-aware, staged publication of generated artifacts. No compiler or database.
mod error;
mod ownership;
mod publish;
mod stage;

pub use error::Error;
pub use ownership::Format;
pub use publish::publish;

use std::path::PathBuf;

/// Fully generated bytes ready for publication; generation must finish before publishing.
pub struct Artifact {
    /// Resolved destination; callers own manifest-relative resolution and protected paths.
    pub path: PathBuf,
    pub bytes: Vec<u8>,
    pub format: Format,
}

#[derive(Clone, Copy)]
pub enum Policy {
    /// Compare only: never create directories, stage bytes, or write files.
    Check,
    Write {
        overwrite_user_owned: bool,
    },
}

#[derive(Default)]
pub struct Report {
    pub written: Vec<PathBuf>,
    pub unchanged: Vec<PathBuf>,
}
