//! Artifact-specific ownership markers and reproducible regeneration annotations.
use crate::Error;

#[derive(Clone, Copy)]
pub enum Format {
    Rust,
    Sql,
    OpenApi,
}

impl Format {
    pub(crate) fn owns_any(bytes: &[u8]) -> bool {
        [Self::Rust, Self::Sql, Self::OpenApi]
            .into_iter()
            .any(|format| format.owns(bytes))
    }

    pub fn owns(self, bytes: &[u8]) -> bool {
        match self {
            Self::Rust => bytes.starts_with(b"// Generated by `based gen client`"),
            Self::Sql => bytes.starts_with(b"-- Generated by `based gen sql`"),
            Self::OpenApi => serde_json::from_slice::<serde_json::Value>(bytes)
                .is_ok_and(|value| value["x-based-generated"]["owner"] == "based"),
        }
    }

    pub fn annotate(self, content: &str, command: &str) -> Result<Vec<u8>, Error> {
        if command.chars().any(char::is_control) {
            return Err(Error::Invalid(
                "regeneration command contains control characters".into(),
            ));
        }
        if matches!(self, Self::OpenApi) {
            return annotate_json(content, command);
        }
        if !self.owns(content.as_bytes()) {
            return Err(Error::Invalid(
                "generated artifact is missing its ownership header".into(),
            ));
        }
        let (header, body) = content.split_once('\n').unwrap_or((content, ""));
        let prefix = match self {
            Self::Rust => "//",
            Self::Sql => "--",
            Self::OpenApi => unreachable!(),
        };
        Ok(
            format!("{header}\n{prefix} Regenerate from the manifest directory: {command}\n{body}")
                .into_bytes(),
        )
    }
}

fn annotate_json(content: &str, command: &str) -> Result<Vec<u8>, Error> {
    let mut value: serde_json::Value = serde_json::from_str(content)
        .map_err(|error| Error::Invalid(format!("invalid generated OpenAPI JSON: {error}")))?;
    let Some(object) = value.as_object_mut() else {
        return Err(Error::Invalid(
            "generated OpenAPI document must be an object".into(),
        ));
    };
    object.insert(
        "x-based-generated".into(),
        serde_json::json!({ "owner": "based", "regenerate": command }),
    );
    let mut bytes =
        serde_json::to_vec_pretty(&value).map_err(|error| Error::Invalid(error.to_string()))?;
    bytes.push(b'\n');
    Ok(bytes)
}
