SELECT ku.CONSTRAINT_NAME, ku.COLUMN_NAME, ku.REFERENCED_TABLE_SCHEMA,
       ku.REFERENCED_TABLE_NAME, ku.REFERENCED_COLUMN_NAME, rc.DELETE_RULE, rc.UPDATE_RULE
FROM information_schema.KEY_COLUMN_USAGE ku
JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
 ON rc.CONSTRAINT_SCHEMA = ku.CONSTRAINT_SCHEMA AND rc.CONSTRAINT_NAME = ku.CONSTRAINT_NAME
 AND rc.TABLE_NAME = ku.TABLE_NAME
WHERE ku.TABLE_SCHEMA = ? AND ku.TABLE_NAME = ? AND ku.REFERENCED_TABLE_NAME IS NOT NULL
ORDER BY ku.CONSTRAINT_NAME, ku.ORDINAL_POSITION
