SELECT (
 EXISTS(SELECT 1 FROM information_schema.USER_PRIVILEGES
        WHERE GRANTEE = ? AND PRIVILEGE_TYPE IN ('REFERENCES', 'SELECT'))
 OR EXISTS(SELECT 1 FROM information_schema.SCHEMA_PRIVILEGES
           WHERE GRANTEE = ? AND TABLE_SCHEMA = ? AND PRIVILEGE_TYPE IN ('REFERENCES', 'SELECT'))
 OR EXISTS(SELECT 1 FROM information_schema.TABLE_PRIVILEGES
           WHERE GRANTEE = ? AND TABLE_SCHEMA = ? AND TABLE_NAME = ? AND PRIVILEGE_TYPE IN ('REFERENCES', 'SELECT'))
) AS visible
