// Generated by `based gen client` (target: rust). Do not edit by hand.
//
// The closed RPC surface (calling.md): one input type, one output type, and one
// route per signature. Transport is abstract — implement `Transport` to post JSON
// to a route and decode the reply; the runtime supplies the concrete HTTP client.
//
// Some generated items may be unused by a given consumer; suppress dead-code warnings by
// including this module under an outer `#[allow(dead_code)] mod client { … }` (the standard
// pattern for generated code — an inner `#![allow]` would be rejected by `include!`).

use serde::{Deserialize, Serialize};

// Semantic aliases for the wire types (mirrors the DDL mapping, D10).
pub type Uuid = String;
pub type Timestamp = String;
pub type Date = String;
pub type Json = serde_json::Value;

/// Pagination envelope (calling.md): a paginated query returns rows + an opaque
/// cursor, never a bare array. Next page = the same call carrying `cursor`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Page<T> {
    pub rows: Vec<T>,
    pub cursor: Option<String>,
}

/// An error from a client call (transport failure or decode failure). The concrete
/// `Transport` decides how to populate it.
#[derive(Debug, Clone)]
pub struct ClientError(pub String);

/// Post a typed input to a route, carry the typed request context (`$ctx`, D4/D5 —
/// sent out of band, never a body field, auth.md/D7), and decode the typed output.
/// A callable with no `$ctx` requirements passes `ctx: &()`. Implemented by the
/// runtime's HTTP client; codegen only depends on this shape.
pub trait Transport {
    fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize,
        C: Serialize,
        O: serde::de::DeserializeOwned;
}

/// The generated client, generic over a `Transport`.
pub struct Client<T> {
    pub transport: T,
}

// ---------- output types ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrgRow {
    pub id: Uuid,
    pub name: String,
    pub slug: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCard {
    pub id: Uuid,
    pub status: String,
    pub total: i64,
    pub placed_by: OrderCardPlacedBy,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderCardPlacedBy {
    pub name: String,
    pub email: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRow {
    pub id: Uuid,
    pub email: String,
    pub name: String,
}

// ---------- inputs + routes ----------

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateOrgInput {
    pub name: String,
    pub slug: String,
}
/// Wire route for `create_org`.
pub const CREATE_ORG_ROUTE: &str = "/m/create_org";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderByIdInput {
    pub id: Uuid,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderByIdCtx {
    pub org: Uuid,
}
/// Wire route for `order_by_id`.
pub const ORDER_BY_ID_ROUTE: &str = "/q/order_by_id";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrdersInput;
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MyOrdersCtx {
    pub org: Uuid,
}
/// Wire route for `my_orders`.
pub const MY_ORDERS_ROUTE: &str = "/q/my_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentOrdersInput {
    pub cursor: Option<String>,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RecentOrdersCtx {
    pub org: Uuid,
}
/// Wire route for `recent_orders`.
pub const RECENT_ORDERS_ROUTE: &str = "/q/recent_orders";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaceOrderInput {
    pub buyer: Uuid,
    pub total: i64,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlaceOrderCtx {
    pub org: Uuid,
}
/// Wire route for `place_order`.
pub const PLACE_ORDER_ROUTE: &str = "/m/place_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CancelOrderInput {
    pub id: Uuid,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CancelOrderCtx {
    pub org: Uuid,
}
/// Wire route for `cancel_order`.
pub const CANCEL_ORDER_ROUTE: &str = "/m/cancel_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreOrderInput {
    pub id: Uuid,
}
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RestoreOrderCtx {
    pub org: Uuid,
}
/// Wire route for `restore_order`.
pub const RESTORE_ORDER_ROUTE: &str = "/m/restore_order";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserInput {
    pub email: String,
    pub name: String,
}
/// Wire route for `create_user`.
pub const CREATE_USER_ROUTE: &str = "/m/create_user";

// ---------- client ----------

impl<T: Transport> Client<T> {
    /// `POST /m/create_org`
    pub fn create_org(&self, input: CreateOrgInput, ctx: ()) -> Result<OrgRow, ClientError> {
        self.transport.call(CREATE_ORG_ROUTE, &input, &ctx)
    }
    /// `POST /q/order_by_id`
    pub fn order_by_id(
        &self,
        input: OrderByIdInput,
        ctx: OrderByIdCtx,
    ) -> Result<Option<OrderCard>, ClientError> {
        self.transport.call(ORDER_BY_ID_ROUTE, &input, &ctx)
    }
    /// `POST /q/my_orders`
    pub fn my_orders(
        &self,
        input: MyOrdersInput,
        ctx: MyOrdersCtx,
    ) -> Result<Vec<OrderCard>, ClientError> {
        self.transport.call(MY_ORDERS_ROUTE, &input, &ctx)
    }
    /// `POST /q/recent_orders`
    pub fn recent_orders(
        &self,
        input: RecentOrdersInput,
        ctx: RecentOrdersCtx,
    ) -> Result<Page<OrderCard>, ClientError> {
        self.transport.call(RECENT_ORDERS_ROUTE, &input, &ctx)
    }
    /// `POST /m/place_order`
    pub fn place_order(
        &self,
        input: PlaceOrderInput,
        ctx: PlaceOrderCtx,
    ) -> Result<OrderCard, ClientError> {
        self.transport.call(PLACE_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/cancel_order`
    pub fn cancel_order(
        &self,
        input: CancelOrderInput,
        ctx: CancelOrderCtx,
    ) -> Result<OrderCard, ClientError> {
        self.transport.call(CANCEL_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/restore_order`
    pub fn restore_order(
        &self,
        input: RestoreOrderInput,
        ctx: RestoreOrderCtx,
    ) -> Result<OrderCard, ClientError> {
        self.transport.call(RESTORE_ORDER_ROUTE, &input, &ctx)
    }
    /// `POST /m/create_user`
    pub fn create_user(&self, input: CreateUserInput, ctx: ()) -> Result<UserRow, ClientError> {
        self.transport.call(CREATE_USER_ROUTE, &input, &ctx)
    }
}

// ---------- embedded bridge (based_runtime::Engine, D62) ----------

/// A `Transport` backed by an in-process `based_runtime::Engine` — every callable runs
/// through the engine's dispatch core with no socket. Build one with [`embedded`].
pub struct Embedded<'a> {
    engine: &'a based_runtime::Engine,
}

impl Transport for Embedded<'_> {
    fn call<I, C, O>(&self, route: &str, input: &I, ctx: &C) -> Result<O, ClientError>
    where
        I: Serialize,
        C: Serialize,
        O: serde::de::DeserializeOwned,
    {
        let args = serde_json::to_value(input).map_err(|e| ClientError(e.to_string()))?;
        // `&()` → JSON `null`; the engine treats a non-object context as empty.
        let ctx = serde_json::to_value(ctx)
            .map(|v| {
                if v.is_object() {
                    v
                } else {
                    serde_json::json!({})
                }
            })
            .map_err(|e| ClientError(e.to_string()))?;
        let resp = self.engine.call(route, args, ctx);
        if resp.status == 200 {
            serde_json::from_value(resp.body).map_err(|e| ClientError(e.to_string()))
        } else {
            let msg = resp.body["error"]["message"]
                .as_str()
                .unwrap_or("call failed");
            Err(ClientError(msg.to_string()))
        }
    }
}

/// A ready-to-use client over an in-process `based_runtime::Engine` — no bridge to write.
/// `$ctx` is a typed per-call argument (auth.md/D7 still holds: the app sets it, not the
/// caller); a public callable passes `()`, which maps to an empty context bag.
pub fn embedded(engine: &based_runtime::Engine) -> Client<Embedded<'_>> {
    Client {
        transport: Embedded { engine },
    }
}
